# Spatial niche analysis figures
#
# This script generates figures for spatial niche analysis using the summary
# tables generated by:
#   04_03_niche_summarize_spatial_niche_composition.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(patchwork)
  library(ragg)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define input and output directories ---------------------------------------

niche_table_dir <- file.path(xenium_table_dir, "niche_analysis")

niche_figure_dir <- file.path(
  niche_analysis_figure_dir,
  "08_04_01_niche_analysis"
)

fs::dir_create(niche_figure_dir)


## Define niche annotations, colors, and display order ------------------------

niche_order <- paste0("niche_", c(2, 3, 8, 9, 5, 6, 1, 4, 7, 10))

niche_annotation <- c(
  "niche_1" = "N7. Plasma cell niche",
  "niche_2" = "N1. Normal acinar niche",
  "niche_3" = "N2. Atrophic acinar niche",
  "niche_4" = "N8. Lymphoid niche",
  "niche_5" = "N5. Islet niche",
  "niche_6" = "N6. Vascular niche",
  "niche_7" = "N9. Lymphoid–myeloid niche",
  "niche_8" = "N3. Normal–PanIN niche",
  "niche_9" = "N4. Cancer niche",
  "niche_10" = "N10. Neuronal niche"
)

initial_cluster_display_order <- as.character(c(
  0, 13, 24,
  33, 12, 1, 17, 30,
  23,
  10, 27,
  20,
  14,
  11,
  34, 3,
  18, 37,
  15,
  16, 2,
  5, 4, 31,
  26,
  29
))

initial_label_display_order <- paste0("Ini-", initial_cluster_display_order)

label_display_order <- c(
  caf_subcluster_display_order,
  initial_label_display_order
)

initial_label_names <- c(
  "Ini-0"  = "C0. Acinar",
  "Ini-13" = "C13. Acinar",
  "Ini-24" = "C24. Acinar",
  "Ini-33" = "C33. Ductal-like acinar",
  "Ini-12" = "C12. Ductal-like acinar",
  "Ini-1"  = "C1. Ductal-like acinar",
  "Ini-17" = "C17. Ductal-like acinar",
  "Ini-30" = "C30. Ductal-like acinar",
  "Ini-23" = "C23. Normal ductal",
  "Ini-10" = "C10. PanIN",
  "Ini-27" = "C27. PanIN",
  "Ini-20" = "C20. PDAC",
  "Ini-14" = "C14. Islet",
  "Ini-11" = "C11. Mural",
  "Ini-34" = "C34. Endothelial",
  "Ini-3"  = "C3. Endothelial",
  "Ini-18" = "C18. Plasma",
  "Ini-37" = "C37. Plasma",
  "Ini-15" = "C15. B cell",
  "Ini-16" = "C16. T cell",
  "Ini-2"  = "C2. T cell",
  "Ini-5"  = "C5. Myeloid",
  "Ini-4"  = "C4. Myeloid",
  "Ini-31" = "C31. Myeloid",
  "Ini-26" = "C26. Mast",
  "Ini-29" = "C29. Neuronal"
)

# Broader cell-type groups shown below the x-axis of the supplementary heatmap.
# Plasma cells are shown separately from T/B lymphocytes because their
# transcriptional state and niche distribution are distinct.
initial_cluster_group_table <- tibble::tribble(
  ~label_for_summary, ~cluster_number, ~cell_type_group,
  "Ini-0",  "0",  "Acinar cell",
  "Ini-13", "13", "Acinar cell",
  "Ini-24", "24", "Acinar cell",
  "Ini-33", "33", "Ductal-like acinar cell",
  "Ini-12", "12", "Ductal-like acinar cell",
  "Ini-1",  "1",  "Ductal-like acinar cell",
  "Ini-17", "17", "Ductal-like acinar cell",
  "Ini-30", "30", "Ductal-like acinar cell",
  "Ini-23", "23", "Normal ductal cell",
  "Ini-10", "10", "PanIN",
  "Ini-27", "27", "PanIN",
  "Ini-20", "20", "PDAC",
  "Ini-14", "14", "Islet cell",
  "Ini-11", "11", "Mural/endothelial cell",
  "Ini-34", "34", "Mural/endothelial cell",
  "Ini-3",  "3",  "Mural/endothelial cell",
  "Ini-18", "18", "Plasma cell",
  "Ini-37", "37", "Plasma cell",
  "Ini-15", "15", "T/B lymphocyte",
  "Ini-16", "16", "T/B lymphocyte",
  "Ini-2",  "2",  "T/B lymphocyte",
  "Ini-5",  "5",  "Myeloid cell",
  "Ini-4",  "4",  "Myeloid cell",
  "Ini-31", "31", "Myeloid cell",
  "Ini-26", "26", "Mast cell",
  "Ini-29", "29", "Neuronal cell"
)

label_names <- c(
  stats::setNames(caf_subcluster_display_order, caf_subcluster_display_order),
  initial_label_names
)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}


## Read input tables ---------------------------------------------------------

niche_label_count_table <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_cell_count_by_label.csv"),
  "Spatial niche cell count by label table"
)

caf_subcluster_niche_table <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_caf_subcluster_composition.csv"),
  "Spatial niche CAF subcluster composition table"
)

spatial_niche_metadata_table <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_cell_metadata.csv"),
  "Spatial niche cell metadata table"
)

caf_subcluster_metadata_table <- read_required_csv(
  caf_subcluster_metadata_file,
  "CAF subcluster metadata table"
)

check_required_columns(
  niche_label_count_table,
  c(
    "niche",
    "niche_annotation",
    "label_for_summary",
    "n_cell",
    "prop_within_niche",
    "prop_within_label"
  ),
  "spatial niche cell count by label table"
)

check_required_columns(
  caf_subcluster_niche_table,
  c(
    "niche",
    "niche_annotation",
    "caf_subcluster",
    "n_cell",
    "prop_caf_subcluster_within_niche",
    "prop_niche_within_caf_subcluster"
  ),
  "spatial niche CAF subcluster composition table"
)

check_required_columns(
  spatial_niche_metadata_table,
  c(
    "full_id",
    "niche",
    "niche_annotation",
    "caf_subcluster"
  ),
  "spatial niche cell metadata table"
)

check_required_columns(
  caf_subcluster_metadata_table,
  c(
    "cell_id",
    "xenium_sample_id",
    "tx_id",
    "caf_subcluster",
    "caf_umap_1",
    "caf_umap_2"
  ),
  "CAF subcluster metadata table"
)


## Prepare plotting labels ---------------------------------------------------

# Drop rare non-CAF initial clusters when their maximum contribution to any
# niche is less than 1%. The filtered order is used for the supplementary
# non-CAF heatmap and the composition barplot.
initial_labels_to_drop <- niche_label_count_table %>%
  dplyr::filter(stringr::str_detect(.data$label_for_summary, "^Ini-")) %>%
  dplyr::group_by(.data$label_for_summary) %>%
  dplyr::summarise(
    max_prop_within_niche = max(.data$prop_within_niche, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::filter(.data$max_prop_within_niche < 0.01) %>%
  dplyr::pull(.data$label_for_summary)

non_caf_label_display_order_for_supplementary <- setdiff(
  initial_label_display_order,
  initial_labels_to_drop
)


label_display_order_for_barplot <- setdiff(
  label_display_order,
  initial_labels_to_drop
)


## Plot niche composition heatmaps -------------------------------------------

make_niche_composition_heatmap <- function(
    plot_table,
    fill_column,
    fill_title,
    fill_breaks,
    viridis_option
) {
  fill_values <- dplyr::pull(plot_table, {{ fill_column }})
  fill_max <- max(fill_values, na.rm = TRUE)
  ggplot(
    plot_table,
    aes(
      x = .data$label_for_summary,
      y = .data$niche,
      fill = {{ fill_column }}
    )
  ) +
    geom_tile(color = "gray25", linewidth = 0.2) +
    scale_x_discrete(
      expand = expansion(mult = c(0, 0)),
      labels = label_names
    ) +
    scale_y_discrete(
      expand = expansion(mult = c(0, 0)),
      labels = niche_annotation,
      position = "right"
    ) +
    scale_fill_viridis_c(
      option = viridis_option,
      trans = "sqrt",
      limits = c(
        0, 
        fill_max
      ),
      breaks = fill_breaks,
      labels = function(x) x * 100,
      guide = guide_colorbar(
        direction = "horizontal",
        title.position = "top",
        title.hjust = 0.5,
        frame.colour = "black",
        ticks.colour = "black"
      )
    ) +
    labs(
      x = NULL,
      y = NULL,
      fill = fill_title
    ) +
    coord_fixed(ratio = 1.10) +
    theme_classic() +
    theme(
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        vjust = 1,
        color = "black"
      ),
      axis.text.y = element_text(color = "black"),
      legend.position = "bottom",
      legend.title = element_text(color = "black"),
      legend.text = element_text(color = "black"),
      axis.line = element_blank(),
      panel.border = element_rect(fill = NA, color = "black"),
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      legend.background = element_rect(fill = "transparent", color = NA)
    )
}


## Supplementary heatmap: non-CAF clusters only ------------------------------

niche_label_count_supplementary_heatmap_table <- niche_label_count_table %>%
  dplyr::filter(.data$label_for_summary %in% non_caf_label_display_order_for_supplementary) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = rev(niche_order)),
    label_for_summary = factor(
      .data$label_for_summary,
      levels = non_caf_label_display_order_for_supplementary
    )
  )

# Prepare the three-level x-axis: cluster number, grouping segment, and group
# name. Positions are recalculated after rare clusters are excluded.
supplementary_heatmap_axis_table <- initial_cluster_group_table %>%
  dplyr::filter(.data$label_for_summary %in% non_caf_label_display_order_for_supplementary) %>%
  dplyr::mutate(
    label_for_summary = factor(
      .data$label_for_summary,
      levels = non_caf_label_display_order_for_supplementary
    ),
    x_position = as.numeric(.data$label_for_summary)
  ) %>%
  dplyr::arrange(.data$x_position)

supplementary_heatmap_group_table <- supplementary_heatmap_axis_table %>%
  dplyr::group_by(.data$cell_type_group) %>%
  dplyr::summarise(
    x_min = min(.data$x_position) - 0.32,
    x_max = max(.data$x_position) + 0.32,
    x_mid = mean(range(.data$x_position)),
    .groups = "drop"
  )

supplementary_heatmap_highlight_table <- tibble::tribble(
  ~xmin, ~xmax, ~ymin, ~ymax,
   0.5,   5.5,   9.5,  10.5,
   3.5,   7.5,   8.5,   9.5,
   7.5,  10.5,   7.5,   8.5,
  10.5,  11.5,   6.5,   7.5,
  11.5,  12.5,   5.5,   6.5,
  12.5,  14.5,   4.5,   5.5,
  14.5,  15.5,   3.5,   4.5,
  15.5,  18.5,   2.5,   3.5,
  15.5,  20.5,   1.5,   2.5,
  22.5,  23.5,   0.5,   1.5
)

cluster_composition_within_niche_heatmap_supplementary_panel <-
  make_niche_composition_heatmap(
    plot_table = niche_label_count_supplementary_heatmap_table,
    fill_column = prop_within_niche,
    fill_title = "Cluster composition\nwithin each niche (%)",
    fill_breaks = c(0, 0.2, 0.4, 0.6),
    viridis_option = "magma"
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    plot.margin = margin(
      t = 5.5,
      r = 5.5,
      b = 0,
      l = 5.5
    )
  ) +
  geom_rect(
    data = supplementary_heatmap_highlight_table,
    aes(
      xmin = .data$xmin,
      xmax = .data$xmax,
      ymin = .data$ymin,
      ymax = .data$ymax
    ),
    inherit.aes = FALSE,
    fill = NA,
    color = "orange"
  )

supplementary_heatmap_group_axis <- ggplot() +
  geom_text(
    data = supplementary_heatmap_axis_table,
    aes(
      x = .data$x_position,
      y = 3.0,
      label = .data$cluster_number
    ),
    size = 9 / ggplot2::.pt,
    color = "black",
    vjust = 1.2
  ) +
  geom_segment(
    data = supplementary_heatmap_group_table,
    aes(
      x = .data$x_min,
      xend = .data$x_max,
      y = 2.60,
      yend = 2.60
    ),
    linewidth = 0.7,
    lineend = "butt",
    color = "black"
  ) +
  geom_text(
    data = supplementary_heatmap_group_table,
    aes(
      x = .data$x_mid,
      y = 2.4,
      label = .data$cell_type_group
    ),
    angle = 45,
    hjust = 1,
    vjust = 0.65,
    size = 9 / ggplot2::.pt,
    color = "black"
  ) +
  scale_x_continuous(
    limits = c(
      0.5,
      length(non_caf_label_display_order_for_supplementary) + 0.5
    ),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    limits = c(0, 3),
    expand = expansion(mult = c(0, 0))
  ) +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    plot.margin = margin(t = 0, r = 5.5, b = 2, l = 5.5),
    plot.background = element_rect(fill = "transparent", color = NA)
  )

cluster_composition_within_niche_heatmap_supplementary_figure <-
  cluster_composition_within_niche_heatmap_supplementary_panel /
  supplementary_heatmap_group_axis +
  patchwork::plot_layout(
    heights = c(NA, 0.27),
    guides = "collect"
  ) &
  theme(
    legend.position = "bottom",
    legend.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA)
  )

ggsave(
  plot = cluster_composition_within_niche_heatmap_supplementary_figure,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_non_caf_cluster_composition_heatmap.pdf"
  ),
  width = 7,
  height = 5,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)


## Full heatmaps: CAF subclusters and all non-CAF clusters --------------------

niche_label_count_full_heatmap_table <- niche_label_count_table %>%
  dplyr::filter(.data$label_for_summary %in% label_display_order) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = rev(niche_order)),
    label_for_summary = factor(
      .data$label_for_summary,
      levels = label_display_order
    )
  )

cluster_composition_within_niche_heatmap_full <-
  make_niche_composition_heatmap(
    plot_table = niche_label_count_full_heatmap_table,
    fill_column = prop_within_niche,
    fill_title = "Cluster composition\nwithin each niche (%)",
    fill_breaks = c(0, 0.2, 0.4, 0.6),
    viridis_option = "magma"
  )

niche_proportion_within_cluster_heatmap_full <-
  make_niche_composition_heatmap(
    plot_table = niche_label_count_full_heatmap_table,
    fill_column = prop_within_label,
    fill_title = "Niche proportion\nwithin each cluster (%)",
    fill_breaks = c(0, 0.25, 0.50, 0.75),
    viridis_option = "mako"
  )

niche_composition_heatmaps_full <- (
  cluster_composition_within_niche_heatmap_full /
    niche_proportion_within_cluster_heatmap_full
) & 
  theme(
    legend.position = "right"
  )

ggsave(
  plot = niche_composition_heatmaps_full,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_cluster_composition_heatmaps_full.pdf"
  ),
  width = 12,
  height = 7,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)

niche_proportion_barplot_table <- niche_label_count_table %>%
  dplyr::filter(.data$label_for_summary %in% label_display_order_for_barplot) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = rev(niche_order)),
    label_for_summary = factor(
      .data$label_for_summary,
      levels = rev(label_display_order_for_barplot)
    ),
    caf_or_non_caf = dplyr::if_else(
      stringr::str_detect(as.character(.data$label_for_summary), "^Ini-"),
      "Non-CAF",
      "CAF"
    ),
    caf_or_non_caf = factor(.data$caf_or_non_caf, levels = c("Non-CAF", "CAF"))
  )


## Plot niche proportion within each cluster ---------------------------------

niche_proportion_within_cluster_barplot <- ggplot(
  niche_proportion_barplot_table,
  aes(
    y = .data$label_for_summary,
    x = .data$n_cell,
    fill = .data$niche
  )
) +
  geom_col(
    position = "fill",
    color = "gray40",
    linewidth = 0.25,
    width = 1
  ) +
  facet_grid(
    caf_or_non_caf ~ .,
    scales = "free_y",
    space = "free_y",
    axes = "all"
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0)),
    labels = scales::percent_format(accuracy = 1)
  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0, 0)),
    labels = label_names
  ) +
  scale_fill_manual(
    values = niche_colors,
    breaks = niche_order,
    labels = niche_annotation
  ) +
  labs(
    x = "Niche composition within each cluster",
    y = NULL,
    fill = NULL
  ) +
  theme_classic() +
  theme(
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.text = element_text(color = "black"),
    strip.text = element_blank(),
    strip.background = element_rect(fill = "transparent", color = NA),
    legend.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid = element_blank(),
    panel.border = element_rect(fill = "transparent", color = "black")
  )

ggsave(
  plot = niche_proportion_within_cluster_barplot,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_composition_within_cluster_barplot.pdf"
  ),
  width = 6,
  height = 7,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)


## Plot CAF subcluster composition within each niche --------------------------

caf_subcluster_niche_plot_table <- caf_subcluster_niche_table %>%
  dplyr::filter(!is.na(.data$caf_subcluster)) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = rev(niche_order)),
    caf_subcluster = factor(
      .data$caf_subcluster,
      levels = rev(caf_subcluster_display_order)
    )
  )

caf_subcluster_composition_within_niche_barplot <- ggplot(
  caf_subcluster_niche_plot_table,
  aes(
    y = .data$niche,
    x = .data$n_cell,
    fill = .data$caf_subcluster
  )
) +
  geom_col(
    position = "fill",
    color = "gray25",
    linewidth = 0.25,
    width = 0.95
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0)),
    labels = scales::percent_format(accuracy = 1)
  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0, 0)),
    labels = niche_annotation
  ) +
  scale_fill_manual(
    values = caf_subcluster_colors_label_named,
    breaks = caf_subcluster_display_order
  ) +
  labs(
    x = "CAF subcluster composition within each niche",
    y = NULL,
    fill = NULL
  ) +
  theme_classic() +
  theme(
    aspect.ratio = 0.89,  #  0.795,
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    axis.ticks.y = element_blank(),
    legend.text = element_text(color = "black"),
    axis.line = element_blank(),
    legend.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid = element_blank(),
    panel.border = element_rect(fill = NA, color = "black")
  )

ggsave(
  plot = caf_subcluster_composition_within_niche_barplot,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_caf_subcluster_composition_barplot.pdf"
  ),
  width = 5.0,
  height = 3.0,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)


## Plot CAF subcluster UMAP faceted by spatial niche --------------------------

caf_umap_table <- caf_subcluster_metadata_table %>%
  dplyr::mutate(
    cell_id = as.character(.data$cell_id),
    xenium_sample_id = as.character(.data$xenium_sample_id),
    tx_id = as.character(.data$tx_id),
    local_cell_id = stringr::str_remove(
      .data$cell_id,
      paste0("^", .data$xenium_sample_id, "_")
    ),
    full_id = paste0(
      stringr::str_remove(.data$tx_id, "_"),
      "_",
      .data$local_cell_id
    ),
    caf_subcluster = factor(
      .data$caf_subcluster,
      levels = rev(caf_subcluster_display_order)
    )
  ) %>%
  dplyr::select(
    full_id,
    caf_subcluster,
    caf_umap_1,
    caf_umap_2
  )

caf_umap_niche_table <- spatial_niche_metadata_table %>%
  dplyr::filter(!is.na(.data$caf_subcluster)) %>%
  dplyr::select(
    full_id,
    niche
  ) %>%
  dplyr::inner_join(
    caf_umap_table,
    by = "full_id"
  ) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = niche_order)
  )

caf_subcluster_umap_by_niche_plot <- ggplot(
  caf_umap_niche_table,
  aes(x = .data$caf_umap_1, y = .data$caf_umap_2)
) +
  ggrastr::rasterise(
    geom_point(
      aes(color = .data$caf_subcluster),
      size = 0.1
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  facet_wrap(
    . ~ niche,
    ncol = 4,
    labeller = labeller(niche = niche_annotation)
  ) +
  scale_color_manual(
    values = caf_subcluster_colors_label_named,
    breaks = rev(caf_subcluster_display_order)
  ) +
  guides(
    color = guide_legend(override.aes = list(size = 4))
  ) +
  labs(
    x = "UMAP 1",
    y = "UMAP 2",
    color = NULL
  ) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    axis.title = element_text(color = "black"),
    legend.text = element_text(color = "black"),
    strip.text = element_text(color = "black"),
    legend.background = element_rect(fill = "transparent", color = NA),
    strip.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.border = element_rect(fill = NA, color = "black"),
    panel.grid = element_blank()
  )

ggsave(
  plot = caf_subcluster_umap_by_niche_plot,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_caf_subcluster_umap_by_niche.pdf"
  ),
  width = 11,
  height = 11,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)


## Save point-only CAF UMAP panels for each spatial niche --------------------

# Use the common coordinate range from the faceted plot so that every PNG has
# the same UMAP position and scale as its corresponding facet panel.
caf_umap_x_limits <- range(
  caf_umap_niche_table$caf_umap_1,
  na.rm = TRUE
)

caf_umap_y_limits <- range(
  caf_umap_niche_table$caf_umap_2,
  na.rm = TRUE
)

caf_umap_panel_aspect_ratio <-
  diff(caf_umap_y_limits) / diff(caf_umap_x_limits)

# Approximate physical width of one panel in the 11 x 11 inch faceted PDF.
caf_umap_by_niche_panel_width <- 2.36

for (target_niche in niche_order) {
  target_niche_annotation <- unname(niche_annotation[[target_niche]])

  target_niche_file_label <- target_niche_annotation %>%
    stringr::str_to_lower() %>%
    stringr::str_replace_all("[^a-z0-9]+", "_") %>%
    stringr::str_remove("_$")

  target_niche_plot <- caf_umap_niche_table %>%
    dplyr::filter(as.character(.data$niche) == target_niche) %>%
    ggplot(
      aes(x = .data$caf_umap_1, y = .data$caf_umap_2)
    ) +
    ggrastr::rasterise(
      geom_point(
        aes(color = .data$caf_subcluster),
        size = 0.1
      ),
      dpi = figure_dpi,
      dev = "ragg"
    ) +
    scale_x_continuous(limits = caf_umap_x_limits) +
    scale_y_continuous(limits = caf_umap_y_limits) +
    scale_color_manual(
      values = caf_subcluster_colors_label_named,
      breaks = rev(caf_subcluster_display_order)
    ) +
    coord_fixed(ratio = 1) +
    guides(color = "none") +
    theme_void() +
    theme(
      plot.margin = margin(0, 0, 0, 0, unit = "pt"),
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA)
    )

  ggsave(
    plot = target_niche_plot,
    filename = file.path(
      niche_figure_dir,
      paste0(
        "spatial_niche_caf_subcluster_umap_",
        target_niche_file_label,
        "_only_points.png"
      )
    ),
    width = caf_umap_by_niche_panel_width,
    height = caf_umap_by_niche_panel_width * caf_umap_panel_aspect_ratio,
    units = "in",
    bg = figure_bg,
    dpi = figure_dpi
  )
}


message(
  "Saved spatial niche analysis figures to: ",
  niche_figure_dir
)
