# Spatial niche maps on Xenium coordinates
#
# This script generates sample-wise spatial maps of k-means-defined spatial
# niches using the summary table generated by:
#   04_03_niche_summarize_spatial_niche_composition.R
#
# Spatial coordinates are retrieved from:
#   xenium_initial_clustering_metadata.csv


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define input and output directories ---------------------------------------

niche_table_dir <- file.path(xenium_table_dir, "niche_analysis")

niche_spatial_map_dir <- file.path(
  niche_analysis_figure_dir,
  "08_04_02_niche_spatial_maps"
)

fs::dir_create(niche_spatial_map_dir)


## Define niche annotations and display order --------------------------------

niche_order <- paste0("niche_", c(2, 3, 8, 9, 5, 6, 1, 4, 7, 10))

niche_annotation <- c(
  "niche_1" = "N7.Plasma cell niche",
  "niche_2" = "N1.Normal acinar niche",
  "niche_3" = "N2.Atrophic acinar niche",
  "niche_4" = "N8.Lymphoid niche",
  "niche_5" = "N5.Islet niche",
  "niche_6" = "N6.Vascular niche",
  "niche_7" = "N9.Lymphoid–myeloid niche",
  "niche_8" = "N3.Normal–PanIN niche",
  "niche_9" = "N4.Cancer niche",
  "niche_10" = "N10.Neuronal niche"
)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}

prepare_coordinate_table <- function(metadata_table) {
  metadata_table %>%
    dplyr::mutate(
      cell_id = as.character(.data$cell_id),
      xenium_sample_id = as.character(.data$xenium_sample_id),
      tx_id = as.character(.data$tx_id),
      local_cell_id = stringr::str_remove(
        .data$cell_id,
        paste0("^", .data$xenium_sample_id, "_")
      ),
      full_id = paste0(
        stringr::str_remove(.data$tx_id, "_"),
        "_",
        .data$local_cell_id
      ),
      x = as.numeric(.data$x),
      y = as.numeric(.data$y)
    ) %>%
    dplyr::select(
      full_id,
      x,
      y
    ) %>%
    dplyr::distinct()
}

prepare_sample_coordinates_for_plot <- function(sample_table) {
  x_range <- range(sample_table$x, na.rm = TRUE)
  y_range <- range(sample_table$y, na.rm = TRUE)
  
  x_length <- diff(x_range)
  y_length <- diff(y_range)
  
  if (x_length > y_length) {
    sample_table <- sample_table %>%
      dplyr::mutate(
        plot_x = .data$y,
        plot_y = x_range[2] - .data$x
      )
  } else {
    sample_table <- sample_table %>%
      dplyr::mutate(
        plot_x = .data$x,
        plot_y = .data$y
      )
  }
  
  sample_table
}


## Read input tables ---------------------------------------------------------

spatial_niche_metadata_table <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_cell_metadata.csv"),
  "Spatial niche cell metadata table"
)

initial_metadata_table <- read_required_csv(
  initial_metadata_file,
  "Initial clustering metadata table"
)

check_required_columns(
  spatial_niche_metadata_table,
  c(
    "full_id",
    "tx_id",
    "tx_number",
    "xenium_sample_id",
    "niche",
    "caf_subcluster"
  ),
  "spatial niche cell metadata table"
)

check_required_columns(
  initial_metadata_table,
  c(
    "cell_id",
    "xenium_sample_id",
    "tx_id",
    "x",
    "y"
  ),
  "initial clustering metadata table"
)


## Combine niche labels with spatial coordinates -----------------------------

initial_coordinate_table <- prepare_coordinate_table(initial_metadata_table)

if (any(duplicated(initial_coordinate_table$full_id))) {
  stop(
    "Duplicated full_id values were detected in initial coordinate table.",
    call. = FALSE
  )
}

spatial_niche_plot_table <- spatial_niche_metadata_table %>%
  dplyr::left_join(
    initial_coordinate_table,
    by = "full_id"
  ) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = niche_order)
  )

if (any(is.na(spatial_niche_plot_table$x)) || any(is.na(spatial_niche_plot_table$y))) {
  stop("Some spatial niche cells do not have spatial coordinates.", call. = FALSE)
}

if (any(is.na(spatial_niche_plot_table$niche))) {
  stop("Some cells have niche IDs not included in niche_order.", call. = FALSE)
}


## Plot sample-wise spatial niche maps for figure ----------------------------

plot_spatial_niche_map_for_figure <- function(sample_plot_table, xenium_sample_id) {
  x_range <- range(sample_plot_table$plot_x, na.rm = TRUE)
  y_range <- range(sample_plot_table$plot_y, na.rm = TRUE)
  
  x_breaks <- seq(
    from = ceiling(x_range[1] / 1000) * 1000,
    to = floor(x_range[2] / 1000) * 1000,
    by = 1000
  )
  
  y_breaks <- seq(
    from = ceiling(y_range[1] / 1000) * 1000,
    to = floor(y_range[2] / 1000) * 1000,
    by = 1000
  )
  
  scale_bar_right_x <- stats::quantile(x_range, 0.93, names = FALSE)
  scale_bar_y <- stats::quantile(y_range, 0.97, names = FALSE)
  
  spatial_niche_map <- ggplot(
    sample_plot_table,
    aes(
      x = .data$plot_x,
      y = .data$plot_y,
      color = .data$niche
    )
  ) +
    geom_point(size = 1) +
    geom_point(
      data = dplyr::filter(sample_plot_table, .data$caf_subcluster == "CAF-8"),
      aes(
        x = .data$plot_x,
        y = .data$plot_y
      ),
      inherit.aes = FALSE,
      shape = 21,
      color = "black",
      fill = NA,
      stroke = 2,
      size = 1
    ) +
    annotate(
      geom = "segment",
      x = scale_bar_right_x - 1000,
      xend = scale_bar_right_x,
      y = scale_bar_y,
      yend = scale_bar_y,
      color = "black",
      linewidth = 2
    ) +
    scale_x_continuous(
      expand = expansion(mult = c(0, 0)),
      breaks = x_breaks,
      limits = x_range
    ) +
    scale_y_reverse(
      expand = expansion(mult = c(0, 0)),
      breaks = y_breaks,
      limits = rev(y_range)
    ) +
    scale_color_manual(
      values = niche_colors,
      breaks = niche_order,
      labels = niche_annotation
    ) +
    guides(
      color = guide_legend(override.aes = list(size = 3))
    ) +
    labs(
      x = NULL,
      y = NULL,
      color = NULL
    ) +
    coord_fixed(ratio = 1) +
    theme_classic() +
    theme(
      legend.position = "none",
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line = element_blank(),
      legend.key = element_blank(),
      plot.background = element_rect(fill = "transparent", color = NA),
      legend.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      panel.border = element_rect(fill = NA, color = "black"),
      panel.grid = element_blank()
    )
  
  ggsave(
    plot = spatial_niche_map,
    filename = file.path(
      niche_spatial_map_dir,
      paste0(
        "spatial_niche_map_with_caf8_highlight_",
        stringr::str_to_lower(xenium_sample_id),
        ".png"
      )
    ),
    width = diff(x_range) / 800,
    height = diff(y_range) / 800,
    dpi = 500,
    bg = "transparent"
  )
  
  invisible(spatial_niche_map)
}

tx_numbers_to_plot <- as.character(tx_number_merge_order)

for (tx_number_i in tx_numbers_to_plot) {
  sample_plot_table <- spatial_niche_plot_table %>%
    dplyr::filter(.data$tx_number == tx_number_i) %>%
    prepare_sample_coordinates_for_plot()
  
  if (nrow(sample_plot_table) == 0) {
    stop("No cells found for TX number: ", tx_number_i, call. = FALSE)
  }
  
  xenium_sample_id_i <- unique(sample_plot_table$xenium_sample_id)
  
  if (length(xenium_sample_id_i) != 1) {
    stop(
      "Expected one Xenium sample ID for TX number ",
      tx_number_i,
      ", but found: ",
      paste(xenium_sample_id_i, collapse = ", "),
      call. = FALSE
    )
  }
  
  plot_spatial_niche_map_for_figure(
    sample_plot_table = sample_plot_table,
    xenium_sample_id = xenium_sample_id_i
  )
}

message(
  "Saved spatial niche maps to: ",
  niche_spatial_map_dir
)