# Prepare supplementary tables for hypoxia mapping
#
# This script prepares supplementary tables from the hypoxia mapping outputs
# generated by:
#   03_02_hypoxia_mapping_calculate_grid_non_caf_hypoxia_scores.R
#   03_03_hypoxia_mapping_assign_local_non_caf_hypoxia_scores_to_cafs.R
#
# The tables summarize grid-level non-CAF-derived Winter hypoxia scores and
# CAF-assigned local non-CAF-derived Winter hypoxia scores.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))


## Define input and output directories ---------------------------------------

hypoxia_mapping_table_dir <- file.path(
  xenium_table_dir,
  "hypoxia_mapping"
)

hypoxia_mapping_supplementary_table_dir <- file.path(
  hypoxia_mapping_table_dir,
  "supplementary_tables"
)

fs::dir_create(hypoxia_mapping_supplementary_table_dir)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}

summarize_score_vector <- function(score) {
  valid_score <- score[!is.na(score)]
  
  if (length(valid_score) == 0) {
    return(
      tibble::tibble(
        n_cells = length(score),
        n_cells_with_score = 0L,
        n_cells_without_score = length(score),
        mean_score = NA_real_,
        median_score = NA_real_,
        sd_score = NA_real_,
        q1_score = NA_real_,
        q3_score = NA_real_,
        min_score = NA_real_,
        max_score = NA_real_
      )
    )
  }
  
  tibble::tibble(
    n_cells = length(score),
    n_cells_with_score = length(valid_score),
    n_cells_without_score = sum(is.na(score)),
    mean_score = mean(valid_score),
    median_score = stats::median(valid_score),
    sd_score = stats::sd(valid_score),
    q1_score = stats::quantile(
      valid_score,
      0.25,
      names = FALSE
    ),
    q3_score = stats::quantile(
      valid_score,
      0.75,
      names = FALSE
    ),
    min_score = min(valid_score),
    max_score = max(valid_score)
  )
}


## Read input tables ---------------------------------------------------------

grid_nonCAF_hypoxia_table <- read_required_csv(
  file.path(
    hypoxia_mapping_table_dir,
    "grid_non_caf_winter_hypoxia_scores_all_samples.csv"
  ),
  "Grid-level non-CAF-derived Winter hypoxia score table"
)

caf_local_nonCAF_hypoxia_table <- read_required_csv(
  file.path(
    hypoxia_mapping_table_dir,
    "caf_assigned_local_non_caf_winter_hypoxia_scores.csv"
  ),
  "CAF-assigned local non-CAF-derived Winter hypoxia score table"
)

check_required_columns(
  grid_nonCAF_hypoxia_table,
  c(
    "sample",
    "xenium_sample_id",
    "tx_id",
    "Grid_id",
    "GridX_edge",
    "GridY_edge",
    "GridX_center_um",
    "GridY_center_um",
    "grid_length_um",
    "n_nonCAF_cells",
    "min_non_caf_cells_per_grid",
    "mean_Winter_z_celltype"
  ),
  "grid-level non-CAF-derived Winter hypoxia score table"
)

check_required_columns(
  caf_local_nonCAF_hypoxia_table,
  c(
    "sample",
    "xenium_sample_id",
    "tx_id",
    "full_id",
    "cell_id",
    "SubClust",
    "Grid_id",
    "n_nonCAF_cells",
    "local_nonCAF_Winter_z_celltype"
  ),
  "CAF-assigned local non-CAF-derived Winter hypoxia score table"
)


## Prepare grid-level supplementary table -----------------------------------

grid_nonCAF_hypoxia_supplementary_table <- grid_nonCAF_hypoxia_table %>%
  dplyr::mutate(
    xenium_sample_id = factor(
      .data$xenium_sample_id,
      levels = xenium_sample_id_display_order
    )
  ) %>%
  dplyr::arrange(
    .data$xenium_sample_id,
    .data$GridX_edge,
    .data$GridY_edge
  ) %>%
  dplyr::transmute(
    xenium_sample_id = as.character(.data$xenium_sample_id),
    tx_id,
    grid_id = .data$Grid_id,
    grid_x_edge = .data$GridX_edge,
    grid_y_edge = .data$GridY_edge,
    grid_x_center_um = .data$GridX_center_um,
    grid_y_center_um = .data$GridY_center_um,
    grid_length_um,
    n_nonCAF_cells,
    min_non_caf_cells_per_grid,
    mean_nonCAF_Winter_z_celltype = .data$mean_Winter_z_celltype
  )

readr::write_csv(
  grid_nonCAF_hypoxia_supplementary_table,
  file = file.path(
    hypoxia_mapping_supplementary_table_dir,
    "hypoxia_mapping_grid_non_caf_winter_hypoxia_scores.csv"
  )
)


## Prepare CAF-assigned supplementary table ---------------------------------

caf_local_nonCAF_hypoxia_supplementary_table <- caf_local_nonCAF_hypoxia_table %>%
  dplyr::mutate(
    xenium_sample_id = factor(
      .data$xenium_sample_id,
      levels = xenium_sample_id_display_order
    ),
    caf_subcluster = factor(
      .data$SubClust,
      levels = caf_subcluster_display_order
    )
  ) %>%
  dplyr::arrange(
    .data$xenium_sample_id,
    .data$caf_subcluster,
    .data$full_id
  ) %>%
  dplyr::transmute(
    xenium_sample_id = as.character(.data$xenium_sample_id),
    tx_id,
    full_id,
    cell_id,
    caf_subcluster = as.character(.data$caf_subcluster),
    grid_id = .data$Grid_id,
    n_nonCAF_cells_in_grid = .data$n_nonCAF_cells,
    local_nonCAF_Winter_z_celltype = .data$local_nonCAF_Winter_z_celltype
  )

readr::write_csv(
  caf_local_nonCAF_hypoxia_supplementary_table,
  file = file.path(
    hypoxia_mapping_supplementary_table_dir,
    "hypoxia_mapping_caf_assigned_local_non_caf_winter_hypoxia_scores.csv"
  )
)


## Summarize CAF-assigned hypoxia scores by CAF subcluster -------------------

caf_subcluster_hypoxia_summary_table <- caf_local_nonCAF_hypoxia_supplementary_table %>%
  dplyr::mutate(
    xenium_sample_id = factor(
      .data$xenium_sample_id,
      levels = xenium_sample_id_display_order
    ),
    caf_subcluster = factor(
      .data$caf_subcluster,
      levels = caf_subcluster_display_order
    )
  ) %>%
  dplyr::group_by(
    .data$xenium_sample_id,
    .data$tx_id,
    .data$caf_subcluster
  ) %>%
  dplyr::summarise(
    summarize_score_vector(.data$local_nonCAF_Winter_z_celltype),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    percent_cells_with_score = 100 * .data$n_cells_with_score / .data$n_cells
  ) %>%
  dplyr::arrange(
    .data$xenium_sample_id,
    .data$caf_subcluster
  ) %>%
  dplyr::mutate(
    xenium_sample_id = as.character(.data$xenium_sample_id),
    caf_subcluster = as.character(.data$caf_subcluster)
  )

readr::write_csv(
  caf_subcluster_hypoxia_summary_table,
  file = file.path(
    hypoxia_mapping_supplementary_table_dir,
    "hypoxia_mapping_caf_subcluster_local_non_caf_winter_hypoxia_score_summary.csv"
  )
)


## Summarize grid-level hypoxia scores by sample -----------------------------

grid_nonCAF_hypoxia_summary_table <- grid_nonCAF_hypoxia_supplementary_table %>%
  dplyr::mutate(
    xenium_sample_id = factor(
      .data$xenium_sample_id,
      levels = xenium_sample_id_display_order
    ),
    valid_hypoxia_score = !is.na(.data$mean_nonCAF_Winter_z_celltype)
  ) %>%
  dplyr::group_by(
    .data$xenium_sample_id,
    .data$tx_id
  ) %>%
  dplyr::summarise(
    n_grids = dplyr::n(),
    n_grids_with_nonCAF_cells = sum(.data$n_nonCAF_cells > 0),
    n_grids_with_valid_hypoxia_score = sum(.data$valid_hypoxia_score),
    min_non_caf_cells_per_grid = dplyr::first(.data$min_non_caf_cells_per_grid),
    mean_score = mean(.data$mean_nonCAF_Winter_z_celltype, na.rm = TRUE),
    median_score = stats::median(.data$mean_nonCAF_Winter_z_celltype, na.rm = TRUE),
    sd_score = stats::sd(.data$mean_nonCAF_Winter_z_celltype, na.rm = TRUE),
    q1_score = stats::quantile(
      .data$mean_nonCAF_Winter_z_celltype,
      0.25,
      na.rm = TRUE,
      names = FALSE
    ),
    q3_score = stats::quantile(
      .data$mean_nonCAF_Winter_z_celltype,
      0.75,
      na.rm = TRUE,
      names = FALSE
    ),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    percent_grids_with_valid_hypoxia_score =
      100 * .data$n_grids_with_valid_hypoxia_score / .data$n_grids,
    xenium_sample_id = as.character(.data$xenium_sample_id)
  ) %>%
  dplyr::arrange(.data$xenium_sample_id)

readr::write_csv(
  grid_nonCAF_hypoxia_summary_table,
  file = file.path(
    hypoxia_mapping_supplementary_table_dir,
    "hypoxia_mapping_grid_non_caf_winter_hypoxia_score_summary.csv"
  )
)

message(
  "Saved hypoxia mapping supplementary tables to: ",
  hypoxia_mapping_supplementary_table_dir
)
