# Assign local non-CAF-derived Winter hypoxia scores to CAFs
#
# This script assigns grid-level non-CAF-derived Winter hypoxia scores to CAFs.
# It reads cell-level Winter hypoxia ssGSEA score tables generated by:
#   03_01_hypoxia_mapping_prepare_hypoxia_ssgsea_scores.R
# and grid-level non-CAF-derived Winter hypoxia score tables generated by:
#   03_02_hypoxia_mapping_calculate_grid_non_caf_hypoxia_scores.R
#
# Outputs from this script are used to compare local hypoxia scores across CAF
# subclusters.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))


## Define input and output directory -----------------------------------------

hypoxia_mapping_table_dir <- file.path(
  xenium_table_dir,
  "hypoxia_mapping"
)

fs::dir_create(hypoxia_mapping_table_dir)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}

add_grid_information <- function(cell_table, grid_length_um) {
  cell_table %>%
    dplyr::mutate(
      X = as.numeric(.data$X),
      Y = as.numeric(.data$Y),
      GridX_edge = floor(.data$X / grid_length_um),
      GridY_edge = floor(.data$Y / grid_length_um),
      Grid_id = paste(.data$GridX_edge, .data$GridY_edge, sep = "_")
    )
}


## Assign grid-level hypoxia scores to CAFs ----------------------------------

local_nonCAF_hypoxia_score_table <- purrr::map_dfr(
  tx_number_merge_order,
  function(tx_number_i) {
    xenium_sample_id_i <- xenium_sample_id_by_tx_number[[tx_number_i]]
    
    if (is.null(xenium_sample_id_i)) {
      stop(
        "No Xenium sample ID was defined for TX number: ",
        tx_number_i,
        call. = FALSE
      )
    }
    
    message(
      "Assigning local non-CAF hypoxia scores to CAFs for ",
      xenium_sample_id_i
    )
    
    cell_hypoxia_file <- file.path(
      hypoxia_mapping_table_dir,
      paste0(
        "winter_hypoxia_ssgsea_scores_",
        stringr::str_to_lower(xenium_sample_id_i),
        ".csv"
      )
    )
    
    grid_hypoxia_file <- file.path(
      hypoxia_mapping_table_dir,
      paste0(
        "grid_non_caf_winter_hypoxia_scores_",
        stringr::str_to_lower(xenium_sample_id_i),
        ".csv"
      )
    )
    
    cell_hypoxia_table <- read_required_csv(
      cell_hypoxia_file,
      paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
    )
    
    grid_hypoxia_table <- read_required_csv(
      grid_hypoxia_file,
      paste0("Grid-level non-CAF hypoxia score table for ", xenium_sample_id_i)
    )
    
    check_required_columns(
      cell_hypoxia_table,
      c(
        "sample",
        "xenium_sample_id",
        "tx_id",
        "full_id",
        "cell_id",
        "Annot",
        "SubClust",
        "X",
        "Y"
      ),
      paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
    )
    
    check_required_columns(
      grid_hypoxia_table,
      c(
        "Grid_id",
        "n_nonCAF_cells",
        "mean_Winter_z_celltype"
      ),
      paste0("Grid-level non-CAF hypoxia score table for ", xenium_sample_id_i)
    )
    
    cell_hypoxia_grid_table <- cell_hypoxia_table %>%
      add_grid_information(grid_length_um = grid_length_um)
    
    grid_score_table <- grid_hypoxia_table %>%
      dplyr::select(
        Grid_id,
        n_nonCAF_cells,
        local_nonCAF_Winter_z_celltype = mean_Winter_z_celltype
      )
    
    caf_local_hypoxia_table <- cell_hypoxia_grid_table %>%
      dplyr::filter(.data$Annot == "CAF") %>%
      dplyr::left_join(
        grid_score_table,
        by = "Grid_id"
      ) %>%
      dplyr::mutate(
        sample = as.character(.data$sample),
        xenium_sample_id = as.character(.data$xenium_sample_id),
        tx_id = as.character(.data$tx_id),
        full_id = as.character(.data$full_id),
        cell_id = as.character(.data$cell_id),
        Grid_id = as.character(.data$Grid_id),
        SubClust = factor(
          .data$SubClust,
          levels = paste0("CAF-", caf_subcluster_order)
        )
      ) %>%
      dplyr::select(
        sample,
        xenium_sample_id,
        tx_id,
        full_id,
        cell_id,
        SubClust,
        Grid_id,
        n_nonCAF_cells,
        local_nonCAF_Winter_z_celltype
      )
    
    if (nrow(caf_local_hypoxia_table) == 0) {
      stop(
        "No CAF cells were found for ",
        xenium_sample_id_i,
        call. = FALSE
      )
    }
    
    caf_local_hypoxia_table
  }
)


## Save output ---------------------------------------------------------------

readr::write_csv(
  local_nonCAF_hypoxia_score_table,
  file = file.path(
    hypoxia_mapping_table_dir,
    "caf_assigned_local_non_caf_winter_hypoxia_scores.csv"
  )
)

message(
  "Saved CAF-assigned local non-CAF-derived Winter hypoxia score table to: ",
  hypoxia_mapping_table_dir
)
