# Calculate grid-level non-CAF-derived Winter hypoxia scores
#
# This script calculates grid-level hypoxia scores using only non-CAF cells.
# It reads cell-level Winter hypoxia ssGSEA score tables generated by:
#   03_01_hypoxia_mapping_prepare_hypoxia_ssGSEA_scores.R
# assigns cells to spatial grids, and calculates the mean cell type-normalized
# Winter hypoxia score for each grid. Grids containing fewer than the specified
# minimum number of non-CAF cells are assigned NA.
#
# Outputs from this script are used for non-CAF-derived hypoxia mapping and
# for assigning local non-CAF-derived hypoxia scores to CAFs.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directory -----------------------------------------

hypoxia_mapping_table_dir <- file.path(
  xenium_table_dir,
  "hypoxia_mapping"
)

fs::dir_create(hypoxia_mapping_table_dir)


## Define parameters ---------------------------------------------------------

min_non_caf_cells_per_grid <- 30


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}

add_grid_information <- function(cell_table, grid_length_um) {
  cell_table %>%
    dplyr::mutate(
      X = as.numeric(.data$X),
      Y = as.numeric(.data$Y),
      GridX_edge = floor(.data$X / grid_length_um),
      GridY_edge = floor(.data$Y / grid_length_um),
      Grid_id = paste(.data$GridX_edge, .data$GridY_edge, sep = "_"),
      GridX_center_um = (.data$GridX_edge + 0.5) * grid_length_um,
      GridY_center_um = (.data$GridY_edge + 0.5) * grid_length_um
    )
}

make_complete_grid_table <- function(
    grid_summary_table, 
    nonCAF_grid_table, 
    grid_length_um
) {
  grid_x_range <- range(nonCAF_grid_table$GridX_edge, na.rm = TRUE)
  grid_y_range <- range(nonCAF_grid_table$GridY_edge, na.rm = TRUE)
  
  tidyr::expand_grid(
    GridX_edge = seq(grid_x_range[1], grid_x_range[2]),
    GridY_edge = seq(grid_y_range[1], grid_y_range[2])
  ) %>%
    dplyr::mutate(
      Grid_id = paste(.data$GridX_edge, .data$GridY_edge, sep = "_"),
      GridX_center_um = (.data$GridX_edge + 0.5) * grid_length_um,
      GridY_center_um = (.data$GridY_edge + 0.5) * grid_length_um
    ) %>%
    dplyr::left_join(
      grid_summary_table,
      by = c(
        "Grid_id",
        "GridX_edge",
        "GridY_edge",
        "GridX_center_um",
        "GridY_center_um"
      )
    ) %>%
    dplyr::mutate(
      n_nonCAF_cells = dplyr::if_else(
        is.na(.data$n_nonCAF_cells),
        0L,
        as.integer(.data$n_nonCAF_cells)
      )
    )
}


## Calculate grid-level non-CAF-derived hypoxia scores -----------------------

grid_nonCAF_hypoxia_table_all <- purrr::map_dfr(
  tx_number_merge_order,
  function(tx_number_i) {
    xenium_sample_id_i <- xenium_sample_id_by_tx_number[[tx_number_i]]
    
    if (is.null(xenium_sample_id_i)) {
      stop(
        "No Xenium sample ID was defined for TX number: ",
        tx_number_i,
        call. = FALSE
      )
    }
    
    message(
      "Calculating grid-level non-CAF hypoxia scores for ",
      xenium_sample_id_i
    )
    
    hypoxia_score_file <- file.path(
      hypoxia_mapping_table_dir,
      paste0(
        "winter_hypoxia_ssgsea_scores_",
        stringr::str_to_lower(xenium_sample_id_i),
        ".csv"
      )
    )
    
    cell_hypoxia_table <- read_required_csv(
      hypoxia_score_file,
      paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
    )
    
    check_required_columns(
      cell_hypoxia_table,
      c(
        "sample",
        "xenium_sample_id",
        "tx_id",
        "full_id",
        "cell_id",
        "Annot",
        "X",
        "Y",
        "Winter_z_celltype"
      ),
      paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
    )
    
    cell_hypoxia_grid_table <- cell_hypoxia_table %>%
      add_grid_information(grid_length_um = grid_length_um)
    
    nonCAF_grid_table <- cell_hypoxia_grid_table %>%
      dplyr::filter(.data$Annot != "CAF")
    
    if (nrow(nonCAF_grid_table) == 0) {
      stop(
        "No non-CAF cells were found for ",
        xenium_sample_id_i,
        call. = FALSE
      )
    }
    
    grid_summary_table <- nonCAF_grid_table %>%
      dplyr::group_by(
        .data$Grid_id,
        .data$GridX_edge,
        .data$GridY_edge,
        .data$GridX_center_um,
        .data$GridY_center_um
      ) %>%
      dplyr::summarise(
        n_nonCAF_cells = dplyr::n(),
        mean_Winter_z_celltype = mean(.data$Winter_z_celltype, na.rm = TRUE),
        .groups = "drop"
      ) %>%
      dplyr::mutate(
        mean_Winter_z_celltype = dplyr::if_else(
          .data$n_nonCAF_cells < min_non_caf_cells_per_grid,
          NA_real_,
          .data$mean_Winter_z_celltype
        )
      )
    
    grid_nonCAF_hypoxia_table <- make_complete_grid_table(
      grid_summary_table = grid_summary_table,
      nonCAF_grid_table = nonCAF_grid_table,
      grid_length_um = grid_length_um
    ) %>%
      dplyr::mutate(
        sample = tx_number_i,
        xenium_sample_id = xenium_sample_id_i,
        tx_id = paste0("TX5K_", tx_number_i),
        grid_length_um = .env$grid_length_um,
        min_non_caf_cells_per_grid = min_non_caf_cells_per_grid
      ) %>%
      dplyr::select(
        sample,
        xenium_sample_id,
        tx_id,
        Grid_id,
        GridX_edge,
        GridY_edge,
        GridX_center_um,
        GridY_center_um,
        grid_length_um,
        n_nonCAF_cells,
        min_non_caf_cells_per_grid,
        mean_Winter_z_celltype
      )
    
    readr::write_csv(
      grid_nonCAF_hypoxia_table,
      file = file.path(
        hypoxia_mapping_table_dir,
        paste0(
          "grid_non_caf_winter_hypoxia_scores_",
          stringr::str_to_lower(xenium_sample_id_i),
          ".csv"
        )
      )
    )
    
    grid_nonCAF_hypoxia_table
  }
)


## Save combined output ------------------------------------------------------

readr::write_csv(
  grid_nonCAF_hypoxia_table_all,
  file = file.path(
    hypoxia_mapping_table_dir,
    "grid_non_caf_winter_hypoxia_scores_all_samples.csv"
  )
)

message(
  "Saved grid-level non-CAF-derived Winter hypoxia score tables to: ",
  hypoxia_mapping_table_dir
)
