# Pseudotime state GSEA bar plot
#
# This script reproduces the bar plot of the top five positively enriched
# gene sets for each pseudotime state. Significant gene sets are colored by
# -log10(adjusted P value), whereas non-significant gene sets are shown in gray.
#
# The plotting table is generated by:
#   05_03_pseudotime_state_deg_and_gsea.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(ggh4x)
  library(grid)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))


## Define input and output directories ---------------------------------------

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

pseudotime_figure_dir <- file.path(
  xenium_figure_dir,
  "08_05_pseudotime_analysis"
)

pseudotime_state_gsea_figure_dir <- file.path(
  pseudotime_figure_dir,
  "08_05_04_pseudotime_state_gsea_barplot"
)

fs::dir_create(pseudotime_state_gsea_figure_dir)


## Define input file ---------------------------------------------------------

state_gsea_top_positive_file <- file.path(
  pseudotime_table_dir,
  "pseudotime_analysis_state_gsea_top_positive.csv"
)

if (!file.exists(state_gsea_top_positive_file)) {
  stop(
    "Required input file was not found:\n",
    state_gsea_top_positive_file,
    call. = FALSE
  )
}


## Read and validate input table --------------------------------------------

state_gsea_top_positive_table <- readr::read_csv(
  state_gsea_top_positive_file,
  show_col_types = FALSE
)

required_columns <- c(
  "state",
  "ID",
  "NES",
  "p.adjust",
  "minus_log10_adjusted_p"
)

missing_columns <- setdiff(
  required_columns,
  colnames(state_gsea_top_positive_table)
)

if (length(missing_columns) > 0) {
  stop(
    "Required columns are missing: ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

state_levels <- paste0(
  "State ",
  sort(
    unique(
      readr::parse_number(state_gsea_top_positive_table$state)
    )
  )
)

state_gsea_plot_table <- state_gsea_top_positive_table %>%
  mutate(
    state = factor(
      state,
      levels = state_levels
    )
  ) %>%
  arrange(state, desc(NES)) %>%
  mutate(
    gene_set_state_label = paste(ID, state, sep = "_"),
    gene_set_state_label = factor(
      gene_set_state_label,
      levels = rev(gene_set_state_label)
    ),
    significant_minus_log10_adjusted_p = if_else(
      p.adjust < 0.05,
      minus_log10_adjusted_p,
      NA_real_
    )
  )

if (nrow(state_gsea_plot_table) == 0) {
  stop(
    "The GSEA plotting table contains no rows.",
    call. = FALSE
  )
}

if (any(is.na(state_gsea_plot_table$state))) {
  stop(
    "Some state labels could not be matched to the expected state order.",
    call. = FALSE
  )
}


## Define figure settings ----------------------------------------------------

figure_width <- 4.5
figure_height <- 6.0
panel_width <- 0.81

## Create GSEA bar plot ------------------------------------------------------

plot_state_gsea_barplot <- ggplot(
  state_gsea_plot_table,
  aes(
    x = NES,
    y = gene_set_state_label
  )
) +
  geom_col(
    aes(fill = significant_minus_log10_adjusted_p),
    color = "gray10",
    linewidth = 0.2
  ) +
  labs(
    x = "NES",
    y = NULL,
    fill = "−log10(adjusted P value)"
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.03)),
    breaks = c(0, 1, 2)
  ) +
  scale_y_discrete(
    labels = function(x) {
      x %>%
        str_remove("_State \\d+$") %>%
        format_gene_set_label()
    }
  ) +
  scale_fill_distiller(
    palette = "Oranges",
    breaks = c(3, 5, 7),
    na.value = "gray70",
    guide = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      barwidth = unit(1.5, "in"),
      barheight = unit(0.2, "in"),
      ticks.colour = "black",
      frame.colour = "black"
    )
  ) +
  facet_grid(
    state ~ .,
    scales = "free_y",
    space = "free_y",
    switch = "y"
  ) +
  ggh4x::force_panelsizes(
    cols = grid::unit(0.814, "in")
  ) +
  theme(
    legend.position = "bottom",
    legend.justification = "center",
    legend.box.just = "center",
    axis.text.x = element_text(
      color = "black",
      size = 10
    ),
    axis.text.y = element_text(
      color = "black",
      size = 10
    ),
    axis.title = element_text(
      color = "black",
      size = 10
    ),
    legend.title = element_text(
      color = "black",
      size = 10
    ),
    legend.text = element_text(
      color = "black",
      size = 10
    ),
    plot.background = element_rect(
      fill = NA,
      color = NA
    ),
    panel.background = element_rect(
      fill = NA,
      color = NA
    ),
    legend.background = element_rect(
      fill = NA,
      color = NA
    ),
    axis.line = element_line(
      color = "black"
    ),
    strip.placement = "outside",
    strip.background = element_rect(
      fill = NA,
      color = NA
    ),
    panel.grid = element_blank()
  )


## Save figure ---------------------------------------------------------------

ggsave(
  filename = file.path(
    pseudotime_state_gsea_figure_dir,
    "pseudotime_analysis_state_gsea_barplot.pdf"
  ),
  plot = plot_state_gsea_barplot,
  device = grDevices::cairo_pdf,
  width = figure_width,
  height = figure_height,
  units = "in",
  bg = "transparent"
)
