# Pseudotime state DEG jitter plot
#
# This script reproduces the state-wise DEG jitter plot from the original
# pseudotime analysis code. Only genes with positive average log2 fold change
# are shown. Genes with avg_log2FC > 1 and adjusted P < 0.05 are highlighted.
#
# The DEG table is generated by:
#   05_03_pseudotime_state_deg_and_gsea.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggrastr)
  library(ragg)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directories ---------------------------------------

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

pseudotime_figure_dir <- file.path(
  xenium_figure_dir,
  "08_05_pseudotime_analysis"
)

pseudotime_state_deg_jitter_figure_dir <- file.path(
  pseudotime_figure_dir,
  "08_05_03_pseudotime_state_deg_jitter_plot"
)

pseudotime_state_deg_jitter_panel_png_dir <- file.path(
  pseudotime_state_deg_jitter_figure_dir,
  "panel_png"
)

fs::dir_create(pseudotime_state_deg_jitter_figure_dir)
fs::dir_create(pseudotime_state_deg_jitter_panel_png_dir)


## Define input file ---------------------------------------------------------

state_deg_file <- file.path(
  pseudotime_table_dir,
  "pseudotime_analysis_state_deg.csv"
)

if (!file.exists(state_deg_file)) {
  stop(
    "Required input file was not found:\n",
    state_deg_file,
    call. = FALSE
  )
}


## Read and validate input table --------------------------------------------

state_deg_table <- readr::read_csv(
  state_deg_file,
  show_col_types = FALSE
)

required_columns <- c(
  "state",
  "gene",
  "avg_log2FC",
  "p_val_adj"
)

missing_columns <- setdiff(
  required_columns,
  colnames(state_deg_table)
)

if (length(missing_columns) > 0) {
  stop(
    "Required columns are missing: ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

state_levels <- paste0(
  "State ",
  sort(
    unique(
      readr::parse_number(state_deg_table$state)
    )
  )
)

state_deg_plot_table <- state_deg_table %>%
  filter(avg_log2FC > 0) %>%
  mutate(
    state = factor(
      state,
      levels = state_levels
    ),
    point_group = if_else(
      avg_log2FC > 1 & p_val_adj < 0.05,
      "Colored",
      "Gray"
    ),
    point_group = factor(
      point_group,
      levels = c("Gray", "Colored")
    )
  ) %>%
  group_by(point_group) %>%
  arrange(avg_log2FC, .by_group = TRUE) %>%
  ungroup()

if (nrow(state_deg_plot_table) == 0) {
  stop(
    "No genes with positive avg_log2FC were found.",
    call. = FALSE
  )
}

if (any(is.na(state_deg_plot_table$state))) {
  stop(
    "Some state labels could not be matched to the expected state order.",
    call. = FALSE
  )
}


## Define figure settings ----------------------------------------------------

figure_width <- 5
figure_height <- 4

panel_width <- 4.50
panel_height <- 3.62

jitter_position <- position_jitter(
  width = 0.4,
  height = 0,
  seed = pseudotime_random_seed
)


## Define common themes ------------------------------------------------------

common_theme <- theme(
  legend.position = "none",
  axis.text.x = element_text(
    color = "black",
    size = 10
  ),
  axis.text.y = element_text(
    color = "black",
    size = 10
  ),
  axis.title = element_text(
    color = "black",
    size = 10
  ),
  legend.title = element_text(
    color = "black",
    size = 10
  ),
  legend.text = element_text(
    color = "black",
    size = 10
  ),
  plot.background = element_rect(
    fill = NA,
    color = NA
  ),
  panel.background = element_rect(
    fill = NA,
    color = NA
  ),
  legend.background = element_rect(
    fill = NA,
    color = NA
  ),
  panel.border = element_rect(
    fill = NA,
    color = "black"
  ),
  strip.placement = "outside",
  strip.background = element_rect(
    fill = NA,
    color = NA
  ),
  panel.grid = element_blank()
)

panel_only_theme <- theme_void() +
  theme(
    plot.margin = margin(0, 0, 0, 0),
    plot.background = element_rect(
      fill = NA,
      color = NA
    ),
    panel.background = element_rect(
      fill = NA,
      color = NA
    )
  )


## Create PDF plot -----------------------------------------------------------

plot_state_deg_jitter_pdf <- ggplot(
  state_deg_plot_table,
  aes(
    x = state,
    y = avg_log2FC
  )
) +
  ggrastr::rasterise(
    geom_point(
      aes(
        color = point_group,
        fill = if_else(
          point_group == "Colored",
          avg_log2FC,
          NA_real_
        ),
        shape = point_group
      ),
      position = jitter_position,
      size = 3
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  labs(
    x = NULL,
    y = "log2 fold change",
    fill = "log 2 fold change"
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.03)),
    breaks = c(1, 4, 8)
  ) +
  scale_shape_manual(
    values = c(
      "Colored" = 21,
      "Gray" = 19
    ),
    guide = "none"
  ) +
  scale_color_manual(
    values = c(
      "Colored" = "black",
      "Gray" = "gray80"
    ),
    guide = "none"
  ) +
  scale_fill_distiller(
    palette = "Oranges",
    na.value = "gray80",
    guide = guide_colorbar(
      title.hjust = 0.5,
      ticks.colour = "black",
      frame.colour = "black"
    )
  ) +
  theme(aspect.ratio = 0.804) +
  common_theme


## Create panel-only PNG plot -----------------------------------------------

plot_state_deg_jitter_panel_png <- ggplot(
  state_deg_plot_table,
  aes(
    x = state,
    y = avg_log2FC
  )
) +
  geom_point(
    aes(
      color = point_group,
      fill = if_else(
        point_group == "Colored",
        avg_log2FC,
        NA_real_
      ),
      shape = point_group
    ),
    position = jitter_position,
    size = 3
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.03)),
    breaks = c(1, 4, 8)
  ) +
  scale_shape_manual(
    values = c(
      "Colored" = 21,
      "Gray" = 19
    ),
    guide = "none"
  ) +
  scale_color_manual(
    values = c(
      "Colored" = "black",
      "Gray" = "gray80"
    ),
    guide = "none"
  ) +
  scale_fill_distiller(
    palette = "Oranges",
    na.value = "gray80",
    guide = "none"
  ) +
  panel_only_theme


## Save figures --------------------------------------------------------------

ggsave(
  plot = plot_state_deg_jitter_pdf,
  filename = file.path(
    pseudotime_state_deg_jitter_figure_dir,
    "pseudotime_state_deg_jitter_plot.pdf"
  ),
  width = figure_width,
  height = figure_height,
  units = "in",
  bg = "transparent",
  device = grDevices::cairo_pdf
)

ggsave(
  plot = plot_state_deg_jitter_panel_png,
  filename = file.path(
    pseudotime_state_deg_jitter_panel_png_dir,
    "pseudotime_state_deg_jitter_plot_panel.png"
  ),
  width = panel_width,
  height = panel_height,
  units = "in",
  dpi = figure_dpi,
  bg = "transparent",
  device = ragg::agg_png
)


## Print output summary ------------------------------------------------------

message(
  "Saved pseudotime state DEG jitter plot to:\n",
  pseudotime_state_deg_jitter_figure_dir
)
