# CAF subcluster composition within pseudotime states
#
# This script reproduces the p4 plot from the original pseudotime plotting
# function. It shows the number of cells from each CAF subcluster within each
# pseudotime state.
#
# The composition table is generated by:
#   05_02_pseudotime_extract_metadata_and_state_composition.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define input and output directories ---------------------------------------

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

pseudotime_figure_dir <- file.path(
  xenium_figure_dir,
  "08_05_pseudotime_analysis"
)

pseudotime_state_composition_figure_dir <- file.path(
  pseudotime_figure_dir,
  "08_05_02_pseudotime_state_caf_subcluster_composition"
)

fs::dir_create(pseudotime_state_composition_figure_dir)


## Define input file ---------------------------------------------------------

state_composition_file <- file.path(
  pseudotime_table_dir,
  "pseudotime_analysis_state_caf_subcluster_composition.csv"
)

if (!file.exists(state_composition_file)) {
  stop(
    "Required input file was not found:\n",
    state_composition_file,
    call. = FALSE
  )
}


## Read and validate input table --------------------------------------------

state_composition_table <- readr::read_csv(
  state_composition_file,
  show_col_types = FALSE
)

required_columns <- c(
  "state",
  "caf_subcluster",
  "n_cells"
)

missing_columns <- setdiff(
  required_columns,
  colnames(state_composition_table)
)

if (length(missing_columns) > 0) {
  stop(
    "Required columns are missing: ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

state_levels <- paste0(
  "State ",
  sort(
    unique(
      readr::parse_number(state_composition_table$state)
    )
  )
)

caf_subcluster_levels <- paste0(
  "CAF-",
  setdiff(
    caf_subcluster_number_order,
    pseudotime_excluded_caf_subcluster
  )
)

caf_subcluster_colors <- stats::setNames(
  unname(caf_subcluster_colors_number_named),
  paste0("CAF-", names(caf_subcluster_colors_number_named))
)

missing_caf_colors <- setdiff(
  caf_subcluster_levels,
  names(caf_subcluster_colors)
)

if (length(missing_caf_colors) > 0) {
  stop(
    "CAF subcluster colors were not defined for: ",
    paste(missing_caf_colors, collapse = ", "),
    call. = FALSE
  )
}

state_composition_table <- state_composition_table %>%
  mutate(
    state = factor(
      state,
      levels = state_levels
    ),
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_levels
    )
  )

if (any(is.na(state_composition_table$state))) {
  stop(
    "Some state labels could not be matched to the expected state order.",
    call. = FALSE
  )
}

if (any(is.na(state_composition_table$caf_subcluster))) {
  stop(
    "Some CAF subcluster labels could not be matched to the expected order.",
    call. = FALSE
  )
}


## Create plot ---------------------------------------------------------------

plot_state_caf_subcluster_composition <- ggplot(
  state_composition_table,
  aes(
    x = state,
    y = n_cells,
    fill = caf_subcluster
  )
) +
  geom_col(
    color = "gray50",
    linewidth = 0.3
  ) +
  labs(
    x = "State",
    y = "Number of cells",
    fill = NULL
  ) +
  scale_x_discrete(
    labels = function(x) str_remove(x, pattern = "State ")
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.03)),
    breaks = c(0, 500, 1000)
  ) +
  scale_fill_manual(
    values = caf_subcluster_colors[caf_subcluster_levels],
    drop = FALSE
  ) +
  theme(
    aspect.ratio = 0.70,
    axis.title = element_text(
      color = "black",
      size = 10
    ),
    axis.text.x = element_text(
      color = "black",
      size = 10
    ),
    axis.text.y = element_text(
      color = "black",
      size = 10
    ),
    legend.text = element_text(
      color = "black",
      size = 10
    ),
    plot.background = element_rect(
      fill = NA,
      color = NA
    ),
    panel.background = element_rect(
      fill = NA,
      color = NA
    ),
    legend.background = element_rect(
      fill = NA,
      color = NA
    ),
    legend.key = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "black"
    ),
    panel.grid = element_blank()
  )


## Save figure ---------------------------------------------------------------

ggsave(
  plot = plot_state_caf_subcluster_composition,
  filename = file.path(
    pseudotime_state_composition_figure_dir,
    "pseudotime_state_caf_subcluster_composition.pdf"
  ),
  width = 5,
  height = 5,
  units = "in",
  bg = "transparent",
  device = grDevices::cairo_pdf
)


## Print output summary ------------------------------------------------------

message(
  "Saved pseudotime state CAF subcluster composition figure to:\n",
  pseudotime_state_composition_figure_dir
)
