# Gene set coverage in the Xenium panel
#
# This script calculates the coverage of gene sets used in the Xenium analyses.
# Coverage is defined as the percentage of genes in each original gene set that
# are retained in the RNA assay of the downstream Xenium analysis object.
#
# Two tables are exported: one containing the selected gene sets used for cell
# cycle, hypoxia, CAF-8 marker, myCAF, and iCAF analyses, and another containing
# all MSigDB Hallmark gene sets.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(msigdbr)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_03_genes_and_marker_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))

fs::dir_create(xenium_table_dir)


## Read genes retained in the Xenium analysis object ------------------------

xenium_gene_table <- readr::read_csv(
  file.path(
    xenium_table_dir,
    "xenium_gene_symbols.csv"
  ),
  show_col_types = FALSE
)

required_xenium_gene_columns <- "gene_symbol"
missing_xenium_gene_columns <- setdiff(
  required_xenium_gene_columns,
  colnames(xenium_gene_table)
)

if (length(missing_xenium_gene_columns) > 0) {
  stop(
    paste0(
      "The Xenium gene table is missing the following required column: ",
      paste(missing_xenium_gene_columns, collapse = ", "),
      "."
    ),
    call. = FALSE
  )
}

if (nrow(xenium_gene_table) == 0) {
  stop(
    "The Xenium gene table contains no genes.",
    call. = FALSE
  )
}

if (anyNA(xenium_gene_table$gene_symbol)) {
  stop(
    "Missing gene symbols were found in the Xenium gene table.",
    call. = FALSE
  )
}

if (any(xenium_gene_table$gene_symbol == "")) {
  stop(
    "Empty gene symbols were found in the Xenium gene table.",
    call. = FALSE
  )
}

if (anyDuplicated(xenium_gene_table$gene_symbol)) {
  stop(
    "Duplicated gene symbols were found in the Xenium gene table.",
    call. = FALSE
  )
}

xenium_gene_symbols <- xenium_gene_table$gene_symbol


## Read CAF-8 signature gene set ---------------------------------------------

# The curated CAF-8 signature gene table is distributed with this repository
# to simplify the analysis workflow. The same table can also be regenerated by
# 02_02_caf_subcluster_marker_analysis.R.

caf8_marker_table <- read.csv(
  caf8_signature_genes_table_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_caf8_marker_columns <- "gene"
missing_caf8_marker_columns <- setdiff(
  required_caf8_marker_columns,
  colnames(caf8_marker_table)
)

if (length(missing_caf8_marker_columns) > 0) {
  stop(
    paste0(
      "The CAF-8 marker table is missing the following required column: ",
      paste(missing_caf8_marker_columns, collapse = ", "),
      "."
    ),
    call. = FALSE
  )
}

caf8_marker_genes <- caf8_marker_table$gene

if (anyNA(caf8_marker_genes) || any(caf8_marker_genes == "")) {
  stop(
    "Missing or empty gene symbols were found in the CAF-8 marker table.",
    call. = FALSE
  )
}

caf8_marker_genes <- unique(caf8_marker_genes)


## Retrieve MSigDB gene sets -------------------------------------------------

hallmark_gene_set_table <- msigdbr::msigdbr(
  species = "Homo sapiens",
  category = "H"
)

hallmark_gene_sets <- hallmark_gene_set_table %>%
  split(.$gs_name) %>%
  lapply(function(gene_set_table) {
    unique(gene_set_table$gene_symbol)
  })

curated_gene_set_table <- msigdbr::msigdbr(
  species = "Homo sapiens",
  category = "C2"
)

kegg_cell_cycle_genes <- curated_gene_set_table %>%
  dplyr::filter(.data$gs_name == "KEGG_CELL_CYCLE") %>%
  dplyr::pull(.data$gene_symbol) %>%
  unique()

if (length(kegg_cell_cycle_genes) == 0) {
  stop(
    "The KEGG_CELL_CYCLE gene set was not found in the MSigDB C2 collection.",
    call. = FALSE
  )
}


## Define gene set coverage function ----------------------------------------

calculate_gene_set_coverage <- function(
    gene_set_name,
    gene_symbols,
    xenium_gene_symbols
) {
  gene_symbols <- unique(gene_symbols)
  intersecting_gene_symbols <- intersect(
    gene_symbols,
    xenium_gene_symbols
  )
  
  if (length(gene_symbols) == 0) {
    stop(
      paste0(
        "The gene set '",
        gene_set_name,
        "' contains no genes."
      ),
      call. = FALSE
    )
  }
  
  tibble::tibble(
    GeneSet = gene_set_name,
    OrigGenes = paste(sort(gene_symbols), collapse = ", "),
    NumOfOrigGenes = length(gene_symbols),
    Intersect = paste(sort(intersecting_gene_symbols), collapse = ", "),
    NumOfIntersect = length(intersecting_gene_symbols),
    Coverage = length(intersecting_gene_symbols) / length(gene_symbols) * 100
  )
}


## Calculate coverage of selected gene sets ---------------------------------

selected_gene_set_coverage <- dplyr::bind_rows(
  calculate_gene_set_coverage(
    gene_set_name = "Sphase",
    gene_symbols = Seurat::cc.genes$s.genes,
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "G2Mphase",
    gene_symbols = Seurat::cc.genes$g2m.genes,
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "KEGG_cell_cycle",
    gene_symbols = kegg_cell_cycle_genes,
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "Winter",
    gene_symbols = marker_table$gene[
      marker_table$set_name == "Winter"
    ],
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "Buffa",
    gene_symbols = marker_table$gene[
      marker_table$set_name == "Buffa"
    ],
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "CAF8",
    gene_symbols = caf8_marker_genes,
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "myCAF",
    gene_symbols = marker_table$gene[
      marker_table$set_name == "myCAF"
    ],
    xenium_gene_symbols = xenium_gene_symbols
  ),
  calculate_gene_set_coverage(
    gene_set_name = "iCAF",
    gene_symbols = marker_table$gene[
      marker_table$set_name == "iCAF"
    ],
    xenium_gene_symbols = xenium_gene_symbols
  )
) %>%
  dplyr::select(
    GeneSet,
    NumOfOrigGenes,
    NumOfIntersect,
    Coverage,
    Intersect
  )

readr::write_csv(
  selected_gene_set_coverage,
  file.path(
    xenium_table_dir,
    "xenium_gene_set_coverage.csv"
  )
)


## Calculate coverage of all Hallmark gene sets -----------------------------

hallmark_gene_set_coverage <- purrr::imap_dfr(
  hallmark_gene_sets,
  function(gene_symbols, gene_set_name) {
    calculate_gene_set_coverage(
      gene_set_name = gene_set_name,
      gene_symbols = gene_symbols,
      xenium_gene_symbols = xenium_gene_symbols
    )
  }
) %>%
  dplyr::select(
    GeneSet,
    NumOfOrigGenes,
    NumOfIntersect,
    Coverage,
    Intersect
  ) %>%
  dplyr::mutate(
    GeneSet = format_gene_set_label_for_table(.data$GeneSet)
  )

readr::write_csv(
  hallmark_gene_set_coverage,
  file.path(
    xenium_table_dir,
    "xenium_hallmark_gene_set_coverage.csv"
  )
)
