# CAF subcluster ssGSEA heatmaps
#
# This script generates CAF subcluster-level ssGSEA heatmaps using the
# ssGSEA summary table generated by 02_03_caf_subcluster_gene_set_scoring.R.
# The selected heatmap corresponds to the main figure panel, and the full
# heatmap with pathway dendrogram corresponds to the supplementary figure.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggdendro)
  library(patchwork)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))

stopifnot(exists("figure_bg"))
stopifnot(exists("caf_subcluster_display_order"))
stopifnot(exists("caf_subclustering_figure_dir"))
stopifnot(exists("diverging_colors"))
stopifnot(length(diverging_colors) == 3)
stopifnot(exists("format_gene_set_label"))


## Read ssGSEA summary table -------------------------------------------------

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

ssgsea_summary_file <- file.path(
  caf_subclustering_table_dir,
  "xenium_caf_subcluster_ssgsea_summary.csv"
)

stopifnot(file.exists(ssgsea_summary_file))

ssgsea_summary_df <- read.csv(
  ssgsea_summary_file,
  stringsAsFactors = FALSE
)

required_columns <- c(
  "caf_subcluster",
  "gene_set",
  "mean_ssGSEA_score",
  "z_score_within_gene_set"
)

stopifnot(all(required_columns %in% colnames(ssgsea_summary_df)))


## Prepare plotting data -----------------------------------------------------

ssgsea_heatmap_df <- ssgsea_summary_df %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    gene_set_label = format_gene_set_label(gene_set)
  ) %>%
  dplyr::filter(!is.na(caf_subcluster))

stopifnot(nrow(ssgsea_heatmap_df) > 0)
stopifnot(!any(is.na(ssgsea_heatmap_df$z_score_within_gene_set)))

zscore_matrix <- ssgsea_heatmap_df %>%
  dplyr::select(
    caf_subcluster,
    gene_set,
    z_score_within_gene_set
  ) %>%
  tidyr::pivot_wider(
    names_from = gene_set,
    values_from = z_score_within_gene_set
  ) %>%
  dplyr::arrange(caf_subcluster) %>%
  tibble::column_to_rownames(var = "caf_subcluster") %>%
  as.matrix()

stopifnot(nrow(zscore_matrix) == length(caf_subcluster_display_order))
stopifnot(identical(rownames(zscore_matrix), caf_subcluster_display_order))

zscore_long_df <- zscore_matrix %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "caf_subcluster") %>%
  tidyr::pivot_longer(
    cols = -caf_subcluster,
    names_to = "gene_set",
    values_to = "z_score_within_gene_set"
  ) %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = rev(caf_subcluster_display_order)
    ),
    gene_set_label = format_gene_set_label(gene_set)
  )

max_abs_zscore <- max(
  abs(zscore_long_df$z_score_within_gene_set),
  na.rm = TRUE
)


## Hierarchical clustering for supplementary heatmap -------------------------

pathway_distance <- dist(
  t(zscore_matrix),
  method = "euclidean"
)

pathway_hclust <- hclust(
  pathway_distance,
  method = "ward.D2"
)

pathway_order <- colnames(zscore_matrix)[pathway_hclust$order]
pathway_label_order <- format_gene_set_label(pathway_order)

supplementary_heatmap_df <- zscore_long_df %>%
  dplyr::mutate(
    gene_set_label = factor(
      gene_set_label,
      levels = pathway_label_order
    )
  )

pathway_dendrogram_data <- ggdendro::dendro_data(
  as.dendrogram(pathway_hclust)
)

plot_pathway_dendrogram <- ggplot(
  pathway_dendrogram_data$segments
) +
  geom_segment(
    aes(
      x = x,
      y = y,
      xend = xend,
      yend = yend
    )
  ) +
  scale_x_continuous(
    limits = c(0.5, length(pathway_hclust$labels) + 0.5),
    breaks = seq_along(pathway_hclust$labels),
    labels = pathway_hclust$labels,
    expand = expansion(mult = c(0, 0))
  ) +
  coord_fixed(ratio = 0.2) +
  theme_void()


## Supplementary heatmap: all gene sets --------------------------------------

plot_supplementary_heatmap <- ggplot(
  supplementary_heatmap_df,
  aes(
    y = caf_subcluster,
    x = gene_set_label,
    fill = z_score_within_gene_set
  )
) +
  geom_tile(color = "gray50") +
  labs(
    x = NULL,
    y = NULL,
    fill = "Z-score"
  ) +
  scale_x_discrete(
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0, 0)),
    position = "left"
  ) +
  scale_fill_gradientn(
    limits = c(-max_abs_zscore, max_abs_zscore),
    breaks = c(-2, 0, 2),
    colors = diverging_colors,
    guide = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      frame.colour = "black",
      ticks.colour = "black"
    )
  ) +
  coord_fixed(ratio = 1.15) +
  theme(
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0),
    legend.position = "bottom",
    axis.text = element_text(color = "black"),
    axis.text.x = element_text(
      angle = 90,
      hjust = 1,
      vjust = 0.5,
      size = 12
    ),
    axis.text.y = element_text(size = 12),
    legend.text = element_text(color = "black", size = 12),
    legend.title = element_text(size = 12),
    legend.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.border = element_rect(fill = "transparent", color = "black"),
    panel.grid = element_blank()
  )

plot_supplementary_heatmap_with_dendrogram <-
  plot_pathway_dendrogram +
  plot_supplementary_heatmap +
  patchwork::plot_layout(ncol = 1) &
  theme(
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA)
  )


## Main heatmap: selected gene sets ------------------------------------------

# Display order from top to bottom in the main heatmap.
main_gene_set_labels <- c(
  "myCAF signature",
  "EMT",
  "Hedgehog signaling",
  "TGF-β signaling",
  "Hypoxia",
  "Buffa hypoxia",
  "Winter hypoxia",
  "Glycolysis",
  "E2F targets",
  "G2/M checkpoint",
  "MYC targets V2",
  "Notch signaling",
  "Wnt/β-catenin signaling",
  "iCAF signature",
  "IL-2/STAT5 signaling",
  "IL-6/JAK/STAT3 signaling",
  "TNF-α signaling via NF-κB",
  "Inflammatory response",
  "IFN-α response",
  "Heme metabolism",
  "Peroxisome"
)

missing_main_gene_sets <- setdiff(
  main_gene_set_labels,
  unique(zscore_long_df$gene_set_label)
)

if (length(missing_main_gene_sets) > 0) {
  stop(
    "The following selected gene sets were not found: ",
    paste(missing_main_gene_sets, collapse = ", ")
  )
}

main_heatmap_df <- zscore_long_df %>%
  dplyr::filter(gene_set_label %in% main_gene_set_labels) %>%
  dplyr::mutate(
    caf_subcluster = factor(
      as.character(caf_subcluster),
      levels = caf_subcluster_display_order
    ),
    gene_set_label = factor(
      gene_set_label,
      levels = rev(main_gene_set_labels)
    )
  )

stopifnot(nrow(main_heatmap_df) > 0)

plot_main_heatmap <- ggplot(
  main_heatmap_df,
  aes(
    x = caf_subcluster,
    y = gene_set_label,
    fill = z_score_within_gene_set
  )
) +
  geom_tile(color = "gray50") +
  labs(
    x = "CAF subcluster",
    y = NULL,
    fill = "Z-score"
  ) +
  scale_x_discrete(
    labels = function(x) stringr::str_remove(x, "^CAF-"),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0, 0)),
    position = "right"
  ) +
  scale_fill_gradientn(
    limits = c(-max_abs_zscore, max_abs_zscore),
    breaks = c(-2, 0, 2),
    colors = diverging_colors,
    guide = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      frame.colour = "black",
      ticks.colour = "black",
      barwidth = 6.25,
      barheight = 1
    )
  ) +
  coord_fixed(ratio = 0.9) +
  theme(
    aspect.ratio = 2.82,
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0),
    legend.position = "bottom",
    axis.title.x = element_text(
      color = "black",
      size = 16.3
    ),
    axis.text.x = element_text(
      color = "black",
      size = 21
    ),
    axis.text.y = element_text(
      color = "black",
      size = 21
    ),
    legend.text = element_text(
      color = "black",
      size = 16.3
    ),
    legend.title = element_text(
      color = "black",
      size = 16.3
    ),
    legend.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.border = element_rect(fill = "transparent", color = "black"),
    axis.line = element_blank(),
    panel.grid = element_blank()
  )


## Save figures --------------------------------------------------------------

caf_subclustering_ssgsea_heatmap_figure_dir <- file.path(
  caf_subclustering_figure_dir,
  "08_02_05_caf_subcluster_ssgsea_heatmap"
)

fs::dir_create(caf_subclustering_ssgsea_heatmap_figure_dir)

ggsave(
  plot = plot_main_heatmap,
  filename = file.path(
    caf_subclustering_ssgsea_heatmap_figure_dir,
    "caf_subcluster_ssgsea_heatmap_main_selected_gene_sets.pdf"
  ),
  width = 8,
  height = 10,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)

ggsave(
  plot = plot_supplementary_heatmap_with_dendrogram,
  filename = file.path(
    caf_subclustering_ssgsea_heatmap_figure_dir,
    "caf_subcluster_ssgsea_heatmap_supplementary_all_gene_sets.pdf"
  ),
  width = 12,
  height = 8,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)
