# CAF subcluster marker volcano plots
#
# This script generates volcano plots for CAF subcluster marker genes using
# the CAF subcluster marker table generated by
# 02_02_caf_subcluster_marker_analysis.R.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(ggrastr)
  library(ragg)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

## Read CAF subcluster marker table -----------------------------------------

caf_marker_table <- read.csv(
  caf_marker_table_file,
  stringsAsFactors = FALSE
)

stopifnot(all(c("cluster", "avg_log2FC", "p_val_adj") %in%
                colnames(caf_marker_table)))


## Prepare CAF colors --------------------------------------------------------

caf_subcluster_plot_colors <- caf_subcluster_colors_label_named[
  caf_subcluster_display_order
]

stopifnot(identical(
  names(caf_subcluster_plot_colors),
  caf_subcluster_display_order
))
stopifnot(!any(is.na(caf_subcluster_plot_colors)))


## Prepare plotting data -----------------------------------------------------

caf_marker_table <- caf_marker_table %>%
  dplyr::mutate(
    cluster = as.character(cluster),
    cluster = dplyr::if_else(
      stringr::str_detect(cluster, "^CAF-"),
      cluster,
      paste0("CAF-", cluster)
    ),
    cluster = factor(
      cluster,
      levels = caf_subcluster_display_order
    ),
    minuslog10_adj_p = -log10(p_val_adj),
    minuslog10_adj_p_volcano = pmin(minuslog10_adj_p, 300),
    color_group = dplyr::case_when(
      p_val_adj < 0.05 & abs(avg_log2FC) > 1 ~ as.character(cluster),
      TRUE ~ "ns"
    )
  ) %>%
  dplyr::filter(!is.na(cluster))

caf8_marker_table <- caf_marker_table %>%
  dplyr::filter(cluster == proliferating_caf_subcluster)


## Common plot settings ------------------------------------------------------

common_theme_volcano <- theme(
  legend.position = "none",
  axis.text = element_text(color = "black"),
  axis.title = element_text(color = "black"),
  axis.ticks = element_line(color = "black"),
  strip.text.y = element_text(color = "black", angle = 0, hjust = 1, vjust = 0.5),
  strip.background = element_rect(fill = NA, color = NA),
  plot.background = element_rect(fill = "transparent", color = NA),
  panel.background = element_rect(fill = "transparent", color = NA),
  panel.grid.major.x = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.border = element_rect(fill = "transparent", color = "black")
)


## CAF-8 volcano plot --------------------------------------------------------

x_limit_caf8 <- max(abs(caf8_marker_table$avg_log2FC), na.rm = TRUE)

plot_caf8_volcano <- ggplot(
  caf8_marker_table,
  aes(x = avg_log2FC, y = minuslog10_adj_p_volcano)
) + 
  ggrastr::rasterise(
    geom_point(
      data = caf8_marker_table %>%
        dplyr::filter(color_group == "ns"),
      color = "gray70",
      size = 0.72
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  ggrastr::rasterise(
    geom_point(
      data = caf8_marker_table %>%
        dplyr::filter(color_group != "ns"),
      aes(fill = color_group),
      shape = 21,
      size = 1.44,
      color = "black",
      stroke = 0.05
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  labs(
    x = "log2 fold change",
    y = "−log10(adjusted P value)"
  ) +
  scale_y_continuous(
    limits = c(0, 300),
    breaks = c(0, 100, 200, 300),
    labels = c(0, 100, 200, 300)
  ) +
  scale_x_continuous(
    breaks = c(-4, 0, 4),
    limits = c(-x_limit_caf8, x_limit_caf8)
  ) +
  scale_fill_manual(
    values = caf_subcluster_plot_colors[proliferating_caf_subcluster]
  ) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.3) +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.3) +
  common_theme_volcano +
  theme(
    aspect.ratio = 4.4 / 4.82
  )


## Faceted volcano plot for all CAF subclusters ------------------------------

plot_all_caf_volcano <- ggplot(
  caf_marker_table,
  aes(x = avg_log2FC, y = minuslog10_adj_p_volcano)
) + 
  ggrastr::rasterise(
    geom_point(
      data = caf_marker_table %>%
        dplyr::filter(color_group == "ns"),
      color = "gray70",
      size = 0.45
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  ggrastr::rasterise(
    geom_point(
      data = caf_marker_table %>%
        dplyr::filter(color_group != "ns"),
      aes(fill = color_group),
      shape = 21,
      size = 1.35,
      stroke = 0.075,
      color = "black"
    ),
  dpi = figure_dpi,
  dev = "ragg"
  ) +
  labs(
    x = "log2 fold change",
    y = "−log10(adjusted P value)"
  ) +
  scale_y_continuous(
    limits = c(0, 300)
  ) +
  scale_x_continuous(
    breaks = c(-6, -3, 0, 3, 6)
  ) +
  scale_fill_manual(
    values = caf_subcluster_plot_colors
  ) +
  facet_grid(cluster ~ .) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.3) +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.3) +
  common_theme_volcano


## Save figures --------------------------------------------------------------

caf_subclustering_subcluster_marker_volcano_figure_dir <- file.path(
  caf_subclustering_figure_dir,
  "08_02_03_caf_subcluster_marker_volcano"
)

fs::dir_create(caf_subclustering_subcluster_marker_volcano_figure_dir)

ggsave(
  plot = plot_caf8_volcano,
  filename = file.path(
    caf_subclustering_subcluster_marker_volcano_figure_dir,
    "caf8_marker_volcano.pdf"
  ),
  width = 3,
  height = 4.5,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)

ggsave(
  plot = plot_all_caf_volcano,
  filename = file.path(
    caf_subclustering_subcluster_marker_volcano_figure_dir,
    "caf_subcluster_marker_volcano_faceted.pdf"
  ),
  width = 6.75,
  height = 6.75,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)

## Save panel-only PNG files -----------------------------------------------

# The physical panel dimensions below were measured from the corresponding
# PDF files used for figure assembly. Keeping these dimensions unchanged
# preserves the apparent point and line sizes when the PNG replaces the
# rasterized panel area in the PDF.

caf_subclustering_subcluster_marker_volcano_panel_png_figure_dir <- file.path(
  caf_subclustering_subcluster_marker_volcano_figure_dir,
  "panel_only_png"
)

fs::dir_create(caf_subclustering_subcluster_marker_volcano_panel_png_figure_dir)

caf8_panel_width <- 2.380153
caf8_panel_height <- 2.172750
facet_panel_width <- 3.375139
facet_panel_height <- 0.374583

# Extract the actual expanded panel ranges from the PDF plot objects. This is
# important for the faceted plot because every standalone PNG must retain the
# same x- and y-ranges as the corresponding facet in the PDF.
caf8_panel_params <- ggplot_build(plot_caf8_volcano)$layout$panel_params[[1]]
facet_panel_params <- ggplot_build(plot_all_caf_volcano)$layout$panel_params[[1]]

caf8_x_range <- caf8_panel_params$x.range
caf8_y_range <- caf8_panel_params$y.range
facet_x_range <- facet_panel_params$x.range
facet_y_range <- facet_panel_params$y.range

panel_only_theme <- common_theme_volcano +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    strip.text = element_blank(),
    strip.background = element_blank(),
    panel.border = element_blank(),
    plot.margin = margin(0, 0, 0, 0, unit = "pt")
  )

make_panel_only_volcano <- function(
    plot_data,
    x_range,
    y_range,
    ns_point_size,
    sig_point_size,
    fill_values
) {
  ggplot(
    plot_data,
    aes(x = avg_log2FC, y = minuslog10_adj_p_volcano)
  ) +
    geom_point(
        data = plot_data %>%
          dplyr::filter(color_group == "ns"),
        color = "gray70",
        size = ns_point_size
      ) +
    geom_point(
        data = plot_data %>%
          dplyr::filter(color_group != "ns"),
        aes(fill = color_group),
        shape = 21,
        size = sig_point_size,
        color = "black",
        stroke = 0.05
      ) +
    scale_x_continuous(
      limits = x_range,
      expand = expansion(mult = 0)
    ) +
    scale_y_continuous(
      limits = y_range,
      expand = expansion(mult = 0)
    ) +
    scale_fill_manual(values = fill_values) +
    geom_hline(yintercept = 0, color = "black", linewidth = 0.3) +
    geom_vline(xintercept = 0, color = "black", linewidth = 0.3) +
    panel_only_theme
}

# CAF-8 panel-only PNG.
plot_caf8_volcano_panel <- make_panel_only_volcano(
  plot_data = caf8_marker_table,
  x_range = caf8_x_range,
  y_range = caf8_y_range,
  ns_point_size = 0.72,
  sig_point_size = 1.44,
  fill_values = caf_subcluster_plot_colors[proliferating_caf_subcluster]
)

ggsave(
  plot = plot_caf8_volcano_panel,
  filename = file.path(
    caf_subclustering_subcluster_marker_volcano_panel_png_figure_dir,
    "caf8_marker_volcano_panel.png"
  ),
  width = caf8_panel_width,
  height = caf8_panel_height,
  units = "in",
  dpi = figure_dpi * 1.5,
  bg = figure_bg
)

# One panel-only PNG per CAF subcluster, in the same order as the PDF facets.
for (caf_subcluster in caf_subcluster_display_order) {
  plot_subcluster_panel <- make_panel_only_volcano(
    plot_data = caf_marker_table %>%
      dplyr::filter(cluster == caf_subcluster),
    x_range = facet_x_range,
    y_range = facet_y_range,
    ns_point_size = 0.3,
    sig_point_size = 0.9,
    fill_values = caf_subcluster_plot_colors[caf_subcluster]
  )

  subcluster_number <- stringr::str_remove(caf_subcluster, "^CAF-")

  ggsave(
    plot = plot_subcluster_panel,
    filename = file.path(
      caf_subclustering_subcluster_marker_volcano_panel_png_figure_dir,
      paste0(
        "caf",
        subcluster_number,
        "_marker_volcano_faceted_panel.png"
      )
    ),
    width = facet_panel_width,
    height = facet_panel_height,
    units = "in",
    dpi = figure_dpi * 1.5,
    bg = figure_bg
  )
}

