# CAF subcluster cluster-level GSEA bar plot
#
# This script generates a bar plot showing cluster-level GSEA results
# for CAF subclusters. It uses the GSEA result table generated by
# 02_04_caf_subcluster_cluster_level_gsea.R.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggtext)
  library(patchwork)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Read cluster-level GSEA results ------------------------------------------

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

gsea_result_file <- file.path(
  caf_subclustering_table_dir,
  "xenium_caf_subcluster_cluster_level_gsea_results.csv"
)

if (!file.exists(gsea_result_file)) {
  stop(
    "Cluster-level GSEA result table was not found: ", gsea_result_file,
    "\nRun 02_04_caf_subcluster_cluster_level_gsea.R first."
  )
}

gsea_result_table <- readr::read_csv(
  gsea_result_file,
  show_col_types = FALSE
)

required_columns <- c(
  "caf_subcluster",
  "direction",
  "significance",
  "ID",
  "NES",
  "p.adjust"
)

if (!all(required_columns %in% colnames(gsea_result_table))) {
  stop(
    "The cluster-level GSEA result table does not contain the required columns: ",
    paste(required_columns, collapse = ", ")
  )
}


## Prepare data for plotting -------------------------------------------------

caf_subcluster_display_order <- paste0("CAF-", caf_subcluster_order)

caf_subcluster_display_order <- caf_subcluster_display_order[
  caf_subcluster_display_order %in% unique(gsea_result_table$caf_subcluster)
]

if (length(caf_subcluster_display_order) == 0) {
  stop("No CAF subclusters in caf_subcluster_order were found in the GSEA table.")
}

gsea_result_table <- gsea_result_table %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    direction = stringr::str_to_upper(direction),
    significance_for_plot = dplyr::if_else(
      significance == "n.s.",
      "n.s.",
      "significant"
    )
  )

if ("gene_set_label" %in% colnames(gsea_result_table)) {
  gsea_result_table <- gsea_result_table %>%
    dplyr::mutate(
      gene_set_label_for_plot = gene_set_label
    )
} else {
  gsea_result_table <- gsea_result_table %>%
    dplyr::mutate(
      gene_set_label_for_plot = format_gene_set_label(ID)
    )
}

gsea_top_up <- gsea_result_table %>%
  dplyr::filter(direction == "UP") %>%
  dplyr::filter(!is.na(caf_subcluster)) %>%
  dplyr::group_by(caf_subcluster) %>%
  dplyr::slice_max(order_by = NES, n = 10, with_ties = FALSE) %>%
  dplyr::ungroup()

gsea_top_down <- gsea_result_table %>%
  dplyr::filter(direction == "DOWN") %>%
  dplyr::filter(!is.na(caf_subcluster)) %>%
  dplyr::group_by(caf_subcluster) %>%
  dplyr::slice_min(order_by = NES, n = 10, with_ties = FALSE) %>%
  dplyr::ungroup()

gsea_plot_table <- dplyr::bind_rows(
  gsea_top_up,
  gsea_top_down
) %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    )
  )

if (nrow(gsea_plot_table) == 0) {
  stop("No GSEA results were available for plotting.")
}

nes_axis_limit <- max(abs(gsea_plot_table$NES), na.rm = TRUE)
nes_fill_limit <- as.numeric(
  stats::quantile(abs(gsea_plot_table$NES), 0.975, na.rm = TRUE)
)

if (!is.finite(nes_fill_limit) || nes_fill_limit == 0) {
  nes_fill_limit <- nes_axis_limit
}


## Define plotting function --------------------------------------------------

plot_gsea_barplot_one_subcluster <- function(target_subcluster) {
  plot_table_one <- gsea_plot_table %>%
    dplyr::filter(caf_subcluster == target_subcluster) %>%
    dplyr::arrange(NES) %>%
    dplyr::mutate(
      gene_set_plot_id = forcats::fct_inorder(
        paste0(as.character(ID), "___", as.character(caf_subcluster))
      ),
      NES_fill = dplyr::if_else(
        significance_for_plot == "n.s.",
        NA_real_,
        NES
      ),
      column_border = dplyr::if_else(
        significance_for_plot == "n.s.",
        "n.s.",
        "significant"
      ),
      label_x = dplyr::if_else(
        NES > 0,
        -0.04 * nes_axis_limit,
        0.04 * nes_axis_limit
      ),
      label_hjust = dplyr::if_else(NES > 0, 1, 0)
    )
  
  ggplot(
    plot_table_one,
    aes(
      x = NES,
      y = gene_set_plot_id,
      fill = NES_fill,
      color = column_border
    )
  ) +
    geom_col(linewidth = 0.25) +
    geom_vline(xintercept = 0, linewidth = 0.3) +
    geom_text(
      data = dplyr::filter(
        plot_table_one,
        significance_for_plot == "significant"
      ),
      aes(
        x = label_x,
        label = gene_set_label_for_plot,
        hjust = label_hjust
      ),
      color = "black",
      size = 3.0
    ) +
    geom_text(
      data = dplyr::filter(
        plot_table_one,
        significance_for_plot == "n.s."
      ),
      aes(
        x = label_x,
        label = gene_set_label_for_plot,
        hjust = label_hjust
      ),
      color = "gray60",
      size = 3.0
    ) +
    labs(
      title = as.character(target_subcluster),
      x = NULL,
      y = NULL,
      fill = "NES"
    ) +
    scale_x_continuous(
      limits = c(-nes_axis_limit, nes_axis_limit),
      breaks = scales::pretty_breaks(n = 5)
    ) +
    scale_y_discrete() +
    scale_fill_gradient2(
      low = diverging_colors[1],
      mid = diverging_colors[2],
      high = diverging_colors[3],
      limits = c(-nes_fill_limit, nes_fill_limit),
      oob = scales::squish,
      na.value = "gray90",
      guide = guide_colorbar(
        frame.colour = "black",
        ticks.colour = "black",
        barheight = 1.5,
        barwidth = 9
      )
    ) +
    scale_color_manual(
      values = c(
        "significant" = "black",
        "n.s." = NA
      ),
      guide = "none"
    ) +
    theme(
      aspect.ratio = 0.72,
      plot.title = element_text(hjust = 0.5, size = 15),
      legend.title = element_text(hjust = 0.5, size = 14),
      legend.text = element_text(hjust = 0.5, size = 14),
      axis.text.x = element_text(color = "black", size = 10),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      legend.key = element_blank(),
      legend.title.position = "top",
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.border = element_rect(fill = NA, color = "black")
    )
}


## Generate plot -------------------------------------------------------------

plot_list <- purrr::map(
  caf_subcluster_display_order,
  plot_gsea_barplot_one_subcluster
)

plot_cluster_level_gsea <- (
  patchwork::wrap_plots(plot_list, nrow = 3) +
    patchwork::plot_layout(guides = "collect")
) &
  theme(
    legend.position = "bottom",
    legend.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA)
  )


## Save output ---------------------------------------------------------------

caf_subclustering_cluster_level_gsea_barplot_dir <- file.path(
  caf_subclustering_figure_dir,
  "08_02_06_caf_subcluster_cluster_level_gsea_barplot"
)

fs::dir_create(caf_subclustering_cluster_level_gsea_barplot_dir)

ggsave(
  plot = plot_cluster_level_gsea,
  filename = file.path(
    caf_subclustering_cluster_level_gsea_barplot_dir,
    "caf_subcluster_cluster_level_gsea_barplot.pdf"
  ),
  width = 17.5,
  height = 11.0,
  bg = figure_bg,
  device = grDevices::cairo_pdf
)
