# CAF-8 cell cycle score plots
#
# This script generates cell cycle score plots for CAF subclusters using
# single-cell cell-cycle score tables generated by
# 02_03_caf_subcluster_gene_set_scoring.R.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggpubr)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

## Read cell-cycle score table -----------------------------------------------

cell_cycle_score_table <- read.csv(
  file.path(
    caf_subclustering_table_dir,
    "xenium_caf_single_cell_cell_cycle_scores.csv"
  ),
  stringsAsFactors = FALSE
)

stopifnot(all(c(
  "cell_id",
  "caf_subcluster",
  "S.Score",
  "G2M.Score"
) %in% colnames(cell_cycle_score_table)))


## Prepare CAF subcluster colors --------------------------------------------

caf_subcluster_plot_colors <- caf_subcluster_colors_label_named[
  caf_subcluster_display_order
]

stopifnot(identical(
  names(caf_subcluster_plot_colors),
  caf_subcluster_display_order
))
stopifnot(!any(is.na(caf_subcluster_plot_colors)))


## Prepare plotting data -----------------------------------------------------

plot_df <- cell_cycle_score_table %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    caf8_highlight = dplyr::if_else(
      caf_subcluster == proliferating_caf_subcluster,
      proliferating_caf_subcluster,
      "Other CAFs"
    )
  ) %>%
  dplyr::filter(!is.na(caf_subcluster))

stopifnot(!any(is.na(plot_df$S.Score)))
stopifnot(!any(is.na(plot_df$G2M.Score)))


## Violin plots --------------------------------------------------------------

plot_cell_cycle_violin <- function(score_column, y_label, y_breaks) {
  plot_df %>%
    dplyr::select(caf_subcluster, dplyr::all_of(score_column)) %>%
    rlang::set_names(c("caf_subcluster", "score")) %>%
    ggplot(aes(x = caf_subcluster, y = score, fill = caf_subcluster)) +
    geom_violin(
      trim = TRUE,
      scale = "width",
      width = 0.6
    ) +
    geom_boxplot(
      width = 0.2,
      fill = "white",
      outlier.shape = NA
    ) +
    labs(
      x = "CAF subcluster",
      y = y_label
    ) +
    scale_fill_manual(
      values = caf_subcluster_plot_colors
    ) +
    scale_x_discrete(
      labels = function(x) str_remove(x, pattern = "CAF-")
    ) +
    scale_y_continuous(
      breaks = y_breaks
    ) +
    theme(
      legend.position = "none",
      axis.text.x = element_text(
        color = "black",
      ),
      axis.text.y = element_text(
        color = "black"
      ),
      axis.title.y = element_text(
        color = "black"
      ),
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      axis.line = element_blank(),
      panel.border = element_rect(fill = "transparent", color = "black")
    )
}

plot_s_score_violin <- plot_cell_cycle_violin(
  score_column = "S.Score",
  y_label = "S score",
  y_breaks = c(0, 0.6, 1.2)
)

plot_g2m_score_violin <- plot_cell_cycle_violin(
  score_column = "G2M.Score",
  y_label = "G2/M score",
  y_breaks = c(0, 0.3, 0.6)
)


## S score vs G2/M score scatter plot ----------------------------------------

cell_cycle_scatter_aspect_ratio <- 1.3

plot_df_other <- plot_df %>%
  dplyr::filter(caf_subcluster != proliferating_caf_subcluster)

plot_df_caf8 <- plot_df %>%
  dplyr::filter(caf_subcluster == proliferating_caf_subcluster)

plot_cell_cycle_scatter <- ggplot(
) +
  ggrastr::rasterise(
    geom_point(
      data = plot_df_other,
      aes(x = S.Score, y = G2M.Score),
      color = "gray80",
      size = 1.35,
      alpha = 0.35,
      shape = 16
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  ggrastr::rasterise(
    geom_point(
      data = plot_df_caf8,
      aes(x = S.Score, y = G2M.Score),
      color = caf_subcluster_plot_colors[[proliferating_caf_subcluster]],
      size = 1.35,
      alpha = 0.9,
      shape = 16
    ),
    dpi = figure_dpi,
    dev = "ragg"
  ) +
  labs(
    x = "S score",
    y = "G2/M score"
  ) +
  scale_x_continuous(
    breaks = c(0, 0.6, 1.2)
  ) +
  scale_y_continuous(
    breaks = c(0, 0.3, 0.6)
  ) +
  theme(
    aspect.ratio = cell_cycle_scatter_aspect_ratio,
    axis.text = element_text(
      face = "bold",
      color = "black"
    ),
    axis.title = element_text(
      face = "bold",
      color = "black"
    ),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black")
  )

plot_cell_cycle_scatter_points_only <- ggplot() +
  geom_point(
    data = plot_df_other,
    aes(x = S.Score, y = G2M.Score),
    color = "gray80",
    size = 1.35,
    alpha = 0.35,
    shape = 16
  ) +
  geom_point(
    data = plot_df_caf8,
    aes(x = S.Score, y = G2M.Score),
    color = caf_subcluster_plot_colors[[proliferating_caf_subcluster]],
    size = 1.35,
    alpha = 0.9,
    shape = 16
  ) +
  scale_x_continuous(
    breaks = c(0, 0.6, 1.2)
  ) +
  scale_y_continuous(
    breaks = c(0, 0.3, 0.6)
  ) +
  theme(
    aspect.ratio = cell_cycle_scatter_aspect_ratio,
    legend.position = "none",
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    plot.margin = margin(0, 0, 0, 0)
  )

## Save figures --------------------------------------------------------------

caf_subclustering_caf8_cell_cycle_scores_figure_dir <- file.path(
  caf_subclustering_figure_dir,
  "08_02_07_caf8_cell_cycle_scores"
)

fs::dir_create(caf_subclustering_caf8_cell_cycle_scores_figure_dir)

ggsave(
  plot = plot_s_score_violin,
  filename = file.path(
    caf_subclustering_caf8_cell_cycle_scores_figure_dir,
    "caf8_cell_cycle_score_violin_s_score.pdf"
  ),
  width = 4,
  height = 2,
  bg = figure_bg
)

ggsave(
  plot = plot_g2m_score_violin,
  filename = file.path(
    caf_subclustering_caf8_cell_cycle_scores_figure_dir,
    "caf8_cell_cycle_score_violin_g2m_score.pdf"
  ),
  width = 4,
  height = 2,
  bg = figure_bg
)

ggsave(
  plot = plot_cell_cycle_scatter,
  filename = file.path(
    caf_subclustering_caf8_cell_cycle_scores_figure_dir,
    "caf8_cell_cycle_score_scatter.pdf"
  ),
  width = 4,
  height = 5,
  bg = figure_bg
)

cell_cycle_scatter_points_width <- 4

ggsave(
  plot = plot_cell_cycle_scatter_points_only,
  filename = file.path(
    caf_subclustering_caf8_cell_cycle_scores_figure_dir,
    "caf8_cell_cycle_score_scatter_points_only.png"
  ),
  width = 3.424,
  height = 3.424 * cell_cycle_scatter_aspect_ratio,
  units = "in",
  dpi = figure_dpi,
  bg = "transparent"
)
