# CAF subclustering supplementary tables
#
# This script formats supplementary tables for CAF subclustering analyses.
# It uses outputs generated by:
#   02_01_caf_extraction_and_subclustering.R
#   02_02_caf_subcluster_marker_analysis.R
#   02_03_caf_subcluster_gene_set_scoring.R
#   02_04_caf_subcluster_cluster_level_gsea.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

## Input files ---------------------------------------------------------------

ssgsea_summary_file <- file.path(
  caf_subclustering_table_dir,
  "xenium_caf_subcluster_ssgsea_summary.csv"
)

cell_cycle_summary_file <- file.path(
  caf_subclustering_table_dir,
  "xenium_caf_subcluster_cell_cycle_summary.csv"
)

cluster_level_gsea_file <- file.path(
  caf_subclustering_table_dir,
  "xenium_caf_subcluster_cluster_level_gsea_results.csv"
)

required_input_files <- c(
  caf_subcluster_metadata_file,
  caf_marker_table_file,
  ssgsea_summary_file,
  cell_cycle_summary_file,
  cluster_level_gsea_file
)

missing_input_files <- required_input_files[!file.exists(required_input_files)]

if (length(missing_input_files) > 0) {
  stop(
    "The following input files were not found:\n",
    paste(missing_input_files, collapse = "\n"),
    "\nRun 02_01 to 02_04 before running this script."
  )
}


## Output directory ----------------------------------------------------------

fs::dir_create(caf_subclustering_table_dir)


## 1. CAF subclustering summary ---------------------------------------------

caf_metadata_df <- readr::read_csv(
  caf_subcluster_metadata_file,
  show_col_types = FALSE
)

required_caf_metadata_columns <- c(
  "cell_id",
  "xenium_sample_id",
  "tx_id",
  "caf_subcluster"
)

stopifnot(all(required_caf_metadata_columns %in% colnames(caf_metadata_df)))

caf_metadata_df <- caf_metadata_df %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    xenium_sample_id = factor(
      xenium_sample_id,
      levels = xenium_sample_id_display_order
    )
  )

stopifnot(!any(is.na(caf_metadata_df$caf_subcluster)))

n_caf_cells <- nrow(caf_metadata_df)

# Use the initial-clustering metadata table to calculate the percentage among
# all QC-filtered Xenium cells. This table should contain all QC-filtered cells
# before CAF extraction.

if (exists("initial_metadata_file") && file.exists(initial_metadata_file)) {
  initial_metadata_df <- readr::read_csv(
    initial_metadata_file,
    show_col_types = FALSE
  )
  n_total_qc_cells <- nrow(initial_metadata_df)
} else {
  warning(
    "initial_metadata_file was not found. ",
    "pct_of_total_QC_cells will be set to NA."
  )
  n_total_qc_cells <- NA_real_
}

caf_subcluster_summary_table <- caf_metadata_df %>%
  dplyr::count(caf_subcluster, name = "cell_number") %>%
  tidyr::complete(
    caf_subcluster = factor(
      caf_subcluster_display_order,
      levels = caf_subcluster_display_order
    ),
    fill = list(cell_number = 0)
  ) %>%
  dplyr::arrange(caf_subcluster) %>%
  dplyr::mutate(
    pct_of_CAF = round(cell_number / n_caf_cells * 100, 2),
    pct_of_total_QC_cells = round(cell_number / n_total_qc_cells * 100, 2),
    caf_subcluster = as.character(caf_subcluster)
  ) %>%
  dplyr::rename(
    CAF_subcluster = caf_subcluster
  )

readr::write_csv(
  caf_subcluster_summary_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_summary.csv"
  )
)


## 2. CAF subcluster sample composition --------------------------------------

caf_subcluster_sample_count_table <- caf_metadata_df %>%
  dplyr::count(caf_subcluster, xenium_sample_id, name = "cell_number") %>%
  tidyr::complete(
    caf_subcluster = factor(
      caf_subcluster_display_order,
      levels = caf_subcluster_display_order
    ),
    xenium_sample_id = factor(
      xenium_sample_id_display_order,
      levels = xenium_sample_id_display_order
    ),
    fill = list(cell_number = 0)
  ) %>%
  dplyr::arrange(caf_subcluster, xenium_sample_id) %>%
  tidyr::pivot_wider(
    names_from = xenium_sample_id,
    values_from = cell_number
  ) %>%
  dplyr::mutate(
    caf_subcluster = as.character(caf_subcluster)
  ) %>%
  dplyr::rename(
    CAF_subcluster = caf_subcluster
  )

readr::write_csv(
  caf_subcluster_sample_count_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_sample_count.csv"
  )
)

caf_subcluster_sample_proportion_table <- caf_subcluster_sample_count_table %>%
  dplyr::mutate(
    row_total = rowSums(
      dplyr::across(dplyr::all_of(xenium_sample_id_display_order)),
      na.rm = TRUE
    )
  ) %>%
  dplyr::mutate(
    dplyr::across(
      dplyr::all_of(xenium_sample_id_display_order),
      ~ dplyr::if_else(row_total > 0, round(.x / row_total * 100, 2), NA_real_)
    )
  ) %>%
  dplyr::select(-row_total)

readr::write_csv(
  caf_subcluster_sample_proportion_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_sample_proportion.csv"
  )
)


## 3. CAF subcluster DEG table -----------------------------------------------

caf_marker_table <- readr::read_csv(
  caf_marker_table_file,
  show_col_types = FALSE
)

required_marker_columns <- c(
  "cluster",
  "gene",
  "avg_log2FC",
  "pct.1",
  "pct.2",
  "p_val",
  "p_val_adj"
)

stopifnot(all(required_marker_columns %in% colnames(caf_marker_table)))

caf_marker_supplementary_table <- caf_marker_table %>%
  dplyr::mutate(
    caf_subcluster = as.character(cluster),
    caf_subcluster = dplyr::if_else(
      stringr::str_detect(caf_subcluster, "^CAF-"),
      caf_subcluster,
      paste0("CAF-", caf_subcluster)
    ),
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    )
  ) %>%
  dplyr::arrange(
    caf_subcluster,
    dplyr::desc(avg_log2FC)
  ) %>%
  dplyr::transmute(
    CAF_subcluster = as.character(caf_subcluster),
    Gene = gene,
    avg_log2FC = avg_log2FC,
    pct_1 = pct.1,
    pct_2 = pct.2,
    P_value = p_val,
    FDR = p_val_adj
  )

readr::write_csv(
  caf_marker_supplementary_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_degs.csv"
  )
)


## 4. Mean and Z-score of ssGSEA scores --------------------------------------

ssgsea_summary_table <- readr::read_csv(
  ssgsea_summary_file,
  show_col_types = FALSE
)

required_ssgsea_columns <- c(
  "caf_subcluster",
  "gene_set",
  "mean_ssGSEA_score",
  "z_score_within_gene_set"
)

stopifnot(all(required_ssgsea_columns %in% colnames(ssgsea_summary_table)))

ssgsea_supplementary_table <- ssgsea_summary_table %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    gene_set_for_table = format_gene_set_label_for_table(gene_set)
  ) %>%
  dplyr::arrange(caf_subcluster, gene_set_for_table) %>%
  dplyr::transmute(
    CAF_subcluster = as.character(caf_subcluster),
    Gene_set = gene_set_for_table,
    Mean_ssGSEA_score = mean_ssGSEA_score,
    Z_score_within_gene_set = z_score_within_gene_set
  )

readr::write_csv(
  ssgsea_supplementary_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_ssgsea.csv"
  )
)


## 5. Cell-cycle scores -------------------------------------------------------

cell_cycle_summary_table <- readr::read_csv(
  cell_cycle_summary_file,
  show_col_types = FALSE
)

required_cell_cycle_columns <- c(
  "caf_subcluster",
  "mean_S_score",
  "mean_G2M_score"
)

stopifnot(all(required_cell_cycle_columns %in% colnames(cell_cycle_summary_table)))

cell_cycle_supplementary_table <- cell_cycle_summary_table %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    )
  ) %>%
  dplyr::arrange(caf_subcluster) %>%
  dplyr::transmute(
    CAF_subcluster = as.character(caf_subcluster),
    Mean_S_phase_score = mean_S_score,
    Mean_G2M_phase_score = mean_G2M_score
  )

readr::write_csv(
  cell_cycle_supplementary_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_cell_cycle_scores.csv"
  )
)


## 6. Cluster-level GSEA ------------------------------------------------------

cluster_level_gsea_table <- readr::read_csv(
  cluster_level_gsea_file,
  show_col_types = FALSE
)

required_gsea_columns <- c(
  "caf_subcluster",
  "direction",
  "ID",
  "NES",
  "p.adjust",
  "significance",
  "leading_edge",
  "core_enrichment"
)

stopifnot(all(required_gsea_columns %in% colnames(cluster_level_gsea_table)))

cluster_level_gsea_table <- cluster_level_gsea_table %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    )
  )

if ("gene_set_label_for_table" %in% colnames(cluster_level_gsea_table)) {
  cluster_level_gsea_table <- cluster_level_gsea_table %>%
    dplyr::mutate(
      gene_set_for_table = gene_set_label_for_table
    )
} else {
  cluster_level_gsea_table <- cluster_level_gsea_table %>%
    dplyr::mutate(
      gene_set_for_table = format_gene_set_label_for_table(ID)
    )
}

gsea_supplementary_table <- cluster_level_gsea_table %>%
  dplyr::arrange(
    caf_subcluster,
    desc(direction),
    dplyr::desc(abs(NES))
  ) %>%
  dplyr::transmute(
    CAF_subcluster = as.character(caf_subcluster),
    Direction = direction,
    Gene_set = gene_set_for_table,
    NES = NES,
    p.adjust = p.adjust,
    Significance = significance,
    Leading_edge = leading_edge,
    Core_enrichment = core_enrichment
  )

readr::write_csv(
  gsea_supplementary_table,
  file = file.path(
    caf_subclustering_table_dir,
    "supplementary_table_caf_subcluster_cluster_level_gsea.csv"
  )
)


## Completion message --------------------------------------------------------

message(
  "CAF subclustering supplementary tables were written to: ",
  caf_subclustering_table_dir
)
