# CAF subcluster cluster-level GSEA
#
# This script performs cluster-level GSEA for CAF subclusters using the
# CAF subcluster marker table generated by 02_02_caf_subcluster_marker_analysis.R.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(msigdbr)
  library(clusterProfiler)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_03_genes_and_marker_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))

caf_subclustering_table_dir <- file.path(
  xenium_table_dir,
  "caf_subclustering"
)

## Read Xenium gene identifier mapping ---------------------------------------

xenium_gene_identifier_mapping_file <- file.path(
  xenium_table_dir,
  "xenium_gene_symbol_entrez_mapping.csv"
)

if (!file.exists(xenium_gene_identifier_mapping_file)) {
  stop(
    "Xenium gene identifier mapping table was not found: ",
    xenium_gene_identifier_mapping_file,
    "\nRun 01_02_xenium_gene_identifier_mapping.R first.",
    call. = FALSE
  )
}

xenium_gene_identifier_mapping <- readr::read_csv(
  xenium_gene_identifier_mapping_file,
  show_col_types = FALSE,
  col_types = readr::cols(
    gene_symbol = readr::col_character(),
    entrez_id = readr::col_character(),
    mapping_source = readr::col_character()
  )
)

required_mapping_columns <- c(
  "gene_symbol",
  "entrez_id",
  "mapping_source"
)

if (!all(
  required_mapping_columns %in%
  colnames(xenium_gene_identifier_mapping)
)) {
  stop(
    "The Xenium gene identifier mapping table must contain: ",
    paste(required_mapping_columns, collapse = ", "),
    call. = FALSE
  )
}

if (nrow(xenium_gene_identifier_mapping) == 0) {
  stop(
    "The Xenium gene identifier mapping table is empty.",
    call. = FALSE
  )
}

if (
  anyNA(xenium_gene_identifier_mapping$gene_symbol) ||
  any(xenium_gene_identifier_mapping$gene_symbol == "")
) {
  stop(
    "The Xenium gene identifier mapping table contains missing or empty gene symbols.",
    call. = FALSE
  )
}

if (anyDuplicated(xenium_gene_identifier_mapping$gene_symbol)) {
  stop(
    "The Xenium gene identifier mapping table contains duplicated gene symbols.",
    call. = FALSE
  )
}


## Define gene sets ----------------------------------------------------------

hallmark_term2gene <- get_hallmark_term2gene()

c2_gene_sets <- msigdbr::msigdbr(
  species = "Homo sapiens",
  category = "C2"
)

additional_gene_sets_symbol <- dplyr::bind_rows(
  tibble::tibble(
    term = "Buffa_Hypoxia",
    symbol = buffa_hypoxia_genes
  ),
  tibble::tibble(
    term = "Winter_Hypoxia",
    symbol = winter_hypoxia_genes
  ),
  tibble::tibble(
    term = "KEGG_Cell_cycle",
    symbol = c2_gene_sets %>%
      dplyr::filter(gs_name == "KEGG_CELL_CYCLE") %>%
      dplyr::pull(gene_symbol) %>%
      unique()
  ),
  tibble::tibble(
    term = "myCAF_signature",
    symbol = myCAF_xenium_panel
  ),
  tibble::tibble(
    term = "iCAF_signature",
    symbol = iCAF_xenium_panel
  )
) %>%
  dplyr::filter(!is.na(symbol)) %>%
  dplyr::distinct(term, symbol)

additional_term2gene <- additional_gene_sets_symbol %>%
  dplyr::inner_join(
    xenium_gene_identifier_mapping %>%
      dplyr::select(
        gene_symbol,
        entrez_id
      ),
    by = c("symbol" = "gene_symbol")
  ) %>%
  dplyr::filter(!is.na(.data$entrez_id)) %>%
  dplyr::transmute(
    term = .data$term,
    gene = .data$entrez_id
  ) %>%
  dplyr::distinct(
    term,
    gene
  )

term2gene <- dplyr::bind_rows(
  hallmark_term2gene,
  additional_term2gene
) %>%
  dplyr::mutate(
    term = as.character(.data$term),
    gene = as.character(.data$gene)
  ) %>%
  dplyr::filter(
    !is.na(.data$term),
    .data$term != "",
    !is.na(.data$gene),
    .data$gene != ""
  ) %>%
  dplyr::distinct(
    term,
    gene
  )

if (nrow(term2gene) == 0) {
  stop(
    "The combined TERM2GENE table is empty.",
    call. = FALSE
  )
}

missing_additional_gene_sets <- setdiff(
  unique(additional_gene_sets_symbol$term),
  unique(additional_term2gene$term)
)

if (length(missing_additional_gene_sets) > 0) {
  stop(
    "No mapped Xenium-panel genes were found for the following gene sets: ",
    paste(missing_additional_gene_sets, collapse = ", "),
    call. = FALSE
  )
}


## Read CAF subcluster marker table -----------------------------------------

if (!file.exists(caf_marker_table_file)) {
  stop(
    "CAF subcluster marker table was not found: ", caf_marker_table_file,
    "\nRun 02_02_caf_subcluster_marker_analysis.R first, or update ",
    "caf_marker_table_file to match its output filename."
  )
}

caf_marker_table <- readr::read_csv(
  caf_marker_table_file,
  show_col_types = FALSE
)

required_marker_columns <- c(
  "cluster",
  "gene",
  "entrez_id",
  "avg_log2FC"
)

stopifnot(all(required_marker_columns %in% colnames(caf_marker_table)))

if (nrow(caf_marker_table) == 0) {
  stop("The CAF subcluster marker table is empty.", call. = FALSE)
}

if (any(is.na(caf_marker_table$gene)) ||
    any(caf_marker_table$gene == "")) {
  stop(
    "The CAF subcluster marker table contains missing or empty gene symbols.",
    call. = FALSE
  )
}

if (any(is.na(caf_marker_table$entrez_id))) {
  stop(
    "The CAF subcluster marker table contains missing Entrez IDs. ",
    "Run 01_02_xenium_gene_identifier_mapping.R and ",
    "02_02_caf_subcluster_marker_analysis.R before this script.",
    call. = FALSE
  )
}

marker_gene_identifier_check <- caf_marker_table %>%
  dplyr::distinct(
    gene,
    entrez_id
  ) %>%
  dplyr::mutate(
    entrez_id = as.character(.data$entrez_id)
  ) %>%
  dplyr::left_join(
    xenium_gene_identifier_mapping %>%
      dplyr::select(
        gene_symbol,
        mapping_entrez_id = entrez_id
      ),
    by = c("gene" = "gene_symbol")
  )

if (anyNA(marker_gene_identifier_check$mapping_entrez_id)) {
  stop(
    "Some genes in the CAF marker table are absent from the Xenium gene ",
    "identifier mapping table.",
    call. = FALSE
  )
}

inconsistent_gene_identifiers <- marker_gene_identifier_check %>%
  dplyr::filter(
    dplyr::coalesce(.data$entrez_id, "") !=
      dplyr::coalesce(.data$mapping_entrez_id, "")
  )

if (nrow(inconsistent_gene_identifiers) > 0) {
  stop(
    "Entrez IDs in the CAF marker table do not match the Xenium gene ",
    "identifier mapping table.",
    call. = FALSE
  )
}

caf_marker_table_entrez <- caf_marker_table %>%
  dplyr::mutate(
    caf_subcluster = as.character(.data$cluster),
    caf_subcluster = dplyr::if_else(
      stringr::str_detect(.data$caf_subcluster, "^CAF-"),
      .data$caf_subcluster,
      paste0("CAF-", .data$caf_subcluster)
    ),
    entrez_id = as.character(.data$entrez_id)
  )


## Run cluster-level GSEA -----------------------------------------------------

caf_subclusters <- caf_subcluster_display_order[
  caf_subcluster_display_order %in% unique(caf_marker_table_entrez$caf_subcluster)
]

if (length(caf_subclusters) == 0) {
  stop("No CAF subclusters in caf_subcluster_display_order were found in the marker table.")
}

gsea_result_table <- tibble::tibble()
gsea_result_list <- list()

for (target_subcluster in caf_subclusters) {
  message("Running cluster-level GSEA for ", target_subcluster)
  
  marker_table_target <- caf_marker_table_entrez %>%
    dplyr::filter(caf_subcluster == target_subcluster) %>%
    dplyr::arrange(dplyr::desc(avg_log2FC)) %>%
    dplyr::distinct(entrez_id, .keep_all = TRUE)
  
  gene_list <- marker_table_target$avg_log2FC
  names(gene_list) <- marker_table_target$entrez_id
  
  # Add a very small deterministic offset to avoid ties in the ranked list.
  # The offset is far smaller than the log2FC scale and does not change the
  # biological ranking except when values are exactly tied.
  gene_list <- gene_list + seq_along(gene_list) * 1e-12
  gene_list <- sort(gene_list, decreasing = TRUE)
  
  set.seed(1234)
  
  gsea_pos <- clusterProfiler::GSEA(
    geneList = gene_list,
    minGSSize = 10,
    TERM2GENE = term2gene,
    pvalueCutoff = 1,
    verbose = FALSE,
    eps = 0,
    scoreType = "pos"
  )
  
  set.seed(1234)
  
  gsea_neg <- clusterProfiler::GSEA(
    geneList = gene_list,
    minGSSize = 10,
    TERM2GENE = term2gene,
    pvalueCutoff = 1,
    verbose = FALSE,
    eps = 0,
    scoreType = "neg"
  )
  
  gsea_pos_df <- as.data.frame(gsea_pos@result) %>%
    dplyr::mutate(direction = "UP")
  
  gsea_neg_df <- as.data.frame(gsea_neg@result) %>%
    dplyr::mutate(direction = "DOWN")
  
  gsea_target_df <- dplyr::bind_rows(
    gsea_pos_df,
    gsea_neg_df
  )
  
  if (nrow(gsea_target_df) > 0) {
    gsea_target_df <- gsea_target_df %>%
      dplyr::mutate(
        caf_subcluster = target_subcluster,
        gene_set_label = format_gene_set_label(ID),
        gene_set_label_for_table = format_gene_set_label_for_table(ID),
        significance = dplyr::case_when(
          p.adjust < 0.001 ~ "***",
          p.adjust < 0.01 ~ "**",
          p.adjust < 0.05 ~ "*",
          TRUE ~ "n.s."
        )
      ) %>%
      dplyr::relocate(
        caf_subcluster,
        direction,
        significance,
        gene_set_label,
        gene_set_label_for_table,
        .before = ID
      )
    
    gsea_result_table <- dplyr::bind_rows(
      gsea_result_table,
      gsea_target_df
    )
  }
  
  gsea_result_list[[paste0(target_subcluster, "_UP")]] <- gsea_pos
  gsea_result_list[[paste0(target_subcluster, "_DOWN")]] <- gsea_neg
}


## Prepare supplementary table ----------------------------------------------

gsea_supplementary_table <- gsea_result_table %>%
  dplyr::transmute(
    CAF_subcluster = caf_subcluster,
    Direction = direction,
    Gene_set = gene_set_label_for_table,
    NES = NES,
    P_value = pvalue,
    FDR = p.adjust,
    Significance = significance,
    Leading_edge = leading_edge,
    Core_enrichment = core_enrichment
  )


## Save outputs --------------------------------------------------------------

fs::dir_create(caf_subclustering_table_dir)

readr::write_csv(
  gsea_result_table,
  file = file.path(
    caf_subclustering_table_dir,
    "xenium_caf_subcluster_cluster_level_gsea_results.csv"
  )
)

saveRDS(
  gsea_result_list,
  file = file.path(
    caf_subclustering_table_dir,
    "xenium_caf_subcluster_cluster_level_gsea_results.rds"
  )
)

