# Plot CAF proliferation
#
# This script visualizes longitudinal CAF proliferation measurements from CAF
# pairs cultured under 21% and 1% O2 during isolation and subsequently assayed
# under 21% and 1% O2. It reads the normalized luminescence table generated by
# code/06_caf_isolation_assays/06_04_analyze_caf_proliferation.R and generates
# figures only; statistical testing is performed in the analysis script.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_06_color_palettes.R"
))

## Define input and output paths ---------------------------------------------

caf_proliferation_normalized_luminescence_file <- file.path(
  caf_isolation_table_dir,
  "caf_proliferation_normalized_luminescence.csv"
)

caf_proliferation_figure_dir <- file.path(
  caf_isolation_figure_dir,
  "08_06_04_caf_proliferation_figures"
)

fs::dir_create(caf_proliferation_figure_dir)


## Define plot settings ------------------------------------------------------

caf_pair_display_order <- c("9", "12", "13")

proliferation_group_display_order <- c(
  "Hypo-CAF in 21% O2",
  "Hypo-CAF",
  "Normo-CAF",
  "Normo-CAF in 1% O2"
)

proliferation_group_labels <- c(
  "Hypo-CAF in 21% O2" = "Hypo-CAF in 21% O2",
  "Hypo-CAF" = "Hypo-CAF",
  "Normo-CAF" = "Normo-CAF",
  "Normo-CAF in 1% O2" = "Normo-CAF in 1% O2"
)

proliferation_group_colors <- c(
  "Hypo-CAF in 21% O2" = caf_culture_colors_4_groups[["hypocaf_in_normoxia"]],
  "Hypo-CAF" = caf_culture_colors_4_groups[["hypocaf_in_hypoxia"]],
  "Normo-CAF" = caf_culture_colors_4_groups[["normocaf_in_normoxia"]],
  "Normo-CAF in 1% O2" = caf_culture_colors_4_groups[["normocaf_in_hypomoxia"]]
)

figure_width <- 4.8
figure_height <- 2.88
figure_font_size <- 12
figure_aspect_ratio <- c(
  "9" = 1.25,
  "12" = 1.25,
  "13" = 1.25
)

## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }

  readr::read_csv(
    file,
    show_col_types = FALSE
  )
}

make_proliferation_plot <- function(plot_data, caf_pair_number) {
  ggplot(
    plot_data,
    aes(
      x = .data$time_after_seeding_hours,
      y = .data$log2_normalized_luminescence,
      color = .data$group,
      group = .data$group
    )
  ) +
    stat_summary(
      geom = "line",
      fun = mean,
      linewidth = 0.85,
      alpha = 0.9
    ) +
    stat_summary(
      geom = "errorbar",
      fun.data = function(x) {
        mean_value <- mean(x, na.rm = TRUE)
        standard_error <- stats::sd(x, na.rm = TRUE) /
          sqrt(sum(!is.na(x)))

        data.frame(
          y = mean_value,
          ymin = mean_value - standard_error,
          ymax = mean_value + standard_error
        )
      },
      width = 4,
      linewidth = 0.4,
      alpha = 0.65
    ) +
    stat_summary(
      geom = "point",
      fun = mean,
      size = 1.8,
      alpha = 0.9
    ) +
    scale_color_manual(
      values = proliferation_group_colors,
      breaks = proliferation_group_display_order,
      labels = proliferation_group_labels,
      drop = FALSE
    ) +
    scale_x_continuous(
      limits = c(20, 174),
      breaks = c(24, 72, 120, 168),
      minor_breaks = NULL,
      expand = expansion(mult = c(0, 0))
    ) +
    scale_y_continuous(
      limits = c(0, 4.5),
      breaks = 0:4,
      minor_breaks = NULL,
      oob = scales::squish,
      expand = expansion(mult = c(0, 0))
    ) +
    labs(
      x = "Time after seeding (h)",
      y = expression(log[2] * "(NL)"),
      color = NULL,
      title = paste0("CAF pair #", caf_pair_number)
    ) +
    theme_classic() +
    theme(
      aspect.ratio = figure_aspect_ratio[[caf_pair_number]],
      plot.title = element_text(
        face = "plain",
        hjust = 0.5,
        size = figure_font_size * 1.1,
        margin = margin(b = 5)
      ),
      axis.title = element_text(color = "black", size = figure_font_size * 1.1),
      axis.text = element_text(color = "black", size = figure_font_size),
      legend.text = element_text(color = "black", size = figure_font_size),
      axis.line = element_line(
        color = "black",
        linewidth = 0.4
      ),
      axis.ticks = element_line(
        color = "black",
        linewidth = 0.4
      ),
      legend.key = element_blank(),
      legend.background = element_blank(),
      plot.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      panel.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      plot.margin = margin(6, 6, 6, 6)
    )
}


## Read normalized luminescence table ---------------------------------------

caf_proliferation_data <- read_required_csv(
  caf_proliferation_normalized_luminescence_file,
  "CAF proliferation normalized luminescence file"
)

required_columns <- c(
  "CAF pair No.",
  "Isolation oxygen (%)",
  "Assay oxygen (%)",
  "Group",
  "Day",
  "Time after seeding (h)",
  "Replicate No.",
  "Raw luminescence",
  "Mean Day 1 luminescence",
  "Normalized luminescence",
  "log2(NL)"
)

missing_columns <- setdiff(
  required_columns,
  colnames(caf_proliferation_data)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing required columns in normalized luminescence table: ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

caf_proliferation_data <- caf_proliferation_data %>%
  dplyr::transmute(
    caf_pair_no = as.character(.data$`CAF pair No.`),
    isolation_oxygen_percent = as.character(
      .data$`Isolation oxygen (%)`
    ),
    assay_oxygen_percent = as.character(
      .data$`Assay oxygen (%)`
    ),
    group = factor(
      as.character(.data$Group),
      levels = proliferation_group_display_order
    ),
    day = as.integer(.data$Day),
    time_after_seeding_hours = as.numeric(
      .data$`Time after seeding (h)`
    ),
    replicate_no = as.integer(.data$`Replicate No.`),
    log2_normalized_luminescence = as.numeric(.data$`log2(NL)`)
  )


## Validate plot data --------------------------------------------------------

if (anyNA(caf_proliferation_data)) {
  stop(
    "Missing, non-convertible, or unrecognized values were detected in the ",
    "normalized luminescence table.",
    call. = FALSE
  )
}

if (!setequal(
  unique(caf_proliferation_data$caf_pair_no),
  caf_pair_display_order
)) {
  stop(
    "The normalized luminescence table does not contain the expected CAF ",
    "pairs: ",
    paste(caf_pair_display_order, collapse = ", "),
    ".",
    call. = FALSE
  )
}

if (!setequal(
  as.character(unique(caf_proliferation_data$group)),
  proliferation_group_display_order
)) {
  stop(
    "The normalized luminescence table does not contain the expected ",
    "proliferation groups.",
    call. = FALSE
  )
}

measurement_counts <- caf_proliferation_data %>%
  dplyr::count(
    .data$caf_pair_no,
    .data$group,
    .data$day,
    name = "replicate_count"
  )

if (!all(measurement_counts$replicate_count == 3)) {
  stop(
    "Each CAF pair, proliferation group, and day must contain exactly three ",
    "replicate measurements.",
    call. = FALSE
  )
}


## Generate and save proliferation plots ------------------------------------

for (caf_pair in caf_pair_display_order) {

  proliferation_plot <- make_proliferation_plot(
    plot_data = caf_proliferation_data %>%
      dplyr::filter(.data$caf_pair_no == caf_pair),
    caf_pair_number = caf_pair
  )

  proliferation_figure_file <- file.path(
    caf_proliferation_figure_dir,
    paste0(
      "caf_pair_",
      caf_pair,
      "_proliferation.pdf"
    )
  )

  ggsave(
    filename = proliferation_figure_file,
    plot = proliferation_plot,
    device = cairo_pdf,
    width = figure_width,
    height = figure_height,
    units = "in",
    bg = "transparent"
  )

  message(
    "Saved CAF proliferation figure: ",
    proliferation_figure_file
  )
}
