# CAF outgrowth figures
#
# This script generates the CAF outgrowth figures from the canonical CAF
# isolation metadata and the statistical summary tables generated by
# 06_02_analyze_caf_outgrowth.R.
#
# Outputs:
#   1. Paired comparison of time to outgrowth under 21% and 1% O2
#   2. Supplementary comparison by tumor location and neoadjuvant therapy
#
# Note: During manuscript preparation, project_dir is set to a local repository
# path. For public release, replace it with project_dir <- getwd(), and run this
# script from the repository root directory.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggsignif)
  library(patchwork)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_01_analysis_parameters.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_06_color_palettes.R"
))

## Define input and output paths ---------------------------------------------

caf_outgrowth_table_dir <- file.path(
  caf_isolation_output_dir,
  "tables"
)

caf_outgrowth_pair_summary_file <- file.path(
  caf_outgrowth_table_dir,
  "caf_outgrowth_pair_summary.csv"
)

caf_outgrowth_oxygen_comparison_file <- file.path(
  caf_outgrowth_table_dir,
  "caf_outgrowth_oxygen_comparison.csv"
)

caf_outgrowth_tumor_location_file <- file.path(
  caf_outgrowth_table_dir,
  "caf_outgrowth_by_tumor_location.csv"
)

caf_outgrowth_neoadjuvant_therapy_file <- file.path(
  caf_outgrowth_table_dir,
  "caf_outgrowth_by_neoadjuvant_therapy.csv"
)

caf_outgrowth_figure_dir <- file.path(
  caf_isolation_figure_dir,
  "08_06_02_caf_outgrowth_figures"
)

caf_outgrowth_oxygen_figure_file <- file.path(
  caf_outgrowth_figure_dir,
  "caf_outgrowth_by_isolation_oxygen.pdf"
)

caf_outgrowth_location_figure_file <- file.path(
  caf_outgrowth_figure_dir,
  "caf_outgrowth_by_tumor_location.pdf"
)

caf_outgrowth_nat_figure_file <- file.path(
  caf_outgrowth_figure_dir,
  "caf_outgrowth_by_neoadjuvant_therapy.pdf"
)

caf_outgrowth_aligned_file <- file.path(
  caf_outgrowth_figure_dir,
  "caf_outgrowth_aligned.pdf"
)

fs::dir_create(caf_outgrowth_figure_dir)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }

  readr::read_csv(
    file,
    show_col_types = FALSE
  )
}

format_p_value <- function(p_value) {
  if (p_value < 0.001) {
    "< 0.001"
  } else {
    formatC(
      p_value,
      format = "f",
      digits = 3
    )
  }
}

p_value_to_significance <- function(p_value) {
  dplyr::case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ "n.s."
  )
}


## Validate color palettes ---------------------------------------------------

required_caf_culture_colors <- c("H_CAF", "N_CAF")
required_nat_colors <- c("None", "GS", "GnP")
required_location_colors <- c("Ph", "Pb", "Pt")

if (!exists("caf_culture_colors")) {
  stop(
    "caf_culture_colors is not defined in 00_01_analysis_parameters.R.",
    call. = FALSE
  )
}

if (!exists("nat_colors")) {
  stop(
    "nat_colors is not defined in 00_01_analysis_parameters.R.",
    call. = FALSE
  )
}

if (!exists("location_colors")) {
  stop(
    "location_colors is not defined in 00_01_analysis_parameters.R.",
    call. = FALSE
  )
}

if (!all(required_caf_culture_colors %in% names(caf_culture_colors))) {
  stop(
    "caf_culture_colors must contain H_CAF and N_CAF.",
    call. = FALSE
  )
}

if (!all(required_nat_colors %in% names(nat_colors))) {
  stop(
    "nat_colors must contain None, GS, and GnP.",
    call. = FALSE
  )
}

if (!all(required_location_colors %in% names(location_colors))) {
  stop(
    "location_colors must contain Ph, Pb, and Pt.",
    call. = FALSE
  )
}


## Read data and analysis summaries ------------------------------------------

caf_isolation_metadata <- read_required_csv(
  caf_isolation_metadata_file,
  "CAF isolation metadata file"
)

caf_outgrowth_pair_summary <- read_required_csv(
  caf_outgrowth_pair_summary_file,
  "CAF outgrowth pair-level summary table"
)

oxygen_comparison_summary <- read_required_csv(
  caf_outgrowth_oxygen_comparison_file,
  "CAF outgrowth oxygen-comparison table"
)

tumor_location_summary <- read_required_csv(
  caf_outgrowth_tumor_location_file,
  "CAF outgrowth tumor-location table"
)

neoadjuvant_therapy_summary <- read_required_csv(
  caf_outgrowth_neoadjuvant_therapy_file,
  "CAF outgrowth neoadjuvant-therapy table"
)

required_metadata_columns <- c(
  "caf_pair_no",
  "neoadjuvant_therapy",
  "tumor_location",
  "isolation_oxygen_percent",
  "days_to_outgrowth"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(caf_isolation_metadata)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    "Missing required columns in CAF isolation metadata: ",
    paste(missing_metadata_columns, collapse = ", "),
    call. = FALSE
  )
}

required_pair_summary_columns <- c(
  "caf_pair_no",
  "tumor_location",
  "neoadjuvant_therapy",
  "mean_days_to_outgrowth"
)

missing_pair_summary_columns <- setdiff(
  required_pair_summary_columns,
  colnames(caf_outgrowth_pair_summary)
)

if (length(missing_pair_summary_columns) > 0) {
  stop(
    "Missing required columns in CAF outgrowth pair-level summary: ",
    paste(missing_pair_summary_columns, collapse = ", "),
    call. = FALSE
  )
}


## Prepare plotting data -----------------------------------------------------

caf_outgrowth_plot_data <- caf_isolation_metadata %>%
  dplyr::select(dplyr::all_of(required_metadata_columns)) %>%
  dplyr::mutate(
    isolation_oxygen = factor(
      as.character(.data$isolation_oxygen_percent),
      levels = c("21", "1")
    ),
    caf_culture = dplyr::recode(
      as.character(.data$isolation_oxygen_percent),
      `21` = "N_CAF",
      `1` = "H_CAF"
    ),
    caf_culture = factor(
      .data$caf_culture,
      levels = c("N_CAF", "H_CAF")
    ),
    tumor_location = factor(
      .data$tumor_location,
      levels = c("Ph", "Pb", "Pt")
    ),
    neoadjuvant_therapy = factor(
      .data$neoadjuvant_therapy,
      levels = c("None", "GS", "GnP")
    )
  ) %>%
  dplyr::arrange(
    .data$caf_pair_no,
    .data$caf_culture
  )

if (anyNA(caf_outgrowth_plot_data)) {
  stop(
    "Missing or unrecognized values were detected in the plotting data.",
    call. = FALSE
  )
}

caf_outgrowth_pair_plot_data <- caf_outgrowth_pair_summary %>%
  dplyr::select(dplyr::all_of(required_pair_summary_columns)) %>%
  dplyr::mutate(
    tumor_location = factor(
      .data$tumor_location,
      levels = c("Ph", "Pb", "Pt")
    ),
    neoadjuvant_therapy = factor(
      .data$neoadjuvant_therapy,
      levels = c("None", "GS", "GnP")
    )
  ) %>%
  dplyr::arrange(.data$caf_pair_no)

if (anyNA(caf_outgrowth_pair_plot_data)) {
  stop(
    paste0(
      "Missing or unrecognized values were detected in the pair-level ",
      "plotting data."
    ),
    call. = FALSE
  )
}

if (nrow(caf_outgrowth_pair_plot_data) !=
    dplyr::n_distinct(caf_outgrowth_pair_plot_data$caf_pair_no)) {
  stop(
    "The pair-level plotting data must contain one row per CAF pair.",
    call. = FALSE
  )
}

oxygen_p_value <- oxygen_comparison_summary$`P value`[[1]]
tumor_location_p_value <- tumor_location_summary$`P value`[[1]]
neoadjuvant_therapy_p_value <-
  neoadjuvant_therapy_summary$`P value`[[1]]

oxygen_significance_label <- p_value_to_significance(oxygen_p_value)
tumor_location_significance_label <- p_value_to_significance(tumor_location_p_value)
neoadjuvant_therapy_significance_label <- p_value_to_significance(neoadjuvant_therapy_p_value)


oxygen_p_label <- paste0(
  "Wilcoxon signed-rank,\nP = ",
  format_p_value(oxygen_p_value)
  )

tumor_location_p_label <- paste0(
  "Kruskal-Wallis,\nP = ",
  format_p_value(tumor_location_p_value)
)

neoadjuvant_therapy_p_label <- paste0(
  "Kruskal-Wallis,\nP = ",
  format_p_value(neoadjuvant_therapy_p_value)
)


## Figure settings -----------------------------------------------------------

text_size <- 10

y_axis_upper_limit <- max(
  c(
    caf_outgrowth_plot_data$days_to_outgrowth,
    caf_outgrowth_pair_plot_data$mean_days_to_outgrowth
  ),
  na.rm = TRUE
) + 4

oxygen_significance_y <- y_axis_upper_limit - 2
oxygen_test_label_y <- y_axis_upper_limit - 1.5
clinical_p_label_y <- y_axis_upper_limit - 1.5

common_y_scale <- scale_y_continuous(
  limits = c(0, y_axis_upper_limit),
  expand = expansion(mult = c(0, 0))
)

common_labs <- labs(
  x = NULL,
  y = "Days to outgrowth",
  fill = NULL
)

common_theme <- theme(
  legend.position = "none",
  axis.text = element_text(
    face = "plain",
    color = "black",
    size = text_size * 3
  ),
  axis.title = element_text(
    face = "plain",
    color = "black",
    size = text_size * 3
  ),
  plot.subtitle = element_text(
    face = "plain",
    color = "black",
    size = text_size * 3,
    hjust = 0.5
  ),
  plot.caption = element_text(
    face = "plain",
    color = "black",
    size = text_size * 2,
    hjust = 1
  ),
  plot.background = element_rect(
    fill = "transparent",
    color = NA
  ),
  panel.background = element_rect(
    fill = "transparent",
    color = NA
  ),
  panel.grid = element_blank(),
  panel.border = element_rect(
    fill = NA,
    color = "black",
    linewidth = 1.55
  ),
  axis.ticks = element_line(
    color = "black",
    linewidth = 1.24
  ),
  axis.ticks.length = unit(2, "mm"  )
)


## Paired isolation-oxygen plot ----------------------------------------------

plot_caf_outgrowth_oxygen <- ggplot(
  caf_outgrowth_plot_data,
  aes(
    x = .data$isolation_oxygen,
    y = .data$days_to_outgrowth,
    fill = .data$caf_culture
  )
) +
  geom_boxplot(
    width = 0.45,
    fill = "transparent",
    staplewidth = 0.50,
    linewidth = 0.8,
    outlier.shape = NA
  ) +
  geom_line(
    aes(group = .data$caf_pair_no),
    color = "gray60",
    linewidth = 0.4
  ) +
  geom_point(
    shape = 21,
    size = text_size * 0.4,
    position = position_jitter(
      width = 0.10,
      height = 0,
      seed = 1234
    )
  ) +
  ggsignif::geom_signif(
    comparisons = list(c("21", "1")),
    map_signif_level = FALSE,
    y_position = oxygen_significance_y,
    annotation = oxygen_significance_label,
    textsize = text_size * 1.5,
    fontface = "plain",
    vjust = 0.5,
    size = 1.0
  ) +
  scale_x_discrete(
    labels = function(x) {
      parse(text = isolation_oxygen_plot_labels[x])
    },
    expand = expansion(mult = c(0.40, 0.40))
  ) +
  scale_fill_manual(
    values = caf_culture_colors
  ) +
  common_y_scale +
  common_labs +
  labs(
    subtitle = "Oxygen condition",
    caption = oxygen_p_label) +
  theme(aspect.ratio = 1.508) +
  common_theme

## Tumor-location plot -------------------------------------------------------

plot_caf_outgrowth_location <- ggplot(
  caf_outgrowth_pair_plot_data,
  aes(
    x = .data$tumor_location,
    y = .data$mean_days_to_outgrowth
  )
) +
  geom_boxplot(
    width = 0.6,
    fill = "transparent",
    staplewidth = 0.6,
    linewidth = 0.8,
    outlier.shape = NA
  ) +
  geom_point(
    aes(fill = .data$tumor_location),
    shape = 21,
    size = text_size * 0.4,
    alpha = 1,
    position = position_jitter(
      width = 0.30,
      height = 0,
      seed = 1236
    )
  ) +
  annotate(
    "text",
    x = 2,
    y = clinical_p_label_y,
    label = tumor_location_significance_label,
    hjust = 0.5,
    size = text_size * 1.0,
    fontface = "plain"
  ) +
  scale_fill_manual(
    values = location_colors
  ) +
  scale_x_discrete(
    expand = expansion(mult = c(0.25, 0.25))
  ) +
  common_y_scale +
  common_labs +
  labs(
    subtitle = "Tumor location",
    caption = tumor_location_p_label) +
  theme(aspect.ratio = 1.267) +
  common_theme

## Neoadjuvant-therapy plot --------------------------------------------------

plot_caf_outgrowth_nat <- ggplot(
  caf_outgrowth_pair_plot_data,
  aes(
    x = .data$neoadjuvant_therapy,
    y = .data$mean_days_to_outgrowth
  )
) +
  geom_boxplot(
    width = 0.6,
    fill = "transparent",
    staplewidth = 0.6,
    linewidth = 0.8,
    outlier.shape = NA
  ) +
  geom_point(
    aes(fill = .data$neoadjuvant_therapy),
    shape = 21,
    size = text_size * 0.4,
    alpha = 1,
    position = position_jitter(
      width = 0.30,
      height = 0,
      seed = 1235
    )
  ) +
  annotate(
    "text",
    x = 2,
    y = clinical_p_label_y,
    label = neoadjuvant_therapy_significance_label,
    hjust = 0.5,
    size = text_size * 1.0,
    fontface = "plain"
  ) +
  scale_fill_manual(
    values = nat_colors
  ) +
  scale_x_discrete(
    expand = expansion(mult = c(0.20, 0.22))
  ) +
  common_y_scale +
  common_labs +
  labs(
    subtitle = "NAT",
    caption = neoadjuvant_therapy_p_label) +
  coord_fixed(ratio = 3 / 15) +
  theme(aspect.ratio = 1.338) +
  common_theme


## Combine supplementary panels ---------------------------------------------

plot_caf_outgrowth_aligned <- (
  plot_caf_outgrowth_oxygen |
  plot_caf_outgrowth_location |
    plot_caf_outgrowth_nat
) &
  theme(
    plot.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.background = element_rect(
      fill = "transparent",
      color = NA
    )
  )


## Save figures --------------------------------------------------------------

ggsave(
  filename = caf_outgrowth_oxygen_figure_file,
  plot = plot_caf_outgrowth_oxygen,
  device = grDevices::cairo_pdf,
  width = 7,
  height = 7,
  units = "in",
  bg = "transparent"
)

ggsave(
  filename = caf_outgrowth_location_figure_file,
  plot = plot_caf_outgrowth_location,
  device = grDevices::cairo_pdf,
  width = 7,
  height = 7,
  units = "in",
  bg = "transparent"
)

ggsave(
  filename = caf_outgrowth_nat_figure_file,
  plot = plot_caf_outgrowth_nat,
  device = grDevices::cairo_pdf,
  width = 7,
  height = 7,
  units = "in",
  bg = "transparent"
)

ggsave(
  filename = caf_outgrowth_aligned_file,
  plot = plot_caf_outgrowth_aligned,
  device = grDevices::cairo_pdf,
  width = 16,
  height = 7,
  units = "in",
  bg = "transparent"
)

message("Saved CAF outgrowth figures:")
message("  ", caf_outgrowth_oxygen_figure_file)
message("  ", caf_outgrowth_location_figure_file)
message("  ", caf_outgrowth_nat_figure_file)
message("  ", caf_outgrowth_aligned_file)

