# CAF subcluster local non-CAF-derived Winter hypoxia score violin plot
#
# This script generates violin plots showing local non-CAF-derived Winter
# hypoxia scores assigned to CAFs across CAF subclusters.
#
# Input table is generated by:
#   03_03_hypoxia_mapping_assign_local_non_caf_hypoxia_scores_to_cafs.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define output directories -------------------------------------------------

hypoxia_mapping_table_dir <- file.path(
  xenium_table_dir,
  "hypoxia_mapping"
)

hypoxia_score_violin_figure_dir <- file.path(
  hypoxia_mapping_figure_dir,
  "08_03_02_hypoxia_mapping_caf_subcluster_local_non_caf_hypoxia_score_violin"
)

fs::dir_create(hypoxia_score_violin_figure_dir)


## Read local hypoxia score table --------------------------------------------

local_hypoxia_score_file <- file.path(
  hypoxia_mapping_table_dir,
  "caf_assigned_local_non_caf_winter_hypoxia_scores.csv"
)

local_hypoxia_score_table <- readr::read_csv(
  local_hypoxia_score_file,
  show_col_types = FALSE
) %>%
  dplyr::mutate(
    SubClust = factor(
      SubClust,
      levels = paste0("CAF-", caf_subcluster_order)
    ),
    sample = factor(
      xenium_sample_id,
      levels = paste0("Xenium_", stringr::str_pad(1:6, 2, pad = "0"))
    )
  ) %>%
  dplyr::filter(!is.na(local_nonCAF_Winter_z_celltype))


## Prepare colors ------------------------------------------------------------

caf_subcluster_colors_number_named <- caf_subcluster_colors_number_named

if (all(names(caf_subcluster_colors_number_named) %in% as.character(0:8))) {
  names(caf_subcluster_colors_number_named) <- paste0("CAF-", names(caf_subcluster_colors_number_named))
}

caf_subcluster_colors_number_named <- caf_subcluster_colors_number_named[paste0("CAF-", caf_subcluster_order)]


## Generate violin plot -------------------------------------------------------

plot_local_hypoxia_violin <- ggplot(
  local_hypoxia_score_table,
  aes(x = SubClust, y = local_nonCAF_Winter_z_celltype)
) +
  geom_violin(
    aes(fill = SubClust),
    scale = "width",
    color = "black",
    linewidth = 0.3
  ) +
  geom_boxplot(
    width = 0.25,
    outliers = FALSE,
    color = "black",
    fill = "white",
    linewidth = 0.3
  ) +
  scale_x_discrete(
    labels = function(x) str_remove(x, pattern = "CAF-")
  ) +
  facet_wrap(
    . ~ sample,
    ncol = 3,
    scales = "free_y",
    axes = "all"
  ) +
  scale_fill_manual(
    values = caf_subcluster_colors_number_named,
    guide = "none"
  ) +
  labs(
    x = NULL,
    y = "Local non-CAF-derived Winter hypoxia score"
  ) +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black"),
    axis.title.y = element_text(color = "black"),
    strip.text = element_text(color = "black"),
    strip.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.border = element_rect(fill = "transparent", color = "black"),
    panel.grid = element_blank(),
    axis.line = element_blank()
  )

## Save output ---------------------------------------------------------------

ggsave(
  plot = plot_local_hypoxia_violin,
  filename = file.path(
    hypoxia_score_violin_figure_dir,
    "caf_subcluster_local_non_caf_winter_hypoxia_score_violin.pdf"
  ),
  width = 9,
  height = 6,
  bg = figure_bg
)
