# Hypoxia mapping polygon-based CAF distribution maps
#
# This script generates polygon-based CAF distribution maps for the hypoxia
# mapping analysis using Xenium cell boundaries. For each Xenium sample, it
# outputs a full-tissue view with hypoxic and normoxic ROI boxes and magnified
# views of both ROIs. Maps are generated in two visualization modes: all CAFs
# shown in a single CAF color and CAFs colored by CAF subcluster.
#
# To keep sample orientation consistent with the point-based maps generated by
# 08_03_03_hypoxia_mapping_caf_distribution_point.R, samples wider than tall
# are rotated by exchanging the x and y coordinates.
#
# Input tables are generated by:
#   01_04_supplementary_tables.R
#   02_01_caf_extraction_and_subclustering.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(arrow)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define input and output paths ---------------------------------------------

hypoxia_mapping_caf_distribution_polygon_dir <- file.path(
  hypoxia_mapping_figure_dir,
  "08_03_04_hypoxia_mapping_caf_distribution_polygon"
)

fs::dir_create(hypoxia_mapping_caf_distribution_polygon_dir)


## Check required settings ---------------------------------------------------

required_objects <- c(
  "roi_side_length_um",
  "hypoxia_roi_coordinates",
  "normoxia_roi_coordinates",
  "hypoxia_roi_color",
  "normoxia_roi_color",
  "all_caf_color",
  "caf_subcluster_display_order",
  "caf_subcluster_colors_label_named",
  "xenium_sample_id_by_tx_number",
  "xenium_raw_folder_by_tx_id"
)

missing_objects <- required_objects[!vapply(required_objects, exists, logical(1))]

if (length(missing_objects) > 0) {
  stop(
    "The following required objects were not found in config files:\n",
    paste(missing_objects, collapse = "\n"),
    call. = FALSE
  )
}


## Read metadata -------------------------------------------------------------

if (!file.exists(initial_metadata_file)) {
  stop(
    "Initial clustering metadata file was not found: ",
    initial_metadata_file,
    call. = FALSE
  )
}

if (!file.exists(caf_subcluster_metadata_file)) {
  stop(
    "CAF subclustering metadata file was not found: ",
    caf_subcluster_metadata_file,
    call. = FALSE
  )
}

initial_metadata_df <- readr::read_csv(
  initial_metadata_file,
  show_col_types = FALSE
) %>%
  dplyr::mutate(
    cell_id_no_prefix = stringr::str_remove(
      cell_id,
      pattern = "^Xenium_[0-9]+_"
    )
  )

caf_metadata_df <- readr::read_csv(
  caf_subcluster_metadata_file,
  show_col_types = FALSE
) %>%
  dplyr::mutate(
    caf_subcluster = factor(
      caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    cell_id_no_prefix = stringr::str_remove(
      cell_id,
      pattern = "^Xenium_[0-9]+_"
    )
  )

stopifnot(!any(is.na(caf_metadata_df$caf_subcluster)))


## Prepare colors ------------------------------------------------------------

caf_subcluster_colors_for_plot <- caf_subcluster_colors_label_named[
  caf_subcluster_display_order
]

stopifnot(!any(is.na(caf_subcluster_colors_for_plot)))


## Helper functions ----------------------------------------------------------

calculate_image_size <- function(range_x, range_y, base_size = 10) {
  length_x <- diff(range_x)
  length_y <- diff(range_y)

  if (length_y >= length_x) {
    c(width = base_size, height = base_size * length_y / length_x)
  } else {
    c(width = base_size * length_x / length_y, height = base_size)
  }
}

prepare_plot_coordinates <- function(
    caf_boundary_df,
    sample_initial_metadata_df,
    tx_number
) {
  range_x_original <- range(sample_initial_metadata_df$x, na.rm = TRUE)
  range_y_original <- range(sample_initial_metadata_df$y, na.rm = TRUE)
  length_x <- diff(range_x_original)
  length_y <- diff(range_y_original)
  rotate_coordinates <- length_x > length_y

  hypoxia_xy <- hypoxia_roi_coordinates[[tx_number]]
  normoxia_xy <- normoxia_roi_coordinates[[tx_number]]

  if (is.null(hypoxia_xy)) {
    stop(
      "No hypoxia ROI coordinate was defined for TX number: ",
      tx_number,
      call. = FALSE
    )
  }

  if (is.null(normoxia_xy)) {
    stop(
      "No normoxia ROI coordinate was defined for TX number: ",
      tx_number,
      call. = FALSE
    )
  }

  if (rotate_coordinates) {
    caf_boundary_df <- caf_boundary_df %>%
      dplyr::mutate(
        plot_x = .data$vertex_y,
        plot_y = .data$vertex_x
      )

    range_x <- range_y_original
    range_y <- range_x_original
    hypoxia_xy <- rev(hypoxia_xy)
    normoxia_xy <- rev(normoxia_xy)
    reverse_y_axis <- FALSE
  } else {
    caf_boundary_df <- caf_boundary_df %>%
      dplyr::mutate(
        plot_x = .data$vertex_x,
        plot_y = .data$vertex_y
      )

    range_x <- range_x_original
    range_y <- range_y_original
    reverse_y_axis <- TRUE
  }

  list(
    caf_boundary_df = caf_boundary_df,
    range_x = range_x,
    range_y = range_y,
    hypoxia_xy = hypoxia_xy,
    normoxia_xy = normoxia_xy,
    reverse_y_axis = reverse_y_axis
  )
}

add_scale_bar_to_full_view <- function(plot, range_x, range_y, reverse_y_axis) {
  length_x <- diff(range_x)
  length_y <- diff(range_y)
  scale_bar_length_um <- 1000

  scale_bar_x_end <- range_x[2] - length_x * 0.05
  scale_bar_x_start <- scale_bar_x_end - scale_bar_length_um

  scale_bar_y <- if (reverse_y_axis) {
    range_y[2] - length_y * 0.05
  } else {
    range_y[1] + length_y * 0.05
  }

  plot +
    annotate(
      "segment",
      x = scale_bar_x_start - 20,
      xend = scale_bar_x_end + 20,
      y = scale_bar_y,
      yend = scale_bar_y,
      color = "white",
      linewidth = 7
    ) +
    annotate(
      "segment",
      x = scale_bar_x_start,
      xend = scale_bar_x_end,
      y = scale_bar_y,
      yend = scale_bar_y,
      color = "black",
      linewidth = 4
    )
}

add_scale_bar_to_roi <- function(plot, roi_xy, reverse_y_axis) {
  scale_bar_length_um <- 100
  scale_bar_x_start <- roi_xy[1] + roi_side_length_um * 0.70
  scale_bar_x_end <- scale_bar_x_start + scale_bar_length_um

  scale_bar_y <- if (reverse_y_axis) {
    roi_xy[2] + roi_side_length_um * 0.95
  } else {
    roi_xy[2] + roi_side_length_um * 0.05
  }

  plot +
    annotate(
      "segment",
      x = scale_bar_x_start - 2,
      xend = scale_bar_x_end + 2,
      y = scale_bar_y,
      yend = scale_bar_y,
      color = "white",
      linewidth = 6
    ) +
    annotate(
      "segment",
      x = scale_bar_x_start,
      xend = scale_bar_x_end,
      y = scale_bar_y,
      yend = scale_bar_y,
      color = "black",
      linewidth = 4
    )
}

add_roi_boxes <- function(plot, hypoxia_xy, normoxia_xy) {
  plot +
    annotate(
      "rect",
      xmin = hypoxia_xy[1],
      xmax = hypoxia_xy[1] + roi_side_length_um,
      ymin = hypoxia_xy[2],
      ymax = hypoxia_xy[2] + roi_side_length_um,
      color = "white",
      fill = NA,
      linewidth = 2.8
    ) +
    annotate(
      "rect",
      xmin = hypoxia_xy[1],
      xmax = hypoxia_xy[1] + roi_side_length_um,
      ymin = hypoxia_xy[2],
      ymax = hypoxia_xy[2] + roi_side_length_um,
      color = hypoxia_roi_color,
      fill = NA,
      linewidth = 2.1
    ) +
    annotate(
      "rect",
      xmin = normoxia_xy[1],
      xmax = normoxia_xy[1] + roi_side_length_um,
      ymin = normoxia_xy[2],
      ymax = normoxia_xy[2] + roi_side_length_um,
      color = "white",
      fill = NA,
      linewidth = 2.8
    ) +
    annotate(
      "rect",
      xmin = normoxia_xy[1],
      xmax = normoxia_xy[1] + roi_side_length_um,
      ymin = normoxia_xy[2],
      ymax = normoxia_xy[2] + roi_side_length_um,
      color = normoxia_roi_color,
      fill = NA,
      linewidth = 2.1
    )
}

make_caf_distribution_plot <- function(
    caf_boundary_df,
    range_x,
    range_y,
    reverse_y_axis,
    color_mode = c("green", "subcluster"),
    xlim = range_x,
    ylim = range_y
) {
  color_mode <- match.arg(color_mode)

  if (color_mode == "green") {
    plot <- ggplot(
      caf_boundary_df,
      aes(
        x = .data$plot_x,
        y = .data$plot_y,
        group = .data$cell_id
      )
    ) +
      geom_polygon(
        fill = all_caf_color,
        color = NA,
        alpha = 1
      )
  } else {
    plot <- ggplot(
      caf_boundary_df,
      aes(
        x = .data$plot_x,
        y = .data$plot_y,
        group = .data$cell_id,
        fill = .data$caf_subcluster
      )
    ) +
      geom_polygon(
        color = NA,
        alpha = 1
      ) +
      scale_fill_manual(
        values = caf_subcluster_colors_for_plot,
        guide = "none"
      )
  }

  if (reverse_y_axis) {
    plot <- plot +
      scale_y_reverse(expand = expansion(mult = c(0, 0)))
  } else {
    plot <- plot +
      scale_y_continuous(expand = expansion(mult = c(0, 0)))
  }

  plot +
    scale_x_continuous(expand = expansion(mult = c(0, 0))) +
    coord_cartesian(
      xlim = xlim,
      ylim = ylim,
      ratio = 1
    ) +
    labs(x = NULL, y = NULL) +
    theme(
      legend.position = "none",
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "black", color = NA),
      panel.border = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank()
    )
}

save_caf_distribution_outputs <- function(
    base_data,
    color_mode,
    color_label,
    xenium_sample_id
) {
  sample_label <- stringr::str_to_lower(xenium_sample_id)
  image_size <- calculate_image_size(
    range_x = base_data$range_x,
    range_y = base_data$range_y
  )

  full_view_plot <- make_caf_distribution_plot(
    caf_boundary_df = base_data$caf_boundary_df,
    range_x = base_data$range_x,
    range_y = base_data$range_y,
    reverse_y_axis = base_data$reverse_y_axis,
    color_mode = color_mode
  )

  full_view_plot <- full_view_plot %>%
    add_roi_boxes(
      hypoxia_xy = base_data$hypoxia_xy,
      normoxia_xy = base_data$normoxia_xy
    ) %>%
    add_scale_bar_to_full_view(
      range_x = base_data$range_x,
      range_y = base_data$range_y,
      reverse_y_axis = base_data$reverse_y_axis
    )

  hypoxic_roi_plot <- make_caf_distribution_plot(
    caf_boundary_df = base_data$caf_boundary_df,
    range_x = base_data$range_x,
    range_y = base_data$range_y,
    reverse_y_axis = base_data$reverse_y_axis,
    color_mode = color_mode,
    xlim = c(
      base_data$hypoxia_xy[1],
      base_data$hypoxia_xy[1] + roi_side_length_um
    ),
    ylim = c(
      base_data$hypoxia_xy[2],
      base_data$hypoxia_xy[2] + roi_side_length_um
    )
  ) %>%
    add_scale_bar_to_roi(
      roi_xy = base_data$hypoxia_xy,
      reverse_y_axis = base_data$reverse_y_axis
    )

  normoxic_roi_plot <- make_caf_distribution_plot(
    caf_boundary_df = base_data$caf_boundary_df,
    range_x = base_data$range_x,
    range_y = base_data$range_y,
    reverse_y_axis = base_data$reverse_y_axis,
    color_mode = color_mode,
    xlim = c(
      base_data$normoxia_xy[1],
      base_data$normoxia_xy[1] + roi_side_length_um
    ),
    ylim = c(
      base_data$normoxia_xy[2],
      base_data$normoxia_xy[2] + roi_side_length_um
    )
  ) %>%
    add_scale_bar_to_roi(
      roi_xy = base_data$normoxia_xy,
      reverse_y_axis = base_data$reverse_y_axis
    )

  ggsave(
    plot = full_view_plot,
    filename = file.path(
      hypoxia_mapping_caf_distribution_polygon_dir,
      paste0(
        "hypoxia_mapping_caf_distribution_polygon_",
        color_label,
        "_full_view_with_roi_boxes_",
        sample_label,
        ".png"
      )
    ),
    width = image_size[["width"]],
    height = image_size[["height"]],
    dpi = figure_dpi,
    bg = figure_bg,
    limitsize = FALSE
  )

  ggsave(
    plot = hypoxic_roi_plot,
    filename = file.path(
      hypoxia_mapping_caf_distribution_polygon_dir,
      paste0(
        "hypoxia_mapping_caf_distribution_polygon_",
        color_label,
        "_hypoxic_roi_",
        sample_label,
        ".png"
      )
    ),
    width = 4,
    height = 4,
    dpi = figure_dpi,
    bg = figure_bg
  )

  ggsave(
    plot = normoxic_roi_plot,
    filename = file.path(
      hypoxia_mapping_caf_distribution_polygon_dir,
      paste0(
        "hypoxia_mapping_caf_distribution_polygon_",
        color_label,
        "_normoxic_roi_",
        sample_label,
        ".png"
      )
    ),
    width = 4,
    height = 4,
    dpi = figure_dpi,
    bg = figure_bg
  )
}


## Generate CAF distribution maps -------------------------------------------

for (tx_number_i in names(xenium_sample_id_by_tx_number)) {
  tx_id_i <- paste0("TX5K_", tx_number_i)
  xenium_sample_id_i <- xenium_sample_id_by_tx_number[[tx_number_i]]

  message(
    "Generating polygon-based CAF distribution maps for ",
    xenium_sample_id_i,
    " (",
    tx_id_i,
    ")"
  )

  xenium_raw_folder_i <- xenium_raw_folder_by_tx_id[[tx_id_i]]

  if (is.null(xenium_raw_folder_i)) {
    stop("No Xenium raw folder was defined for ", tx_id_i, call. = FALSE)
  }

  xenium_raw_dir_i <- file.path(
    xenium_raw_data_dir,
    xenium_raw_folder_i
  )

  cell_boundary_file_i <- file.path(
    xenium_raw_dir_i,
    "cell_boundaries.parquet"
  )

  if (!file.exists(cell_boundary_file_i)) {
    stop(
      "cell_boundaries.parquet was not found: ",
      cell_boundary_file_i,
      call. = FALSE
    )
  }

  sample_initial_metadata_df <- initial_metadata_df %>%
    dplyr::filter(.data$tx_id == tx_id_i)

  sample_caf_metadata_df <- caf_metadata_df %>%
    dplyr::filter(.data$tx_id == tx_id_i)

  if (nrow(sample_initial_metadata_df) == 0) {
    stop("No initial metadata cells were found for ", tx_id_i, call. = FALSE)
  }

  if (nrow(sample_caf_metadata_df) == 0) {
    stop("No CAF metadata cells were found for ", tx_id_i, call. = FALSE)
  }

  # Retain cell boundaries corresponding to CAFs and attach CAF subcluster labels.
  cell_boundary_df <- arrow::read_parquet(cell_boundary_file_i)

  caf_boundary_df <- cell_boundary_df %>%
    dplyr::inner_join(
      sample_caf_metadata_df %>%
        dplyr::select(
          cell_id_no_prefix,
          caf_subcluster
        ),
      by = c("cell_id" = "cell_id_no_prefix")
    )

  base_data <- prepare_plot_coordinates(
    caf_boundary_df = caf_boundary_df,
    sample_initial_metadata_df = sample_initial_metadata_df,
    tx_number = tx_number_i
  )

  save_caf_distribution_outputs(
    base_data = base_data,
    color_mode = "green",
    color_label = "green_caf",
    xenium_sample_id = xenium_sample_id_i
  )

  save_caf_distribution_outputs(
    base_data = base_data,
    color_mode = "subcluster",
    color_label = "caf_subcluster_colored",
    xenium_sample_id = xenium_sample_id_i
  )
}
