# Hypoxia mapping spatial heatmap
#
# This script generates sample-wise spatial heatmaps of local non-CAF-derived
# Winter hypoxia scores and overlays CAF-8 cells. Hypoxic and normoxic ROI boxes
# are added for the full-view figure panels.
#
# Input tables are generated by:
#   03_01_hypoxia_mapping_prepare_hypoxia_ssgsea_scores.R
#   03_02_hypoxia_mapping_calculate_grid_non_caf_hypoxia_scores.R

## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(cowplot)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_06_color_palettes.R"))


## Define input and output directories ---------------------------------------

hypoxia_mapping_table_dir <- file.path(
  xenium_table_dir,
  "hypoxia_mapping"
)

hypoxia_mapping_spatial_heatmap_dir <- file.path(
  hypoxia_mapping_figure_dir,
  "08_03_01_hypoxia_mapping_spatial_heatmaps"
)

fs::dir_create(hypoxia_mapping_spatial_heatmap_dir)


## Define plotting parameters ------------------------------------------------

overlay_caf_subcluster <- proliferating_caf_subcluster
hypoxia_map_colors <- c(
  "#bd0026", "#f03b20", "#fd8d3c", "#fecc5c", "gray95",
  "#a1dab4", "#41b6c4", "#2c7fb8", "#253494"
)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))
  
  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  
  invisible(NULL)
}

calculate_plot_size <- function(range_x, range_y, scaling = 500) {
  c(
    width = diff(range_x) / scaling,
    height = diff(range_y) / scaling
  )
}

add_hypoxia_normoxia_roi_rectangles <- function(plot, tx_number) {
  if (is.null(hypoxia_roi_coordinates[[tx_number]])) {
    stop(
      "No hypoxia ROI coordinate was defined for TX number: ",
      tx_number,
      call. = FALSE
    )
  }
  
  if (is.null(normoxia_roi_coordinates[[tx_number]])) {
    stop(
      "No normoxia ROI coordinate was defined for TX number: ",
      tx_number,
      call. = FALSE
    )
  }
  
  hypoxia_xy <- hypoxia_roi_coordinates[[tx_number]]
  normoxia_xy <- normoxia_roi_coordinates[[tx_number]]
  
  plot +
    annotate(
      "rect",
      xmin = hypoxia_xy[1],
      xmax = hypoxia_xy[1] + roi_side_length_um,
      ymin = hypoxia_xy[2],
      ymax = hypoxia_xy[2] + roi_side_length_um,
      color = "black",
      fill = NA,
      linewidth = 4
    ) +
    annotate(
      "rect",
      xmin = hypoxia_xy[1],
      xmax = hypoxia_xy[1] + roi_side_length_um,
      ymin = hypoxia_xy[2],
      ymax = hypoxia_xy[2] + roi_side_length_um,
      color = hypoxia_roi_color,
      fill = NA,
      linewidth = 3
    ) +
    annotate(
      "rect",
      xmin = normoxia_xy[1],
      xmax = normoxia_xy[1] + roi_side_length_um,
      ymin = normoxia_xy[2],
      ymax = normoxia_xy[2] + roi_side_length_um,
      color = "black",
      fill = NA,
      linewidth = 4
    ) +
    annotate(
      "rect",
      xmin = normoxia_xy[1],
      xmax = normoxia_xy[1] + roi_side_length_um,
      ymin = normoxia_xy[2],
      ymax = normoxia_xy[2] + roi_side_length_um,
      color = normoxia_roi_color,
      fill = NA,
      linewidth = 3
    )
}

make_hypoxia_heatmap <- function(grid_table, cell_table, xenium_sample_id) {
  range_x <- range(cell_table$X, na.rm = TRUE)
  range_y <- range(cell_table$Y, na.rm = TRUE)
  
  max_abs_score <- max(abs(grid_table$mean_Winter_z_celltype), na.rm = TRUE)
  
  if (!is.finite(max_abs_score) || max_abs_score == 0) {
    max_abs_score <- 1
  }
  
  ggplot() +
    geom_tile(
      data = grid_table,
      aes(
        x = .data$GridX_center_um,
        y = .data$GridY_center_um,
        fill = .data$mean_Winter_z_celltype
      ),
      width = grid_length_um,
      height = grid_length_um,
      color = "gray60"
    ) +
    geom_point(
      data = cell_table %>%
        dplyr::filter(.data$SubClust == overlay_caf_subcluster),
      aes(x = .data$X, y = .data$Y),
      color = "black",
      fill = NA,
      shape = 21,
      size = 3.0,
      stroke = 1.5
    ) +
    scale_x_continuous(
      expand = expansion(mult = c(0, 0))
    ) +
    scale_y_reverse(
      expand = expansion(mult = c(0, 0))
    ) +
    scale_fill_gradientn(
      colors = hypoxia_map_colors,
      limits = c(-max_abs_score, max_abs_score),
      na.value = "gray80",
      guide = guide_colorbar(
        title.hjust = 0.5,
        title.vjust = 0.5,
        frame.colour = "black",
        ticks.colour = "black"
      )
    ) +
    labs(
      subtitle = paste0(
        "Local mean of non-CAF-derived Winter hypoxia score\n",
        xenium_sample_id,
        ", ",
        overlay_caf_subcluster
      ),
      x = NULL,
      y = NULL,
      fill = NULL
    ) +
    coord_cartesian(
      xlim = range_x,
      ylim = range_y,
      ratio = 1
    ) +
    theme_classic() +
    theme(
      legend.background = element_rect(fill = "transparent", color = NA),
      axis.text = element_text(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.line = element_blank(),
      legend.text = element_text(color = "black"),
      plot.subtitle = element_text(size = 20, color = "black"),
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.border = element_rect(fill = NA, color = "black")
    )
}


## Generate spatial hypoxia panels ------------------------------------------

for (tx_number_i in tx_number_merge_order) {
  xenium_sample_id_i <- xenium_sample_id_by_tx_number[[tx_number_i]]
  
  if (is.null(xenium_sample_id_i)) {
    stop(
      "No Xenium sample ID was defined for TX number: ",
      tx_number_i,
      call. = FALSE
    )
  }
  
  message("Generating hypoxia mapping spatial panels for ", xenium_sample_id_i)
  
  cell_hypoxia_table <- read_required_csv(
    file.path(
      hypoxia_mapping_table_dir,
      paste0(
        "winter_hypoxia_ssgsea_scores_",
        stringr::str_to_lower(xenium_sample_id_i),
        ".csv"
      )
    ),
    paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
  )
  
  grid_hypoxia_table <- read_required_csv(
    file.path(
      hypoxia_mapping_table_dir,
      paste0(
        "grid_non_caf_winter_hypoxia_scores_",
        stringr::str_to_lower(xenium_sample_id_i),
        ".csv"
      )
    ),
    paste0("Grid-level non-CAF hypoxia score table for ", xenium_sample_id_i)
  )
  
  check_required_columns(
    cell_hypoxia_table,
    c("X", "Y", "SubClust"),
    paste0("Winter hypoxia ssGSEA score table for ", xenium_sample_id_i)
  )
  
  check_required_columns(
    grid_hypoxia_table,
    c(
      "GridX_center_um",
      "GridY_center_um",
      "mean_Winter_z_celltype"
    ),
    paste0("Grid-level non-CAF hypoxia score table for ", xenium_sample_id_i)
  )
  
  cell_hypoxia_table <- cell_hypoxia_table %>%
    dplyr::mutate(
      X = as.numeric(.data$X),
      Y = as.numeric(.data$Y),
      SubClust = as.character(.data$SubClust)
    )
  
  grid_hypoxia_table <- grid_hypoxia_table %>%
    dplyr::mutate(
      GridX_center_um = as.numeric(.data$GridX_center_um),
      GridY_center_um = as.numeric(.data$GridY_center_um),
      mean_Winter_z_celltype = as.numeric(.data$mean_Winter_z_celltype)
    )
  
  range_x <- range(cell_hypoxia_table$X, na.rm = TRUE)
  range_y <- range(cell_hypoxia_table$Y, na.rm = TRUE)
  whole_panel_size <- calculate_plot_size(
    range_x = range_x,
    range_y = range_y,
    scaling = 500
  )
  
  hypoxia_heatmap <- make_hypoxia_heatmap(
    grid_table = grid_hypoxia_table,
    cell_table = cell_hypoxia_table,
    xenium_sample_id = xenium_sample_id_i
  )
  
  hypoxia_heatmap_full_view_with_roi_boxes <- add_hypoxia_normoxia_roi_rectangles(
    plot = hypoxia_heatmap,
    tx_number = tx_number_i
  ) +
    theme(
      plot.title = element_blank(),
      plot.subtitle = element_blank(),
      plot.caption = element_blank(),
      plot.margin = margin(0, 0, 0, 0),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      legend.position = "none"
    )
  
  hypoxia_heatmap_for_legend <- hypoxia_heatmap +
    labs(fill = NULL) +
    theme(
      plot.margin = margin(0, 0, 0, 0),
      legend.box.margin = margin(0, 0, 0, 0)
    )
  
  output_sample_label <- stringr::str_to_lower(xenium_sample_id_i)
  
  ggsave(
    plot = hypoxia_heatmap,
    filename = file.path(
      hypoxia_mapping_spatial_heatmap_dir,
      paste0(
        "hypoxia_mapping_winter_heatmap_with_caf8_overlay_",
        output_sample_label,
        ".pdf"
      )
    ),
    width = whole_panel_size[["width"]],
    height = whole_panel_size[["height"]],
    bg = figure_bg
  )
  
  ggsave(
    plot = hypoxia_heatmap_full_view_with_roi_boxes,
    filename = file.path(
      hypoxia_mapping_spatial_heatmap_dir,
      paste0(
        "hypoxia_mapping_winter_heatmap_with_caf8_overlay_full_view_with_roi_boxes_",
        output_sample_label,
        ".pdf"
      )
    ),
    width = whole_panel_size[["width"]],
    height = whole_panel_size[["height"]],
    bg = figure_bg
  )
  
  ggsave(
    plot = cowplot::get_legend(hypoxia_heatmap_for_legend),
    filename = file.path(
      hypoxia_mapping_spatial_heatmap_dir,
      paste0(
        "hypoxia_mapping_winter_heatmap_legend_",
        output_sample_label,
        ".pdf"
      )
    ),
    width = 1,
    height = 3,
    bg = figure_bg
  )
}

message(
  "Saved hypoxia mapping spatial panels to: ",
  hypoxia_mapping_spatial_heatmap_dir
)
