# Plot volcano plots for bulk RNA-seq differential expression results
#
# This script loads the differential expression results generated by
# 07_03_bulk_rnaseq_differential_expression.R and creates the volcano plots
# used for the manuscript figure.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(ggrepel)
  library(patchwork)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_01_analysis_parameters.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))


## Define input and output paths ---------------------------------------------

bulk_rnaseq_differential_expression_results_file <- file.path(
  bulk_rnaseq_object_dir,
  "bulk_rnaseq_differential_expression_results.rds"
)

bulk_rnaseq_volcano_figure_dir <- file.path(
  bulk_rnaseq_figure_dir,
  "08_07_03_bulk_rnaseq_volcano_figures"
)

bulk_rnaseq_volcano_figure_file <- file.path(
  bulk_rnaseq_volcano_figure_dir,
  "bulk_rnaseq_volcano.pdf"
)

bulk_rnaseq_volcano_labelled_gene_table_file <- file.path(
  bulk_rnaseq_volcano_figure_dir,
  "bulk_rnaseq_volcano_labelled_genes.csv"
)

fs::dir_create(bulk_rnaseq_volcano_figure_dir)


## Define plot settings ------------------------------------------------------

volcano_comparison_settings <- tibble::tribble(
  ~comparison_name, ~comparison_label,
  "comparison_1_hypocaf_hypoxia_vs_normocaf_normoxia", "Original",
  "comparison_2_hypocaf_normoxia_vs_normocaf_normoxia", "Under21",
  "comparison_3_hypocaf_hypoxia_vs_normocaf_hypoxia", "Under1"
)

labelled_genes <- c(
  "TOP2A",
  "ANLN",
  "MYBL2",
  "BIRC5",
  "LMNB1",
  "CDKN2A",
  "CDKN1A"
)

log2_fold_change_threshold <- 1
fdr_threshold <- 0.05

non_significant_point_color <- "gray"
positive_point_fill <- "#2c7fb8"
negative_point_fill <- "#f03b20"

point_size <- 2
point_stroke <- 0.1
threshold_line_width <- 0.2

label_nudge_y_left <- 0.6
label_nudge_y_right <- 2.0
label_nudge_x_right <- 2.5
label_nudge_x_left <- 6
label_force <- 8
label_box_padding <- 0.6
label_point_padding <- 0
label_seed <- 1

figure_width <- 6
figure_height <- 5/3
panel_width <-  3.0
panel_height <-  1.17


## Load differential expression results -------------------------------------

if (!file.exists(bulk_rnaseq_differential_expression_results_file)) {
  stop(
    "Bulk RNA-seq differential expression results not found: ",
    bulk_rnaseq_differential_expression_results_file,
    call. = FALSE
  )
}

bulk_rnaseq_differential_expression_results <- readRDS(
  bulk_rnaseq_differential_expression_results_file
)

missing_comparisons <- setdiff(
  volcano_comparison_settings$comparison_name,
  names(bulk_rnaseq_differential_expression_results)
)

if (length(missing_comparisons) > 0) {
  stop(
    "Differential expression results are missing required comparisons: ",
    paste(missing_comparisons, collapse = ", "),
    call. = FALSE
  )
}


## Prepare volcano plot data -------------------------------------------------

required_differential_expression_columns <- c(
  "gene_symbol",
  "logFC",
  "FDR"
)

volcano_plot_table <- purrr::map_dfr(
  volcano_comparison_settings$comparison_name,
  function(current_comparison_name) {
    differential_expression_table <-
      bulk_rnaseq_differential_expression_results[[
        current_comparison_name
      ]]$differential_expression_table
    
    missing_differential_expression_columns <- setdiff(
      required_differential_expression_columns,
      colnames(differential_expression_table)
    )
    
    if (length(missing_differential_expression_columns) > 0) {
      stop(
        "Differential expression table for ",
        current_comparison_name,
        " is missing required columns: ",
        paste(
          missing_differential_expression_columns,
          collapse = ", "
        ),
        call. = FALSE
      )
    }
    
    comparison_label <- volcano_comparison_settings |>
      dplyr::filter(
        .data$comparison_name == .env$current_comparison_name
      ) |>
      dplyr::pull(.data$comparison_label)
    
    differential_expression_table |>
      dplyr::transmute(
        comparison_name = .env$current_comparison_name,
        comparison_label = .env$comparison_label,
        gene_symbol = .data$gene_symbol,
        logFC = .data$logFC,
        FDR = .data$FDR
      )
  }
)

if (
  anyNA(volcano_plot_table[, c("gene_symbol", "logFC", "FDR")]) ||
  any(!is.finite(volcano_plot_table$logFC)) ||
  any(!is.finite(volcano_plot_table$FDR)) ||
  any(volcano_plot_table$FDR < 0) ||
  any(volcano_plot_table$FDR > 1)
) {
  stop(
    "Volcano plot table contains missing or invalid logFC/FDR values.",
    call. = FALSE
  )
}

# Replace exact zero FDR values only for the logarithmic transformation.
minimum_positive_fdr <- min(
  volcano_plot_table$FDR[volcano_plot_table$FDR > 0],
  na.rm = TRUE
)

if (!is.finite(minimum_positive_fdr)) {
  stop(
    "No positive FDR values were found in the volcano plot data.",
    call. = FALSE
  )
}

volcano_plot_table <- volcano_plot_table |>
  dplyr::mutate(
    fdr_for_plot = dplyr::if_else(
      .data$FDR == 0,
      minimum_positive_fdr,
      .data$FDR
    ),
    minus_log10_fdr = -log10(.data$fdr_for_plot),
    significance = dplyr::case_when(
      .data$logFC > log2_fold_change_threshold &
        .data$FDR < fdr_threshold ~ "positive",
      .data$logFC < -log2_fold_change_threshold &
        .data$FDR < fdr_threshold ~ "negative",
      TRUE ~ "not_significant"
    ),
    significance = factor(
      .data$significance,
      levels = c(
        "not_significant",
        "negative",
        "positive"
      )
    )
  )

minimum_fdr <- min(volcano_plot_table$fdr_for_plot)
maximum_absolute_log2_fold_change <- max(
  abs(volcano_plot_table$logFC)
)

labelled_gene_table <- volcano_plot_table |>
  dplyr::filter(.data$gene_symbol %in% labelled_genes)

missing_labelled_genes <- setdiff(
  labelled_genes,
  unique(labelled_gene_table$gene_symbol)
)

if (length(missing_labelled_genes) > 0) {
  warning(
    "The following labelled genes were not found in the selected comparisons: ",
    paste(missing_labelled_genes, collapse = ", "),
    call. = FALSE
  )
}


## Define volcano plot function ---------------------------------------------

make_bulk_rnaseq_volcano <- function(
    comparison_number,
    comparison_label,
    show_gene_labels = TRUE
) {
  comparison_plot_table <- volcano_plot_table |>
    dplyr::filter(
      .data$comparison_label == .env$comparison_label
    ) |>
    dplyr::arrange(.data$significance)
  
  comparison_labelled_gene_table <- labelled_gene_table |>
    dplyr::filter(
      .data$comparison_label == .env$comparison_label
    )

  gene_label_color <- if (show_gene_labels) "black" else NA_character_
  
  common_hline <- geom_hline(
    yintercept = -log10(fdr_threshold),
    color = "black",
    linetype = "dashed",
    linewidth = threshold_line_width
  )
  
   common_vline <-  geom_vline(
      xintercept = c(
        -log2_fold_change_threshold,
        log2_fold_change_threshold
      ),
      color = "black",
      linetype = "dashed",
      linewidth = threshold_line_width
    )
  
  common_scale_x <- scale_x_continuous(
    breaks = c(-5, -1, 1, 5)
  )
  
  common_scale_y <- scale_y_continuous(
    expand = expansion(mult = c(0, 0.03)),
    limits = c(0, -1.1 * log10(minimum_fdr)),
    breaks = c(0, 5, 10, 15)
  )
  
  common_scale_color_manual <- scale_color_manual(
    values = c(
      "positive" = "black",
      "negative" = "black",
      "not_significant" = non_significant_point_color
    )
  ) 
  
  common_scale_fill_manual <- scale_fill_manual(
    values = c(
      "positive" = positive_point_fill,
      "negative" = negative_point_fill,
      "not_significant" = non_significant_point_color
    )
  )
    
  common_theme <-
    theme(
      aspect.ratio = 0.39,
      plot.margin = margin(4, 22, 4, 22),
      legend.position = "none",
      axis.text.x = element_text(
        face = "plain",
        color = "black"
      ),
      axis.text.y = element_text(
        face = "plain",
        color = "black"
      ),
      axis.title = element_text(
        face = "plain",
        color = "black"
      ),
      plot.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      panel.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      panel.grid = element_blank(),
      panel.border = element_rect(
        fill = NA,
        color = "black"
      )
    )
  
  common_cartesian <- coord_cartesian(
    xlim = c(
      -maximum_absolute_log2_fold_change,
      maximum_absolute_log2_fold_change
    ),
    clip = "off"
  ) 
  
  volcano_plot_point_pdf <- 
    ggplot(
      comparison_plot_table,
      aes(
        x = .data$logFC,
        y = .data$minus_log10_fdr
      )
    ) +
    ggrastr::rasterise(
      geom_point(
        aes(
          fill = .data$significance,
          color = .data$significance
        ),
        shape = 21,
        size = point_size,
        stroke = point_stroke
      ),
      dpi = figure_dpi,
      dev = "ragg"
    ) +
    common_hline +
    common_vline +
    labs(
      x = "log2 fold change",
      y = paste0(
        comparison_label,
        "\n\n−log10(FDR)"
      )
    ) +
    common_scale_x +
    common_scale_y +
    common_scale_color_manual +
    common_scale_fill_manual +
    common_cartesian +
    common_theme
  
  volcano_plot_only_label_pdf <- 
    ggplot(
      comparison_plot_table,
      aes(
        x = .data$logFC,
        y = .data$minus_log10_fdr
      )
    ) +
    common_hline +
    common_vline +
    ggrepel::geom_text_repel(
      data = comparison_labelled_gene_table |>
        dplyr::filter(.data$logFC > 0),
      aes(label = .data$gene_symbol),
      color = "black",
      segment.color = "black",
      nudge_y = label_nudge_y_right,
      nudge_x = label_nudge_x_right,
      force = label_force,
      force_pull = 0,
      direction = "both",
      xlim = c(3.5, Inf),
      hjust = 0,
      box.padding = label_box_padding,
      point.padding = label_point_padding,
      fontface = "plain",
      max.overlaps = 100,
      seed = label_seed
    ) +
    ggrepel::geom_text_repel(
      data = comparison_labelled_gene_table |>
        dplyr::filter(.data$logFC < 0),
      aes(label = .data$gene_symbol),
      color = "black",
      segment.color = "black",
      nudge_y = label_nudge_y_left,
      nudge_x = -label_nudge_x_left,
      force = label_force,
      force_pull = 0,
      direction = "y",
      xlim = c(-Inf, -1.2),
      box.padding = label_box_padding,
      point.padding = label_point_padding,
      fontface = "plain",
      max.overlaps = 100,
      seed = label_seed
    ) +
    labs(
      x = "log2 fold change",
      y = paste0(
        comparison_label,
        "\n\n−log10(FDR)"
      )
    ) +
    common_scale_x +
    common_scale_y +
    common_cartesian +
    common_theme
  
  volcano_plot_panel_png <- 
    ggplot(
      comparison_plot_table,
      aes(
        x = .data$logFC,
        y = .data$minus_log10_fdr
      )
    ) +
    geom_point(
        aes(
          fill = .data$significance,
          color = .data$significance
        ),
        shape = 21,
        size = point_size,
        stroke = point_stroke
      ) +
    common_hline +
    common_vline +
    common_scale_x +
    common_scale_y +
    common_scale_color_manual +
    common_scale_fill_manual +
    common_cartesian +
    theme(
      aspect.ratio = 0.39,
      plot.margin = margin(0, 0, 0, 0),
      legend.position = "none",
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.title = element_blank(),
      plot.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      panel.background = element_rect(
        fill = "transparent",
        color = NA
      ),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.line = element_blank(),
      axis.ticks = element_blank()
    )
  
  
  ggsave(
    filename = file.path(
      bulk_rnaseq_volcano_figure_dir,
      paste0(
        "bulk_rnaseq_volcano_comparison_",
        comparison_number,".pdf")
    ),
    plot = volcano_plot_point_pdf,
    device = grDevices::cairo_pdf,
    width = figure_width,
    height = figure_height,
    units = "in",
    bg = "transparent"
  )
  
  ggsave(
    filename = file.path(
      bulk_rnaseq_volcano_figure_dir,
      paste0(
        "bulk_rnaseq_volcano_comparison_",
        comparison_number,"_only_label.pdf")
    ),
    plot = volcano_plot_only_label_pdf,
    device = grDevices::pdf,
    width = figure_width,
    height = figure_height,
    units = "in",
    bg = "transparent"
  )
  
  saveRDS(
    object = volcano_plot_point_pdf,
    file = file.path(
      bulk_rnaseq_volcano_figure_dir,
      paste0("bulk_rnaseq_volcano_comparison_",comparison_number,".rds")
    )
  )
  
  ggsave(
    filename = file.path(
      bulk_rnaseq_volcano_figure_dir,
      paste0(
        "bulk_rnaseq_volcano_comparison_",
        comparison_number,"_panel.png")
    ),
    plot = volcano_plot_panel_png,
    width = panel_width,
    height = panel_height,
    units = "in",
    dpi = figure_dpi,
    bg = "transparent"
  )
}


## Generate and save volcano plots ----------------------------------------------------

make_bulk_rnaseq_volcano(
  comparison_number = 1,
  comparison_label = "Original",
  show_gene_labels = FALSE
)

make_bulk_rnaseq_volcano(
  comparison_number = 2,
  comparison_label = "Under21",
  show_gene_labels = FALSE
)

make_bulk_rnaseq_volcano(
  comparison_number = 3,
  comparison_label = "Under1",
  show_gene_labels = FALSE
)

readr::write_csv(
  labelled_gene_table |>
    dplyr::select(
      comparison_name,
      comparison_label,
      gene_symbol,
      logFC,
      FDR
    ),
  file = bulk_rnaseq_volcano_labelled_gene_table_file,
  na = ""
)