# Plot GO GSEA results for bulk RNA-seq data
#
# This script loads the simplified GO GSEA results generated by
# 07_05_bulk_rnaseq_go_gsea.R and creates the dot plot used for the
# manuscript figure.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(dplyr)
  library(fs)
  library(ggplot2)
  library(readr)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_01_analysis_parameters.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))


## Define input and output paths ---------------------------------------------

gene_set_analysis_table_dir <- file.path(
  bulk_rnaseq_table_dir,
  "gene_set_analysis"
)

go_gsea_table_dir <- file.path(
  gene_set_analysis_table_dir,
  "go_gsea"
)

go_gsea_result_file <- file.path(
  go_gsea_table_dir,
  "bulk_rnaseq_go_gsea_simplified_results.csv"
)

bulk_rnaseq_go_gsea_figure_dir <- file.path(
  bulk_rnaseq_figure_dir,
  "08_07_06_bulk_rnaseq_go_gsea_figures"
)

bulk_rnaseq_go_gsea_figure_file <- file.path(
  bulk_rnaseq_go_gsea_figure_dir,
  "bulk_rnaseq_go_gsea_dotplot.pdf"
)

fs::dir_create(bulk_rnaseq_go_gsea_figure_dir)


## Define plot settings ------------------------------------------------------

comparison_display_order <- c(
  "Original",
  "Under21",
  "Under1"
)

biological_process_display_order <- c(
  "inorganic ion transmembrane transport",
  "lipid catabolic process",
  "cytokine-mediated signaling pathway",
  "inflammatory response",
  "regulation of cytokinesis",
  "nuclear division",
  "chromosome segregation"
)

text_size <- 14
figure_width <- 6.5
figure_height <- 3.6


## Load and validate GO GSEA results -----------------------------------------

if (!file.exists(go_gsea_result_file)) {
  stop(
    "GO GSEA result file not found: ",
    go_gsea_result_file,
    call. = FALSE
  )
}

go_gsea_results <- readr::read_csv(
  go_gsea_result_file,
  show_col_types = FALSE
)

required_go_gsea_columns <- c(
  "comparison_label",
  "ONTOLOGY",
  "Description",
  "NES",
  "p.adjust",
  "minus_log10_adjusted_p_value"
)

missing_go_gsea_columns <- setdiff(
  required_go_gsea_columns,
  colnames(go_gsea_results)
)

if (length(missing_go_gsea_columns) > 0) {
  stop(
    "The GO GSEA result table is missing required columns: ",
    paste(missing_go_gsea_columns, collapse = ", "),
    call. = FALSE
  )
}

if (!exists("bulk_rnaseq_comparison_plot_labels")) {
  stop(
    "bulk_rnaseq_comparison_plot_labels is not defined in ",
    "00_01_analysis_parameters.R.",
    call. = FALSE
  )
}

missing_comparison_labels <- setdiff(
  comparison_display_order,
  unique(go_gsea_results$comparison_label)
)

if (length(missing_comparison_labels) > 0) {
  stop(
    "The GO GSEA result table is missing comparison labels: ",
    paste(missing_comparison_labels, collapse = ", "),
    call. = FALSE
  )
}


## Prepare GO GSEA plot data -------------------------------------------------

go_gsea_plot_table <- go_gsea_results |>
  dplyr::filter(
    .data$ONTOLOGY == "BP",
    .data$p.adjust < 0.05,
    .data$Description %in% biological_process_display_order
  ) |>
  dplyr::mutate(
    comparison_label = factor(
      .data$comparison_label,
      levels = comparison_display_order
    ),
    Description = factor(
      .data$Description,
      levels = biological_process_display_order
    )
  )

if (nrow(go_gsea_plot_table) == 0) {
  stop(
    "No selected significant GO biological-process terms were found.",
    call. = FALSE
  )
}

missing_biological_process_terms <- setdiff(
  biological_process_display_order,
  unique(as.character(go_gsea_plot_table$Description))
)

if (length(missing_biological_process_terms) > 0) {
  warning(
    "The following selected GO terms were not found in the significant ",
    "simplified results: ",
    paste(missing_biological_process_terms, collapse = ", ")
  )
}

maximum_absolute_normalized_enrichment_score <- max(
  abs(go_gsea_plot_table$NES),
  na.rm = TRUE
)

if (!is.finite(maximum_absolute_normalized_enrichment_score)) {
  stop(
    "Could not determine the normalized enrichment score range.",
    call. = FALSE
  )
}


## Create GO GSEA dot plot ---------------------------------------------------

bulk_rnaseq_go_gsea_dotplot <- ggplot(
  go_gsea_plot_table,
  aes(
    x = .data$comparison_label,
    y = .data$Description
  )
) +
  geom_point(
    aes(
      fill = .data$NES,
      size = .data$minus_log10_adjusted_p_value
    ),
    shape = 21,
    color = "black"
  ) +
  scale_x_discrete(
    labels = bulk_rnaseq_comparison_plot_labels,
    drop = FALSE
  ) +
  scale_y_discrete(
    position = "right",
    drop = FALSE
  ) +
  scale_fill_distiller(
    palette = "RdBu",
    direction = 1,
    limits = c(
      -maximum_absolute_normalized_enrichment_score,
      maximum_absolute_normalized_enrichment_score
    ),
    breaks = c(2, 0, -2),
    guide = guide_colorbar(
      order = 2,
      frame.colour = "black",
      ticks.colour = "black",
      label.position = "left"
    )
  ) +
  scale_size_continuous(
    range = c(1, 10.5),
    breaks = c(2, 10, 30),
    guide = guide_legend(
      order = 1,
      label.position = "left"
    )
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "NES",
    size = "−log10\n(Adj.P)"
  ) +
  theme(
    aspect.ratio = 2.089,
    axis.text.y = element_text(
      face = "plain",
      color = "black",
      size = text_size
    ),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      face = "plain",
      color = "black",
      size = text_size
    ),
    legend.key = element_blank(),
    legend.title = element_text(
      face = "plain",
      color = "black",
      hjust = 0.5,
      size = text_size*1.0
    ),
    legend.text = element_text(
      face = "plain",
      color = "black",
      size = text_size*1.0
    ),
    legend.box = "vertical",
    legend.box.just = "right",
    legend.justification = c(0.5, 0.9),
    legend.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    plot.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.grid = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "black"
    ),
    axis.line = element_blank()
  )


## Save GO GSEA dot plot -----------------------------------------------------

ggsave(
  filename = bulk_rnaseq_go_gsea_figure_file,
  plot = bulk_rnaseq_go_gsea_dotplot,
  device = cairo_pdf,
  width = figure_width,
  height = figure_height,
  units = "in",
  bg = "transparent"
)
