# Plot the bulk RNA-seq expression heatmaps
#
# This script loads the heatmap results generated by
# 07_02_bulk_rnaseq_heatmap.R and creates two heatmap versions.
#
# The representative-marker heatmap reproduces the manuscript figure.
# The all-marker heatmap is additionally exported as an exploratory output
# and is not used in the manuscript or supplementary figures.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(circlize)
  library(ComplexHeatmap)
  library(grid)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))


## Define input and output paths ---------------------------------------------

bulk_rnaseq_heatmap_results_file <- file.path(
  bulk_rnaseq_object_dir,
  "bulk_rnaseq_heatmap_results.rds"
)

bulk_rnaseq_heatmap_figure_dir <- file.path(
  bulk_rnaseq_figure_dir,
  "08_07_02_bulk_rnaseq_heatmap_figures"
)

representative_heatmap_figure_file <- file.path(
  bulk_rnaseq_heatmap_figure_dir,
  "bulk_rnaseq_heatmap_representative_caf8_markers.pdf"
)

all_marker_heatmap_figure_file <- file.path(
  bulk_rnaseq_heatmap_figure_dir,
  "bulk_rnaseq_heatmap_all_caf8_markers_exploratory.pdf"
)

fs::dir_create(bulk_rnaseq_heatmap_figure_dir)


## Define plot settings ------------------------------------------------------

font_size <- 16

number_of_row_clusters <- 6
clustering_seed <- 1234

figure_width <- 6.5
figure_height <- 10

heatmap_and_dendrogram_width <- 5.2

heatmap_width <- grid::unit(4.108, "in")
row_dendrogram_width <- grid::unit(
  heatmap_and_dendrogram_width - 4.108,
  "in"
)

annotation_bar_height <- grid::unit(0.236, "in")

heatmap_height <- grid::unit(
  7.018373 - 2 * 0.236,
  "in"
)

column_gap <- grid::unit(0.0315, "in")

row_annotation_width <- grid::unit(1.44, "in")
label_link_width <- grid::unit(0.30, "in")

heatmap_color_scale <- circlize::colorRamp2(
  c(-2, 0, 2),
  c("#98CCBE", "#F7F7F7", "#C05A9E")
)

oxygen_colors <- c(
  "normocaf_normoxia" = "#F4B6B6",
  "hypocaf_hypoxia" = "#AFC2FF"
)

pair_colors <- c(
  "pair_02" = "#C8E3C8",
  "pair_08" = "#F3E8B4",
  "pair_09" = "#D6CBE8"
)


## Load heatmap results ------------------------------------------------------

if (!file.exists(bulk_rnaseq_heatmap_results_file)) {
  stop(
    "Bulk RNA-seq heatmap results not found: ",
    bulk_rnaseq_heatmap_results_file,
    call. = FALSE
  )
}

bulk_rnaseq_heatmap_results <- readRDS(
  bulk_rnaseq_heatmap_results_file
)

gene_z_score_matrix <-
  bulk_rnaseq_heatmap_results$gene_z_score_matrix

sample_metadata <-
  bulk_rnaseq_heatmap_results$ordered_sample_metadata

labelled_gene_sets <-
  bulk_rnaseq_heatmap_results$labelled_gene_sets


## Validate heatmap results --------------------------------------------------

required_metadata_columns <- c(
  "sample_name",
  "pair",
  "condition"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(sample_metadata)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    "Heatmap sample metadata is missing required columns: ",
    paste(missing_metadata_columns, collapse = ", "),
    call. = FALSE
  )
}

if (!identical(
  colnames(gene_z_score_matrix),
  sample_metadata$sample_name
)) {
  stop(
    paste0(
      "Heatmap matrix columns do not match the ordered ",
      "sample metadata."
    ),
    call. = FALSE
  )
}

required_label_sets <- c(
  "all_caf8_and_senescence",
  "representative_caf8_and_senescence"
)

missing_label_sets <- setdiff(
  required_label_sets,
  names(labelled_gene_sets)
)

if (length(missing_label_sets) > 0) {
  stop(
    "Heatmap results are missing required labelled gene sets: ",
    paste(missing_label_sets, collapse = ", "),
    call. = FALSE
  )
}


## Prepare shared heatmap components ----------------------------------------

column_split <- factor(
  as.character(sample_metadata$pair),
  levels = c(
    "pair_02",
    "pair_08",
    "pair_09"
  )
)

heatmap_legend <- ComplexHeatmap::Legend(
  title = "Z score (±2 clip)",
  title_position = "topcenter",
  at = c(-2, 0, 2),
  labels = c("-2", "0", "2"),
  col_fun = heatmap_color_scale,
  border = "black",
  title_gp = grid::gpar(
    fontface = "plain",
    fontsize = font_size * 0.8
  ),
  labels_gp = grid::gpar(
    fontface = "plain",
    fontsize = font_size * 0.7
  ),
  direction = "horizontal",
  legend_width = grid::unit(1.20, "in"),
  legend_height = grid::unit(0.23, "in")
)

packed_legends <- ComplexHeatmap::packLegend(
  heatmap_legend,
  direction = "horizontal"
)


## Helper functions ----------------------------------------------------------

make_bottom_annotation <- function() {
  ComplexHeatmap::HeatmapAnnotation(
    CAF_pair = ComplexHeatmap::anno_simple(
      as.character(sample_metadata$pair),
      col = pair_colors,
      border = FALSE,
      height = annotation_bar_height
    ),
    Oxygen = ComplexHeatmap::anno_simple(
      as.character(sample_metadata$condition),
      col = oxygen_colors,
      border = FALSE,
      height = annotation_bar_height
    ),
    show_legend = FALSE,
    annotation_name_side = "left",
    annotation_name_gp = grid::gpar(
      fontface = "plain",
      fontsize = font_size
    ),
    annotation_label = c("", "")
  )
}

make_right_annotation <- function(labelled_genes) {
  labelled_gene_positions <- match(
    labelled_genes,
    rownames(gene_z_score_matrix)
  )

  if (anyNA(labelled_gene_positions)) {
    missing_labelled_genes <- labelled_genes[
      is.na(labelled_gene_positions)
    ]

    stop(
      "Labelled genes were not found in the Z-score matrix: ",
      paste(missing_labelled_genes, collapse = ", "),
      call. = FALSE
    )
  }

  ComplexHeatmap::rowAnnotation(
    labelled_genes = ComplexHeatmap::anno_mark(
      at = labelled_gene_positions,
      labels = labelled_genes,
      labels_gp = grid::gpar(
        col = "black",
        fontface = "plain",
        fontsize = font_size
      ),
      link_width = label_link_width
    ),
    width = row_annotation_width
  )
}

decorate_bottom_annotations <- function() {
  for (slice_index in seq_len(3)) {
    ComplexHeatmap::decorate_annotation(
      "CAF_pair",
      slice = slice_index,
      {
        grid::grid.rect(
          x = grid::unit(0.5, "npc"),
          y = grid::unit(0.5, "npc"),
          width = grid::unit(1, "npc"),
          height = grid::unit(1, "npc"),
          gp = grid::gpar(
            fill = NA,
            col = "black",
            lwd = 0.7
          )
        )
      }
    )

    ComplexHeatmap::decorate_annotation(
      "Oxygen",
      slice = slice_index,
      {
        grid::grid.rect(
          x = grid::unit(0.25, "npc"),
          y = grid::unit(0.5, "npc"),
          width = grid::unit(0.5, "npc"),
          height = grid::unit(1, "npc"),
          gp = grid::gpar(
            fill = NA,
            col = "black",
            lwd = 0.7
          )
        )

        grid::grid.rect(
          x = grid::unit(0.75, "npc"),
          y = grid::unit(0.5, "npc"),
          width = grid::unit(0.5, "npc"),
          height = grid::unit(1, "npc"),
          gp = grid::gpar(
            fill = NA,
            col = "black",
            lwd = 0.7
          )
        )
      }
    )
  }
}

save_bulk_rnaseq_heatmap <- function(
    labelled_genes,
    output_file
) {
  bottom_annotation <- make_bottom_annotation()
  right_annotation <- make_right_annotation(labelled_genes)

  set.seed(clustering_seed)

  heatmap <- ComplexHeatmap::Heatmap(
    gene_z_score_matrix,
    name = "main",
    show_row_names = FALSE,
    show_column_names = FALSE,
    column_title = NULL,
    column_title_side = "bottom",
    row_title = NULL,
    row_title_gp = grid::gpar(
      fontface = "plain"
    ),
    row_title_rot = 90,
    row_km = number_of_row_clusters,
    border = FALSE,
    na_col = "black",
    col = heatmap_color_scale,
    show_heatmap_legend = FALSE,
    bottom_annotation = bottom_annotation,
    right_annotation = right_annotation,
    cluster_rows = TRUE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D2",
    show_row_dend = TRUE,
    row_dend_width = row_dendrogram_width,
    row_dend_gp = grid::gpar(
      col = "grey30",
      lwd = 0.6
    ),
    cluster_columns = FALSE,
    column_split = column_split,
    column_gap = column_gap,
    width = heatmap_width,
    height = heatmap_height,
    use_raster = TRUE,
    raster_quality = 7,
    raster_device = "CairoPNG"
  )

  grDevices::pdf(
    file = output_file,
    width = figure_width,
    height = figure_height,
    bg = "transparent"
  )

  on.exit(grDevices::dev.off(), add = TRUE)

  set.seed(clustering_seed)

  ComplexHeatmap::draw(
    heatmap,
    annotation_legend_list = packed_legends,
    annotation_legend_side = "bottom"
  )

  decorate_bottom_annotations()

  invisible(output_file)
}


## Create manuscript heatmaps ------------------------------------------------

# This version reproduces the heatmap used in the manuscript figure.
save_bulk_rnaseq_heatmap(
  labelled_genes = labelled_gene_sets$
    representative_caf8_and_senescence,
  output_file = representative_heatmap_figure_file
)


## Create exploratory heatmaps -----------------------------------------------

# This exploratory version displays every CAF-8 marker included among the
# high-SD genes and is not used in the manuscript or supplementary figures.
save_bulk_rnaseq_heatmap(
  labelled_genes = labelled_gene_sets$
    all_caf8_and_senescence,
  output_file = all_marker_heatmap_figure_file
)


## Print output summary ------------------------------------------------------

message("Bulk RNA-seq heatmaps completed.")
message(
  "Saved representative-marker heatmap: ",
  representative_heatmap_figure_file
)
message(
  "Saved exploratory all-marker heatmap: ",
  all_marker_heatmap_figure_file
)
