# Plot KEGG over-representation analysis results for bulk RNA-seq data
#
# This script loads the KEGG ORA results generated by
# 07_04_bulk_rnaseq_kegg_ora.R and creates the tile plot used for the
# manuscript figure.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(dplyr)
  library(fs)
  library(ggplot2)
  library(readr)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_01_analysis_parameters.R"
))

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))


## Define input and output paths ---------------------------------------------

gene_set_analysis_table_dir <- file.path(
  bulk_rnaseq_table_dir,
  "gene_set_analysis"
)

kegg_ora_table_dir <- file.path(
  gene_set_analysis_table_dir,
  "kegg_ora"
)

kegg_ora_result_file <- file.path(
  kegg_ora_table_dir,
  "bulk_rnaseq_kegg_ora_all_results.csv"
)

bulk_rnaseq_kegg_ora_figure_dir <- file.path(
  bulk_rnaseq_figure_dir,
  "08_07_04_bulk_rnaseq_kegg_ora_figures"
)

bulk_rnaseq_kegg_ora_figure_file <- file.path(
  bulk_rnaseq_kegg_ora_figure_dir,
  "bulk_rnaseq_kegg_ora_tileplot.pdf"
)

bulk_rnaseq_kegg_ora_png_file <- file.path(
  bulk_rnaseq_kegg_ora_figure_dir,
  "bulk_rnaseq_kegg_ora_tileplot.png"
)

fs::dir_create(bulk_rnaseq_kegg_ora_figure_dir)


## Define plot settings ------------------------------------------------------

comparison_display_order <- c(
  "Original",
  "Under21",
  "Under1"
)

pathway_display_order <- c(
  "Calcium signaling pathway",
  "Rap1 signaling pathway",
  "Cadherin signaling",
  "Hippo signaling pathway",
  "JAK-STAT signaling pathway",
  "HIF-1 signaling pathway",
  "DNA replication",
  "Homologous recombination",
  "Motor proteins",
  "Cell cycle"
)

text_size <- 10
figure_width <- 5.8
figure_height <- 3


## Load KEGG ORA results -----------------------------------------------------

if (!file.exists(kegg_ora_result_file)) {
  stop(
    "KEGG ORA result file not found: ",
    kegg_ora_result_file,
    call. = FALSE
  )
}

kegg_ora_results <- readr::read_csv(
  kegg_ora_result_file,
  show_col_types = FALSE
)

required_kegg_ora_columns <- c(
  "comparison_label",
  "Description",
  "p.adjust",
  "signed_gene_ratio",
  "significance_label"
)

missing_kegg_ora_columns <- setdiff(
  required_kegg_ora_columns,
  colnames(kegg_ora_results)
)

if (length(missing_kegg_ora_columns) > 0) {
  stop(
    "The KEGG ORA result table is missing required columns: ",
    paste(missing_kegg_ora_columns, collapse = ", "),
    call. = FALSE
  )
}


## Prepare KEGG ORA plot data ------------------------------------------------

kegg_ora_plot_table <- kegg_ora_results |>
  dplyr::filter(
    .data$Description %in% pathway_display_order
  ) |>
  dplyr::mutate(
    comparison_label = factor(
      .data$comparison_label,
      levels = comparison_display_order
    ),
    Description = factor(
      .data$Description,
      levels = pathway_display_order
    )
  )

if (nrow(kegg_ora_plot_table) == 0) {
  stop(
    "No selected KEGG pathways were found.",
    call. = FALSE
  )
}

missing_comparison_labels <- setdiff(
  comparison_display_order,
  unique(as.character(kegg_ora_results$comparison_label))
)

if (length(missing_comparison_labels) > 0) {
  stop(
    "The KEGG ORA result table is missing comparison labels: ",
    paste(missing_comparison_labels, collapse = ", "),
    call. = FALSE
  )
}

maximum_absolute_gene_ratio <- max(
  abs(kegg_ora_plot_table$signed_gene_ratio),
  na.rm = TRUE
)


## Create KEGG ORA dot plot -------------------------------------------------

bulk_rnaseq_kegg_ora_dotplot <- ggplot(
  kegg_ora_plot_table,
  aes(
    x = .data$comparison_label,
    y = .data$Description,
    fill = .data$signed_gene_ratio
  )
) +
  geom_tile(
    color = "gray20"
  ) +
  geom_text(
    aes(label = .data$significance_label),
    fontface = "plain",
    color = "black",
    vjust = 0.75,
    size = text_size * 0.45
  ) +
  scale_x_discrete(
    expand = expansion(mult = c(0, 0)),
    drop = FALSE,
    labels = bulk_rnaseq_comparison_plot_labels
  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0, 0)),
    drop = FALSE
  ) +
  scale_fill_distiller(
    palette = "RdBu",
    direction = 1,
    limits = c(
      -maximum_absolute_gene_ratio,
      maximum_absolute_gene_ratio
    ),
    breaks = c(-0.1, 0, 0.1),
    guide = guide_colorbar(
      frame.colour = "black",
      ticks.colour = "black"
    )
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Signed\ngene ratio"
  ) +
  theme(
    aspect.ratio = 2.984,
    axis.text.x = element_text(
      face = "plain",
      color = "black",
      angle = 45,
      hjust = 1,
      size = text_size * 1.3
    ),
    axis.text.y = element_text(
      face = "plain",
      color = "black",
      size = text_size * 1.3
    ),
    legend.title = element_text(
      face = "plain",
      color = "black",
      size = text_size + 2,
      hjust = 0.5
    ),
    legend.text = element_text(
      face = "plain",
      color = "black",
      size = text_size
    ),
    plot.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    legend.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.background = element_rect(
      fill = "transparent",
      color = NA
    ),
    panel.border = element_rect(
      fill = NA,
      color = "black"
    ),
    panel.grid = element_blank(),
    axis.line = element_blank()
  )


## Save KEGG ORA tile plot ---------------------------------------------------

ggsave(
  filename = bulk_rnaseq_kegg_ora_figure_file,
  plot = bulk_rnaseq_kegg_ora_tileplot,
  device = cairo_pdf,
  width = figure_width,
  height = figure_height,
  units = "in",
  bg = "transparent"
)
