# Plot principal component analysis of bulk RNA-seq samples
#
# This script loads the PCA results generated by
# 07_01_bulk_rnaseq_pca.R and generates the three-dimensional PCA figure.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(scatterplot3d)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(
  project_dir,
  "code",
  "00_config",
  "00_02_paths.R"
))


## Define input and output paths ---------------------------------------------

bulk_rnaseq_pca_results_file <- file.path(
  bulk_rnaseq_object_dir,
  "bulk_rnaseq_pca_results.rds"
)

bulk_rnaseq_pca_figure_dir <- file.path(
  bulk_rnaseq_figure_dir,
  "08_07_01_bulk_rnaseq_pca_figures"
)

bulk_rnaseq_pca_figure_file <- file.path(
  bulk_rnaseq_pca_figure_dir,
  "bulk_rnaseq_pca.pdf"
)

fs::dir_create(bulk_rnaseq_pca_figure_dir)


## Define plot settings ------------------------------------------------------

pca_axis_order <- c(
  x = "PC1",
  y = "PC3",
  z = "PC2"
)

condition_display_order <- c(
  "hypocaf_normoxia",
  "hypocaf_hypoxia",
  "normocaf_normoxia",
  "normocaf_hypoxia"
)

condition_colors <- c(
  "hypocaf_normoxia" = "#7FBFFF",
  "hypocaf_hypoxia" = "#607DF0",
  "normocaf_normoxia" = "#FF0000",
  "normocaf_hypoxia" = "#FFA3A3"
)

condition_fill_colors <- stats::setNames(
  grDevices::adjustcolor(
    unname(condition_colors),
    alpha.f = 0.6
  ),
  names(condition_colors)
)

condition_labels <- expression(
  "Hypo-CAF in 21% " * O[2],
  "Hypo-CAF",
  "Normo-CAF",
  "Normo-CAF in 1% " * O[2]
)

figure_width <- 5.0
figure_height <- 4.8

point_size <- 1.6
plot_angle <- 105
plot_y_scale <- 1.4

show_pair_labels <- TRUE
pair_label_cex <- 1.5


## Helper functions ----------------------------------------------------------

make_symmetric_limits <- function(x) {
  maximum_absolute_value <- max(abs(x), na.rm = TRUE)
  c(-maximum_absolute_value, maximum_absolute_value)
}

format_pc_axis_label <- function(pc_name, variance_explained) {
  pc_number <- as.integer(stringr::str_remove(pc_name, "^PC"))

  paste0(
    pc_name,
    " (",
    round(variance_explained[pc_number] * 100, 1),
    "%)"
  )
}


## Load PCA results ----------------------------------------------------------

if (!file.exists(bulk_rnaseq_pca_results_file)) {
  stop(
    "Bulk RNA-seq PCA results not found: ",
    bulk_rnaseq_pca_results_file,
    call. = FALSE
  )
}

bulk_rnaseq_pca_results <- readRDS(
  bulk_rnaseq_pca_results_file
)

pca_plot_data <- bulk_rnaseq_pca_results$scores
variance_explained <- bulk_rnaseq_pca_results$variance_explained

required_columns <- c(
  "sample_name",
  "pair",
  "pair_number",
  "condition",
  "PC1",
  "PC2",
  "PC3"
)

missing_columns <- setdiff(
  required_columns,
  colnames(pca_plot_data)
)

if (length(missing_columns) > 0) {
  stop(
    "PCA score table is missing required columns: ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

pca_plot_data <- pca_plot_data %>%
  dplyr::mutate(
    condition = factor(
      as.character(.data$condition),
      levels = condition_display_order
    ),
    point_fill = unname(
      condition_fill_colors[as.character(.data$condition)]
    )
  )

if (any(is.na(pca_plot_data$condition))) {
  stop(
    "Unexpected condition values were detected in the PCA results.",
    call. = FALSE
  )
}

# Draw distant points first and nearer points last.
point_draw_order <- order(
  pca_plot_data[[pca_axis_order[["y"]]]],
  decreasing = TRUE
)

pca_plot_data_draw <- pca_plot_data[
  point_draw_order,
  ,
  drop = FALSE
]


## Generate and save PCA figure ---------------------------------------------

grDevices::cairo_pdf(
  filename = bulk_rnaseq_pca_figure_file,
  width = figure_width,
  height = figure_height,
  bg = "transparent",
  family = "sans"
)

pca_scatterplot <- scatterplot3d::scatterplot3d(
  x = pca_plot_data[[pca_axis_order[["x"]]]],
  y = pca_plot_data[[pca_axis_order[["y"]]]],
  z = pca_plot_data[[pca_axis_order[["z"]]]],
  xlim = make_symmetric_limits(
    pca_plot_data[[pca_axis_order[["x"]]]]
  ),
  ylim = make_symmetric_limits(
    pca_plot_data[[pca_axis_order[["y"]]]]
  ),
  zlim = make_symmetric_limits(
    pca_plot_data[[pca_axis_order[["z"]]]]
  ),
  type = "n",
  angle = plot_angle,
  scale.y = plot_y_scale,
  grid = TRUE,
  box = TRUE,
  mar = c(5.0, 3.0, 3.0, 3.0),
  xlab = format_pc_axis_label(
    pca_axis_order[["x"]],
    variance_explained
  ),
  ylab = format_pc_axis_label(
    pca_axis_order[["y"]],
    variance_explained
  ),
  zlab = format_pc_axis_label(
    pca_axis_order[["z"]],
    variance_explained
  )
)

point_coordinates <- pca_scatterplot$xyz.convert(
  x = pca_plot_data_draw[[pca_axis_order[["x"]]]],
  y = pca_plot_data_draw[[pca_axis_order[["y"]]]],
  z = pca_plot_data_draw[[pca_axis_order[["z"]]]]
)

graphics::points(
  x = point_coordinates$x,
  y = point_coordinates$y,
  pch = 21,
  col = "black",
  bg = pca_plot_data_draw$point_fill,
  cex = point_size,
  lwd = 0.8
)

if (show_pair_labels) {
  pair_condition_centroids <- pca_plot_data %>%
    dplyr::group_by(.data$pair, .data$pair_number, .data$condition) %>%
    dplyr::summarise(
      PC1 = mean(.data$PC1),
      PC2 = mean(.data$PC2),
      PC3 = mean(.data$PC3),
      .groups = "drop"
    )

  pair_label_offsets <- tibble::tribble(
    ~pair_number, ~condition,          ~PC1_offset, ~PC2_offset, ~PC3_offset,
    "2",          "hypocaf_hypoxia",            -32,           0,           0,
    "8",          "hypocaf_hypoxia",              0,           0,          +3,
    "9",          "hypocaf_hypoxia",            -22,           0,           0,
    "2",          "hypocaf_normoxia",           -45,           0,         -15,
    "8",          "hypocaf_normoxia",           -10,           0,         -25,
    "2",          "normocaf_hypoxia",             0,           0,           5,
    "9",          "normocaf_hypoxia",             0,           0,           5,
    "2",          "normocaf_normoxia",            0,           0,           5,
    "8",          "normocaf_normoxia",          +10,           0,         -20,
    "9",          "normocaf_normoxia",           -5,           0,         -23
  )

  pair_condition_centroids <- pair_condition_centroids %>%
    dplyr::mutate(
      pair_number = as.character(.data$pair_number),
      condition = as.character(.data$condition)
    ) %>%
    dplyr::left_join(
      pair_label_offsets,
      by = c("pair_number", "condition")
    ) %>%
    dplyr::mutate(
      PC1_offset = tidyr::replace_na(.data$PC1_offset, 0),
      PC2_offset = tidyr::replace_na(.data$PC2_offset, 0),
      PC3_offset = tidyr::replace_na(.data$PC3_offset, 0),
      PC1 = .data$PC1 + .data$PC1_offset,
      PC2 = .data$PC2 + .data$PC2_offset,
      PC3 = .data$PC3 + .data$PC3_offset
    )

  centroid_coordinates <- pca_scatterplot$xyz.convert(
    x = pair_condition_centroids[[pca_axis_order[["x"]]]],
    y = pair_condition_centroids[[pca_axis_order[["y"]]]],
    z = pair_condition_centroids[[pca_axis_order[["z"]]]]
  )

  graphics::text(
    x = centroid_coordinates$x,
    y = centroid_coordinates$y,
    labels = paste0("#", pair_condition_centroids$pair_number),
    pos = 3,
    offset = 0.35,
    cex = pair_label_cex
  )
}

graphics::legend(
  "bottomleft",
  inset = c(0.20, -0.30),
  legend = condition_labels,
  col = "black",
  pt.bg = unname(condition_fill_colors[condition_display_order]),
  pch = 21,
  pt.cex = 1.0,
  cex = 0.72,
  bty = "n",
  ncol = 2,
  xpd = NA
)

grDevices::dev.off()


## Print output summary ------------------------------------------------------

message("Bulk RNA-seq PCA figure completed.")
message("Saved PCA figure: ", bulk_rnaseq_pca_figure_file)
