# Prepare spatial niche supplementary tables
#
# This script formats spatial niche composition tables for supplementary
# tables using the summary tables generated by:
#   04_03_niche_summarize_spatial_niche_composition.R
#
# Percent values are exported as 0–100 numeric values.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directories ---------------------------------------

niche_table_dir <- file.path(xenium_table_dir, "niche_analysis")

niche_supplementary_table_dir <- file.path(
  niche_table_dir,
  "supplementary_tables"
)

fs::dir_create(niche_supplementary_table_dir)


## Define display orders and labels ------------------------------------------

niche_order <- paste0("niche_", c(2, 3, 8, 9, 5, 6, 1, 4, 7, 10))

niche_name_for_table <- c(
  "niche_2" = "N1_NormalAcinar",
  "niche_3" = "N2_AtrophicAcinar",
  "niche_8" = "N3_NormalPanIN",
  "niche_9" = "N4_Cancer",
  "niche_5" = "N5_Islet",
  "niche_6" = "N6_Vascular",
  "niche_1" = "N7_PlasmaCell",
  "niche_4" = "N8_Lymphoid",
  "niche_7" = "N9_LymphoidMyeloid",
  "niche_10" = "N10_Neuronal"
)

initial_cluster_display_order <- as.character(c(
  0, 13, 24,
  33, 12, 1, 17, 30,
  23,
  10, 27,
  20,
  14,
  11,
  34, 3,
  18, 37,
  15,
  16, 2,
  5, 4, 31,
  26,
  29
))

initial_label_display_order <- paste0("Ini-", initial_cluster_display_order)

label_for_summary_order <- c(
  caf_subcluster_display_order,
  initial_label_display_order
)

initial_label_name_for_table <- c(
  "Ini-0"  = "C0_Acinar",
  "Ini-13" = "C13_Acinar",
  "Ini-24" = "C24_Acinar",
  "Ini-33" = "C33_DuctalLikeAcinar",
  "Ini-12" = "C12_DuctalLikeAcinar",
  "Ini-1"  = "C1_DuctalLikeAcinar",
  "Ini-17" = "C17_DuctalLikeAcinar",
  "Ini-30" = "C30_DuctalLikeAcinar",
  "Ini-23" = "C23_Ductal_Normal",
  "Ini-10" = "C10_Ductal_PanIN",
  "Ini-27" = "C27_Ductal_PanIN",
  "Ini-20" = "C20_Ductal_PDAC",
  "Ini-14" = "C14_Islet",
  "Ini-11" = "C11_Mural",
  "Ini-34" = "C34_Endothelial",
  "Ini-3"  = "C3_Endothelial",
  "Ini-18" = "C18_Plasma",
  "Ini-37" = "C37_Plasma",
  "Ini-15" = "C15_Bcell",
  "Ini-16" = "C16_Tcell",
  "Ini-2"  = "C2_Tcell",
  "Ini-5"  = "C5_Myeloid",
  "Ini-4"  = "C4_Myeloid",
  "Ini-31" = "C31_Myeloid",
  "Ini-26" = "C26_Mast",
  "Ini-29" = "C29_Neuronal"
)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }
  
  readr::read_csv(file, show_col_types = FALSE)
}

format_niche_wide_table <- function(data, label_order, multiply_by = 1) {
  data %>%
    dplyr::mutate(
      niche = as.character(.data$niche),
      spatial_niche = dplyr::recode(
        .data$niche,
        !!!niche_name_for_table
      )
    ) %>%
    dplyr::arrange(factor(.data$niche, levels = rev(niche_order))) %>%
    dplyr::select(
      spatial_niche,
      dplyr::any_of(label_order)
    ) %>%
    dplyr::mutate(
      dplyr::across(
        -spatial_niche,
        ~ .x * multiply_by
      )
    ) %>%
    dplyr::rename_with(
      ~ dplyr::recode(.x, !!!initial_label_name_for_table),
      dplyr::any_of(initial_label_display_order)
    )
}


## Read 04_03 output tables --------------------------------------------------

niche_cell_count_wide <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_cell_count_wide.csv"),
  "Spatial niche cell count wide table"
)

niche_label_prop_within_niche_wide <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_label_proportion_within_niche_wide.csv"),
  "Spatial niche label proportion within niche wide table"
)

niche_prop_within_label_wide <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_proportion_within_label_wide.csv"),
  "Spatial niche proportion within label wide table"
)

caf_subcluster_prop_within_niche_wide <- read_required_csv(
  file.path(niche_table_dir, "spatial_niche_caf_subcluster_proportion_within_niche_wide.csv"),
  "CAF subcluster proportion within niche wide table"
)


## Format supplementary tables -----------------------------------------------

supp_niche_cell_count <- format_niche_wide_table(
  niche_cell_count_wide,
  label_order = label_for_summary_order,
  multiply_by = 1
)

supp_cluster_prop_within_niche <- format_niche_wide_table(
  niche_label_prop_within_niche_wide,
  label_order = label_for_summary_order,
  multiply_by = 100
)

supp_niche_prop_within_cluster <- format_niche_wide_table(
  niche_prop_within_label_wide,
  label_order = label_for_summary_order,
  multiply_by = 100
)

supp_caf_subcluster_prop_within_niche <- format_niche_wide_table(
  caf_subcluster_prop_within_niche_wide,
  label_order = caf_subcluster_display_order,
  multiply_by = 100
)


## Save supplementary tables -------------------------------------------------

readr::write_csv(
  supp_niche_cell_count,
  file = file.path(
    niche_supplementary_table_dir,
    "niche_cell_count_within_niche.csv"
  )
)

readr::write_csv(
  supp_cluster_prop_within_niche,
  file = file.path(
    niche_supplementary_table_dir,
    "niche_cluster_proportion_within_niche_percent.csv"
  )
)

readr::write_csv(
  supp_niche_prop_within_cluster,
  file = file.path(
    niche_supplementary_table_dir,
    "niche_proportion_within_cluster_percent.csv"
  )
)

readr::write_csv(
  supp_caf_subcluster_prop_within_niche,
  file = file.path(
    niche_supplementary_table_dir,
    "niche_caf_subcluster_proportion_within_niche_percent.csv"
  )
)

message(
  "Saved spatial niche supplementary tables to: ",
  niche_supplementary_table_dir
)
