# Summarize spatial niche composition
#
# This script combines spatial niche labels with initial clustering labels and
# CAF subcluster labels, and summarizes cell composition within each spatial
# niche.
#
# Input files are generated by:
#   04_01_niche_build_spatial_niche_knn_matrix.R
#   04_02_niche_cluster_spatial_niches.R
#
# Important design choice:
# The spatial niche kNN matrix is built from combined labels:
# CAF subcluster labels for CAFs (CAF-0 to CAF-8) and initial clustering
# labels for non-CAF cells (Clust.0, Clust.1, ...), after excluding
# unclassified initial clusters.
#
# For downstream summaries and plotting, non-CAF initial cluster labels are
# displayed as Ini-0, Ini-1, ..., while CAF labels are kept as CAF-0 to CAF-8.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directories ---------------------------------------

niche_table_dir <- file.path(xenium_table_dir, "niche_analysis")

fs::dir_create(niche_table_dir)


## Define niche annotations --------------------------------------------------

# Spatial niche IDs are assigned by k-means clustering in 04_02.
# The biological annotations below correspond to the final manually interpreted
# niche identities used in the manuscript.
niche_order <- paste0("niche_", c(2, 3, 8, 9, 5, 6, 1, 4, 7, 10))

niche_annotation <- c(
  "niche_1" = "N7.Plasma cell niche",
  "niche_2" = "N1.Normal acinar niche",
  "niche_3" = "N2.Atrophic acinar niche",
  "niche_4" = "N8.Lymphoid niche",
  "niche_5" = "N5.Islet niche",
  "niche_6" = "N6.Vascular niche",
  "niche_7" = "N9.Lymphoid–myeloid niche",
  "niche_8" = "N3.Normal–PanIN niche",
  "niche_9" = "N4.Cancer niche",
  "niche_10" = "N10.Neuronal niche"
)

niche_annotation_for_csv <- stringr::str_replace_all(
  niche_annotation,
  "\u2013",
  "-"
)

# Initial clusters used for non-CAF label summaries. CAF labels are already
# represented by CAF subcluster labels in the input table generated by 04_01.
initial_cluster_display_order <- as.character(c(
  0, 13, 24,
  33, 12, 1, 17, 30,
  23,
  10, 27,
  20,
  14,
  11,
  34, 3,
  18, 37,
  15,
  16, 2,
  5, 4, 31,
  26,
  29
))

initial_label_display_order <- paste0("Ini-", initial_cluster_display_order)

label_for_summary_order <- c(
  caf_subcluster_display_order,
  initial_label_display_order
)


## Helper functions ----------------------------------------------------------

read_required_csv <- function(file, description) {
  if (!file.exists(file)) {
    stop(description, " not found: ", file, call. = FALSE)
  }

  readr::read_csv(file, show_col_types = FALSE)
}

check_required_columns <- function(data, required_columns, table_name) {
  missing_columns <- setdiff(required_columns, colnames(data))

  if (length(missing_columns) > 0) {
    stop(
      "Missing required columns in ",
      table_name,
      ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  invisible(NULL)
}

make_wide_table <- function(data, label_column, value_column, label_order) {
  data %>%
    dplyr::select(niche, niche_annotation, {{ label_column }}, {{ value_column }}) %>%
    tidyr::pivot_wider(
      names_from = {{ label_column }},
      values_from = {{ value_column }},
      values_fill = 0
    ) %>%
    dplyr::arrange(niche) %>%
    dplyr::select(niche, niche_annotation, dplyr::any_of(label_order))
}


## Read input tables ---------------------------------------------------------

niche_input_label_file <- file.path(
  niche_table_dir,
  "spatial_niche_input_cell_labels.csv"
)

niche_assignment_file <- file.path(
  niche_table_dir,
  "spatial_niche_kmeans_assignment.csv"
)

niche_input_label_table <- read_required_csv(
  niche_input_label_file,
  "Spatial niche input label table"
)

niche_assignment_table <- read_required_csv(
  niche_assignment_file,
  "Spatial niche k-means assignment table"
)

check_required_columns(
  niche_input_label_table,
  c(
    "full_id",
    "tx_id",
    "tx_number",
    "xenium_sample_id",
    "cell_id",
    "local_cell_id",
    "initial_cluster",
    "initial_cell_type",
    "caf_subcluster",
    "label_for_niche_assay"
  ),
  "spatial niche input label table"
)

check_required_columns(
  niche_assignment_table,
  c("full_id", "niche"),
  "spatial niche k-means assignment table"
)


## Combine niche labels with cell labels -------------------------------------

spatial_niche_metadata_table <- niche_input_label_table %>%
  dplyr::inner_join(
    niche_assignment_table %>%
      dplyr::select(full_id, niche),
    by = "full_id"
  ) %>%
  dplyr::mutate(
    niche = factor(.data$niche, levels = niche_order),
    niche_annotation = niche_annotation[as.character(.data$niche)],
    caf_subcluster = factor(
      .data$caf_subcluster,
      levels = caf_subcluster_display_order
    ),
    label_for_summary = dplyr::if_else(
      !is.na(.data$caf_subcluster),
      as.character(.data$caf_subcluster),
      stringr::str_replace(
        .data$label_for_niche_assay,
        "^Clust\\.",
        "Ini-"
      )
    ),
    label_for_summary = factor(
      .data$label_for_summary,
      levels = label_for_summary_order
    )
  ) %>%
  dplyr::relocate(
    niche,
    niche_annotation,
    label_for_summary,
    caf_subcluster,
    .after = label_for_niche_assay
  )

spatial_niche_metadata_table_for_csv <- spatial_niche_metadata_table %>%
  dplyr::mutate(
    niche_annotation = niche_annotation_for_csv[as.character(.data$niche)]
  )

if (any(is.na(spatial_niche_metadata_table$niche))) {
  stop("Some cells have niche IDs not included in niche_order.", call. = FALSE)
}

if (any(is.na(spatial_niche_metadata_table$label_for_summary))) {
  stop("Some cells could not be assigned to a summary label.", call. = FALSE)
}

readr::write_csv(
  spatial_niche_metadata_table_for_csv,
  file = file.path(
    niche_table_dir,
    "spatial_niche_cell_metadata.csv"
  )
)

## Summarize initial cell type composition -----------------------------------

niche_label_count_table <- spatial_niche_metadata_table_for_csv %>%
  dplyr::count(
    niche,
    niche_annotation,
    label_for_summary,
    name = "n_cell",
    .drop = FALSE
  ) %>%
  dplyr::filter(!is.na(.data$niche), !is.na(.data$label_for_summary)) %>%
  dplyr::group_by(.data$niche) %>%
  dplyr::mutate(
    total_cells_in_niche = sum(.data$n_cell),
    prop_within_niche = dplyr::if_else(
      .data$total_cells_in_niche > 0,
      .data$n_cell / .data$total_cells_in_niche,
      NA_real_
    )
  ) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(.data$label_for_summary) %>%
  dplyr::mutate(
    total_cells_in_label = sum(.data$n_cell),
    prop_within_label = dplyr::if_else(
      .data$total_cells_in_label > 0,
      .data$n_cell / .data$total_cells_in_label,
      NA_real_
    )
  ) %>%
  dplyr::ungroup()

readr::write_csv(
  niche_label_count_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_cell_count_by_label.csv"
  )
)

niche_initial_cell_type_composition_table <- spatial_niche_metadata_table_for_csv %>%
  dplyr::count(
    niche,
    niche_annotation,
    initial_cell_type,
    name = "n_cell",
    .drop = FALSE
  ) %>%
  dplyr::filter(!is.na(.data$niche), !is.na(.data$initial_cell_type)) %>%
  dplyr::group_by(.data$niche) %>%
  dplyr::mutate(
    total_cells_in_niche = sum(.data$n_cell),
    prop_within_niche = dplyr::if_else(
      .data$total_cells_in_niche > 0,
      .data$n_cell / .data$total_cells_in_niche,
      NA_real_
    )
  ) %>%
  dplyr::ungroup()

readr::write_csv(
  niche_initial_cell_type_composition_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_initial_cell_type_composition.csv"
  )
)


## Generate wide-format tables -----------------------------------------------

niche_cell_count_wide <- make_wide_table(
  niche_label_count_table,
  label_for_summary,
  n_cell,
  label_for_summary_order
)

niche_label_prop_within_niche_wide <- make_wide_table(
  niche_label_count_table,
  label_for_summary,
  prop_within_niche,
  label_for_summary_order
)

niche_prop_within_label_wide <- make_wide_table(
  niche_label_count_table,
  label_for_summary,
  prop_within_label,
  label_for_summary_order
)

readr::write_csv(
  niche_cell_count_wide,
  file = file.path(
    niche_table_dir,
    "spatial_niche_cell_count_wide.csv"
  )
)

readr::write_csv(
  niche_label_prop_within_niche_wide,
  file = file.path(
    niche_table_dir,
    "spatial_niche_label_proportion_within_niche_wide.csv"
  )
)

readr::write_csv(
  niche_prop_within_label_wide,
  file = file.path(
    niche_table_dir,
    "spatial_niche_proportion_within_label_wide.csv"
  )
)


## Summarize CAF subcluster composition within each niche ---------------------

caf_subcluster_niche_table <- spatial_niche_metadata_table_for_csv %>%
  dplyr::filter(!is.na(.data$caf_subcluster)) %>%
  dplyr::count(
    niche,
    niche_annotation,
    caf_subcluster,
    name = "n_cell",
    .drop = FALSE
  ) %>%
  dplyr::filter(!is.na(.data$niche), !is.na(.data$caf_subcluster)) %>%
  dplyr::group_by(.data$niche) %>%
  dplyr::mutate(
    total_cafs_in_niche = sum(.data$n_cell),
    prop_caf_subcluster_within_niche = dplyr::if_else(
      .data$total_cafs_in_niche > 0,
      .data$n_cell / .data$total_cafs_in_niche,
      NA_real_
    )
  ) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(.data$caf_subcluster) %>%
  dplyr::mutate(
    total_cells_in_caf_subcluster = sum(.data$n_cell),
    prop_niche_within_caf_subcluster = dplyr::if_else(
      .data$total_cells_in_caf_subcluster > 0,
      .data$n_cell / .data$total_cells_in_caf_subcluster,
      NA_real_
    )
  ) %>%
  dplyr::ungroup()


## Save CAF subcluster composition tables ------------------------------------

readr::write_csv(
  caf_subcluster_niche_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_caf_subcluster_composition.csv"
  )
)

caf_subcluster_prop_within_niche_wide <- make_wide_table(
  caf_subcluster_niche_table,
  caf_subcluster,
  prop_caf_subcluster_within_niche,
  caf_subcluster_display_order
)

caf_subcluster_prop_within_subcluster_wide <- make_wide_table(
  caf_subcluster_niche_table,
  caf_subcluster,
  prop_niche_within_caf_subcluster,
  caf_subcluster_display_order
)

readr::write_csv(
  caf_subcluster_prop_within_niche_wide,
  file = file.path(
    niche_table_dir,
    "spatial_niche_caf_subcluster_proportion_within_niche_wide.csv"
  )
)

readr::write_csv(
  caf_subcluster_prop_within_subcluster_wide,
  file = file.path(
    niche_table_dir,
    "spatial_niche_caf_subcluster_proportion_within_subcluster_wide.csv"
  )
)

message(
  "Saved spatial niche composition summaries for ",
  dplyr::n_distinct(spatial_niche_metadata_table$full_id),
  " cells across ",
  dplyr::n_distinct(spatial_niche_metadata_table$niche),
  " spatial niches."
)
