# Cluster spatial niches
#
# This script performs PCA and k-means clustering on the spatial niche kNN
# count matrix generated by:
#   04_01_niche_build_spatial_niche_knn_matrix.R
#
# The resulting k-means clusters are used as spatial niche labels.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(Matrix)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directories ---------------------------------------

niche_table_dir <- file.path(xenium_table_dir, "niche_analysis")
niche_object_dir <- file.path(xenium_object_dir, "niche_analysis")
niche_figure_dir <- file.path(
  xenium_figure_dir,
  "08_04_niche_analysis_figures"
)

fs::dir_create(niche_figure_dir)
fs::dir_create(niche_table_dir)
fs::dir_create(niche_object_dir)


## Read kNN count matrix -----------------------------------------------------

knn_count_matrix_file <- file.path(
  niche_object_dir,
  "spatial_niche_knn_count_matrix.rds"
)

if (!file.exists(knn_count_matrix_file)) {
  stop(
    "Spatial niche kNN count matrix not found: ",
    knn_count_matrix_file,
    call. = FALSE
  )
}

knn_count_matrix <- readRDS(knn_count_matrix_file)


## Normalize kNN count matrix ------------------------------------------------

knn_row_sums <- Matrix::rowSums(knn_count_matrix)

if (any(knn_row_sums == 0)) {
  stop("Some rows of the kNN count matrix have a row sum of zero.", call. = FALSE)
}

knn_count_proportion_matrix <- knn_count_matrix / knn_row_sums

knn_proportion_scaled_matrix <- scale(as.matrix(knn_count_proportion_matrix))


## PCA -----------------------------------------------------------------------

set.seed(niche_random_seed)

niche_pca <- prcomp(
  knn_proportion_scaled_matrix,
  rank. = 30
)

pca_variance_table <- tibble::tibble(
  PC = seq_along(niche_pca$sdev),
  variance_ratio = niche_pca$sdev^2 / sum(niche_pca$sdev^2)
) %>%
  dplyr::mutate(
    cumulative_variance_ratio = cumsum(variance_ratio)
  )

saveRDS(
  niche_pca,
  file = file.path(
    niche_object_dir,
    "spatial_niche_pca.rds"
  )
)

readr::write_csv(
  pca_variance_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_pca_variance.csv"
  )
)


## Evaluate k for k-means clustering -----------------------------------------

if (niche_pc_use > ncol(niche_pca$x)) {
  stop("niche_pc_use exceeds the number of available PCs.", call. = FALSE)
}

set.seed(niche_random_seed)

n_cells <- nrow(niche_pca$x)
n_cells_sampled_for_elbow <- 50000

sampled_cell_indices <- sample.int(
  n = n_cells,
  size = min(n_cells_sampled_for_elbow, n_cells)
)

pca_sampled_for_elbow <- niche_pca$x[
  sampled_cell_indices,
  seq_len(niche_pc_use),
  drop = FALSE
]

k_values <- 2:24

wss <- sapply(
  k_values,
  function(k_value) {
    kmeans(
      pca_sampled_for_elbow,
      centers = k_value,
      nstart = 20,
      iter.max = 50
    )$tot.withinss
  }
)

wss_table <- tibble::tibble(
  k = k_values,
  total_withinss = wss,
  relative_total_withinss = wss / wss[1]
)

readr::write_csv(
  wss_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_kmeans_elbow_wss.csv"
  )
)

elbow_plot <- ggplot(
  wss_table,
  aes(x = .data$k, y = .data$relative_total_withinss)
) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = c(5, 10, 15, 20), color = "gray80") +
  scale_x_continuous(breaks = k_values) +
  labs(
    x = "k\n(Number of spatial niches)",
    y = "Relative within-cluster sum of squares (WSS)",
    title = "Elbow plot for decision of k (number of niches)",
    subtitle = paste0("Sampling: ", min(n_cells_sampled_for_elbow, n_cells))
  ) +
  theme_classic()

ggsave(
  plot = elbow_plot,
  filename = file.path(
    niche_figure_dir,
    "spatial_niche_kmeans_elbow_plot.png"
  ),
  width = 6,
  height = 5,
  dpi = figure_dpi,
  bg = figure_bg
)


## k-means clustering --------------------------------------------------------

set.seed(niche_random_seed)

niche_kmeans <- kmeans(
  niche_pca$x[, seq_len(niche_pc_use), drop = FALSE],
  centers = niche_k,
  nstart = 50,
  iter.max = 100
)

niche_assignment_table <- tibble::tibble(
  full_id = rownames(niche_pca$x),
  niche = paste0("niche_", niche_kmeans$cluster)
)


## Save outputs --------------------------------------------------------------

saveRDS(
  niche_kmeans,
  file = file.path(
    niche_object_dir,
    "spatial_niche_kmeans.rds"
  )
)

readr::write_csv(
  niche_assignment_table,
  file = file.path(
    niche_table_dir,
    "spatial_niche_kmeans_assignment.csv"
  )
)

message(
  "Saved spatial niche k-means assignments for ",
  nrow(niche_assignment_table),
  " cells across ",
  niche_k,
  " spatial niches."
)
