# Create Monocle2 CellDataSet for CAF pseudotime analysis
#
# This script creates a Monocle2 CellDataSet from the CAF-subclustered Xenium
# object. The specified CAF subcluster is excluded, cells are downsampled within
# each remaining CAF subcluster, and highly variable genes are used as ordering
# genes for DDRTree-based trajectory inference.


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(monocle)
  library(Matrix)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))


## Define input and output directories ---------------------------------------

pseudotime_object_dir <- file.path(
  xenium_object_dir,
  "pseudotime_analysis"
)

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

fs::dir_create(pseudotime_object_dir)
fs::dir_create(pseudotime_table_dir)


## Read CAF subcluster object ------------------------------------------------

if (!file.exists(caf_object_file)) {
  stop(
    "CAF subcluster object was not found: ",
    caf_object_file
  )
}

caf_subcluster_object <- readRDS(caf_object_file)

required_metadata_columns <- c(
  "seurat_clusters",
  "orig.ident"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  colnames(caf_subcluster_object@meta.data)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    "Required metadata columns are missing: ",
    paste(missing_metadata_columns, collapse = ", ")
  )
}


## Exclude the specified CAF subcluster and downsample cells -----------------

caf_subcluster_object@graphs <- list()
Seurat::Idents(caf_subcluster_object) <- "seurat_clusters"

excluded_caf_identity <- as.character(
  pseudotime_excluded_caf_subcluster
)

if (!excluded_caf_identity %in% levels(Seurat::Idents(caf_subcluster_object))) {
  stop(
    "The CAF subcluster selected for exclusion was not found: CAF-",
    excluded_caf_identity
  )
}

caf_object_for_pseudotime <- subset(
  caf_subcluster_object,
  idents = excluded_caf_identity,
  invert = TRUE
)

set.seed(pseudotime_random_seed)

caf_object_for_pseudotime <- subset(
  caf_object_for_pseudotime,
  downsample = pseudotime_downsample_per_caf_subcluster
)

caf_object_for_pseudotime <- SeuratObject::JoinLayers(
  caf_object_for_pseudotime
)


## Prepare expression matrix and metadata -----------------------------------

expression_matrix <- Seurat::GetAssayData(
  caf_object_for_pseudotime,
  assay = "RNA",
  layer = "counts"
)

if (nrow(expression_matrix) == 0 || ncol(expression_matrix) == 0) {
  stop("The RNA count matrix is empty after filtering and downsampling.")
}

cell_metadata <- Biobase::AnnotatedDataFrame(
  caf_object_for_pseudotime@meta.data
)

gene_metadata <- data.frame(
  gene_short_name = rownames(expression_matrix),
  row.names = rownames(expression_matrix),
  stringsAsFactors = FALSE
)

feature_metadata <- Biobase::AnnotatedDataFrame(
  gene_metadata
)


## Create Monocle2 CellDataSet ----------------------------------------------

cds <- monocle::newCellDataSet(
  expression_matrix,
  phenoData = cell_metadata,
  featureData = feature_metadata,
  expressionFamily = VGAM::negbinomial.size()
)

cds <- BiocGenerics::estimateSizeFactors(cds)
cds <- BiocGenerics::estimateDispersions(cds)

dispersion_table <- monocle::dispersionTable(cds)


## Define ordering genes ----------------------------------------------------

set.seed(pseudotime_random_seed)

caf_object_for_pseudotime <- Seurat::FindVariableFeatures(
  caf_object_for_pseudotime,
  assay = "RNA",
  nfeatures = pseudotime_n_hvgs
)

ordering_genes <- intersect(
  Seurat::VariableFeatures(caf_object_for_pseudotime),
  rownames(cds)
)

if (length(ordering_genes) == 0) {
  stop("No ordering genes remained after matching Seurat and Monocle genes.")
}

cds <- monocle::setOrderingFilter(
  cds,
  ordering_genes
)


## Reduce dimension and order cells -----------------------------------------

set.seed(pseudotime_random_seed)

cds <- monocle::reduceDimension(
  cds,
  max_components = 2,
  method = "DDRTree"
)

# The first call assigns trajectory states. The second call reorders the
# trajectory using the prespecified root state.
cds <- monocle::orderCells(cds)

available_states <- sort(unique(Biobase::pData(cds)$State))

if (!pseudotime_root_state %in% available_states) {
  stop(
    "The specified root state was not generated by Monocle2. Available states: ",
    paste(available_states, collapse = ", ")
  )
}

cds_rooted <- monocle::orderCells(
  cds,
  root_state = pseudotime_root_state
)


## Create summary objects ---------------------------------------------------

pseudotime_summary <- list(
  excluded_caf_subcluster = paste0(
    "CAF-",
    pseudotime_excluded_caf_subcluster
  ),
  n_hvgs = pseudotime_n_hvgs,
  downsample_per_caf_subcluster = pseudotime_downsample_per_caf_subcluster,
  random_seed = pseudotime_random_seed,
  root_state = pseudotime_root_state,
  trajectory_states = available_states,
  n_cells = ncol(cds_rooted),
  n_genes = nrow(cds_rooted),
  n_ordering_genes = length(ordering_genes),
  ordering_genes = ordering_genes,
  mean_expression_summary = summary(
    dispersion_table$mean_expression
  ),
  dispersion_empirical_summary = summary(
    dispersion_table$dispersion_empirical
  ),
  dispersion_fit_summary = summary(
    dispersion_table$dispersion_fit
  ),
  dispersion_table_na_count = colSums(
    is.na(dispersion_table)
  )
)

summary_table <- tibble::tibble(
  item = c(
    "excluded_caf_subcluster",
    "n_hvgs",
    "downsample_per_caf_subcluster",
    "random_seed",
    "root_state",
    "trajectory_states",
    "n_cells",
    "n_genes",
    "n_ordering_genes"
  ),
  value = as.character(c(
    paste0("CAF-", pseudotime_excluded_caf_subcluster),
    pseudotime_n_hvgs,
    pseudotime_downsample_per_caf_subcluster,
    pseudotime_random_seed,
    pseudotime_root_state,
    paste(available_states, collapse = ","),
    ncol(cds_rooted),
    nrow(cds_rooted),
    length(ordering_genes)
  ))
)


## Save outputs -------------------------------------------------------------

saveRDS(
  cds_rooted,
  file = file.path(
    pseudotime_object_dir,
    "pseudotime_analysis_cds.rds"
  )
)

saveRDS(
  pseudotime_summary,
  file = file.path(
    pseudotime_object_dir,
    "pseudotime_analysis_summary.rds"
  )
)

readr::write_csv(
  summary_table,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_summary.csv"
  )
)
