# Extract pseudotime metadata and state composition
#
# This script extracts cell-level pseudotime metadata and trajectory edge
# coordinates from the rooted Monocle2 CellDataSet generated in 05_01. It also
# summarizes CAF subcluster composition across pseudotime states and links
# pseudotime cells to spatial niche annotations.
#
# Input files are generated by:
#   05_01_pseudotime_create_monocle_cds.R
#   04_03_niche_summarize_spatial_niche_composition.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(monocle)
  library(igraph)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))


## Define input and output paths ---------------------------------------------

pseudotime_object_dir <- file.path(
  xenium_object_dir,
  "pseudotime_analysis"
)

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

niche_table_dir <- file.path(
  xenium_table_dir,
  "niche_analysis"
)

cds_file <- file.path(
  pseudotime_object_dir,
  "pseudotime_analysis_cds.rds"
)

niche_metadata_file <- file.path(
  niche_table_dir,
  "spatial_niche_cell_metadata.csv"
)

fs::dir_create(pseudotime_table_dir)


## Check required input files ------------------------------------------------

if (!file.exists(cds_file)) {
  stop(
    "Pseudotime CellDataSet file was not found:\n",
    cds_file,
    call. = FALSE
  )
}

if (!file.exists(niche_metadata_file)) {
  stop(
    "Spatial niche metadata table was not found:\n",
    niche_metadata_file,
    call. = FALSE
  )
}


## Read Monocle2 CellDataSet -------------------------------------------------

cds <- readRDS(cds_file)


## Extract pseudotime cell metadata ------------------------------------------

pseudotime_coordinate_table <- data.frame(
  component_1 = monocle::reducedDimS(cds)[1, ],
  component_2 = monocle::reducedDimS(cds)[2, ]
) %>%
  tibble::rownames_to_column(var = "cell_id")

state_levels <- paste0(
  "State ",
  sort(unique(Biobase::pData(cds)$State))
)

pseudotime_caf_subcluster_levels <- paste0(
  "CAF-",
  setdiff(
    caf_subcluster_order,
    pseudotime_excluded_caf_subcluster
  )
)

pseudotime_metadata_table <- Biobase::pData(cds) %>%
  dplyr::select(
    cell_id,
    orig.ident,
    seurat_clusters,
    Pseudotime,
    State
  ) %>%
  dplyr::rename(
    tx_id = orig.ident,
    pseudotime = Pseudotime,
    state_number = State
  ) %>%
  dplyr::mutate(
    xenium_sample_id = unname(
      xenium_sample_label_by_tx_id[tx_id]
    ),
    state = factor(
      paste0("State ", state_number),
      levels = state_levels
    ),
    caf_subcluster = factor(
      paste0("CAF-", seurat_clusters),
      levels = pseudotime_caf_subcluster_levels
    )
  ) %>%
  dplyr::select(
    cell_id,
    xenium_sample_id,
    tx_id,
    seurat_clusters,
    caf_subcluster,
    pseudotime,
    state,
    state_number
  ) %>%
  dplyr::left_join(
    pseudotime_coordinate_table,
    by = "cell_id"
  )

if (any(is.na(pseudotime_metadata_table$xenium_sample_id))) {
  stop(
    "Some pseudotime cell IDs did not match the expected Xenium sample ID pattern.",
    call. = FALSE
  )
}

if (any(is.na(pseudotime_metadata_table$caf_subcluster))) {
  stop(
    "Some CAF subclusters were not represented in caf_subcluster_order.",
    call. = FALSE
  )
}

readr::write_csv(
  pseudotime_metadata_table,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_cell_metadata.csv"
  )
)


## Extract trajectory edge table ---------------------------------------------

trajectory_node_table <- t(monocle::reducedDimK(cds)) %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "node")

colnames(trajectory_node_table)[2:3] <- c("component_1", "component_2")

trajectory_edge_table <- igraph::as_data_frame(
  monocle::minSpanningTree(cds),
  what = "edges"
) %>%
  dplyr::left_join(
    trajectory_node_table,
    by = c("from" = "node")
  ) %>%
  dplyr::rename(
    x = component_1,
    y = component_2
  ) %>%
  dplyr::left_join(
    trajectory_node_table,
    by = c("to" = "node")
  ) %>%
  dplyr::rename(
    xend = component_1,
    yend = component_2
  )

readr::write_csv(
  trajectory_edge_table,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_trajectory_edges.csv"
  )
)


## Summarize CAF subcluster composition across pseudotime states --------------

state_caf_subcluster_composition_table <- pseudotime_metadata_table %>%
  dplyr::count(
    state,
    caf_subcluster,
    name = "n_cells",
    .drop = FALSE
  ) %>%
  dplyr::group_by(state) %>%
  dplyr::mutate(
    total_cells_in_state = sum(n_cells),
    proportion_caf_subcluster_within_state = n_cells / total_cells_in_state
  ) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(caf_subcluster) %>%
  dplyr::mutate(
    total_cells_in_caf_subcluster = sum(n_cells),
    proportion_state_within_caf_subcluster = n_cells / total_cells_in_caf_subcluster
  ) %>%
  dplyr::ungroup()

readr::write_csv(
  state_caf_subcluster_composition_table,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_state_caf_subcluster_composition.csv"
  )
)

state_caf_subcluster_count_wide <- state_caf_subcluster_composition_table %>%
  dplyr::select(
    state,
    caf_subcluster,
    n_cells
  ) %>%
  tidyr::pivot_wider(
    names_from = state,
    values_from = n_cells,
    values_fill = 0
  ) %>%
  dplyr::mutate(
    n_total = rowSums(dplyr::across(where(is.numeric)))
  )

readr::write_csv(
  state_caf_subcluster_count_wide,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_state_caf_subcluster_count_wide.csv"
  )
)


## Add spatial niche labels to pseudotime cells -------------------------------

niche_metadata_table <-
  readr::read_csv(
    niche_metadata_file,
    show_col_types = FALSE
  ) %>%
  dplyr::mutate(
    tx_id = stringr::str_replace(
      stringr::str_extract(
        full_id,
        "^TX5K[0-9]{2}"
      ),
      "^TX5K([0-9]{2})$",
      "TX5K_\\1"
    )
  )

if (
  anyDuplicated(
    niche_metadata_table[
      c(
        "cell_id",
        "tx_id"
      )
    ]
  ) > 0
) {
  stop(
    paste(
      "Duplicated combinations of cell_id and tx_id",
      "were found in the spatial niche metadata."
    ),
    call. = FALSE
  )
}

niche_metadata_table_for_join <-
  niche_metadata_table %>%
  dplyr::select(
    cell_id,
    tx_id,
    niche,
    niche_annotation
  )

n_pseudotime_cells <- nrow(pseudotime_metadata_table)

pseudotime_niche_metadata_table <-
  pseudotime_metadata_table %>%
  dplyr::left_join(
    niche_metadata_table_for_join,
    by = c(
      "cell_id",
      "tx_id"
    )
  )

if (nrow(pseudotime_niche_metadata_table) != n_pseudotime_cells) {
  stop(
    "The niche metadata join changed the number of pseudotime cells.",
    call. = FALSE
  )
}

readr::write_csv(
  pseudotime_niche_metadata_table,
  file = file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_cell_metadata_with_niche.csv"
  )
)

