# Pseudotime state DEG and GSEA analysis
#
# This script identifies differentially expressed genes for each pseudotime
# state versus all other states and performs GSEA using Hallmark and selected
# CAF- and hypoxia-related gene sets.
#
# Input files are generated by:
#   05_01_pseudotime_create_monocle_cds.R
#   05_02_pseudotime_extract_metadata_and_state_composition.R


## Load packages -------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(clusterProfiler)
  library(msigdbr)
  library(fs)
})


## Load settings -------------------------------------------------------------

project_dir <- getwd()

if (basename(project_dir) != "PDAC_CAF_hypoxia_analysis") {
  stop(
    "Please open PDAC_CAF_hypoxia_analysis.Rproj before running this script."
  )
}

source(file.path(project_dir, "code", "00_config", "00_01_analysis_parameters.R"))
source(file.path(project_dir, "code", "00_config", "00_02_paths.R"))
source(file.path(project_dir, "code", "00_config", "00_03_genes_and_marker_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_04_annotation_definitions.R"))
source(file.path(project_dir, "code", "00_config", "00_05_helper_functions.R"))


## Define input and output directories ---------------------------------------

pseudotime_table_dir <- file.path(
  xenium_table_dir,
  "pseudotime_analysis"
)

fs::dir_create(pseudotime_table_dir)


## Read Xenium gene identifier mapping ---------------------------------------

xenium_gene_identifier_mapping_file <- file.path(
  xenium_table_dir,
  "xenium_gene_symbol_entrez_mapping.csv"
)

if (!file.exists(xenium_gene_identifier_mapping_file)) {
  stop(
    "Xenium gene identifier mapping table was not found: ",
    xenium_gene_identifier_mapping_file,
    "\nRun 01_02_xenium_gene_identifier_mapping.R first.",
    call. = FALSE
  )
}

xenium_gene_identifier_mapping <- readr::read_csv(
  xenium_gene_identifier_mapping_file,
  show_col_types = FALSE,
  col_types = readr::cols(
    gene_symbol = readr::col_character(),
    entrez_id = readr::col_character(),
    mapping_source = readr::col_character()
  )
)

required_mapping_columns <- c(
  "gene_symbol",
  "entrez_id",
  "mapping_source"
)

if (!all(
  required_mapping_columns %in%
  colnames(xenium_gene_identifier_mapping)
)) {
  stop(
    "The Xenium gene identifier mapping table must contain: ",
    paste(required_mapping_columns, collapse = ", "),
    call. = FALSE
  )
}

if (nrow(xenium_gene_identifier_mapping) == 0) {
  stop(
    "The Xenium gene identifier mapping table is empty.",
    call. = FALSE
  )
}

if (
  anyNA(xenium_gene_identifier_mapping$gene_symbol) ||
  any(xenium_gene_identifier_mapping$gene_symbol == "")
) {
  stop(
    "The Xenium gene identifier mapping table contains missing or empty gene symbols.",
    call. = FALSE
  )
}

if (anyDuplicated(xenium_gene_identifier_mapping$gene_symbol)) {
  stop(
    "The Xenium gene identifier mapping table contains duplicated gene symbols.",
    call. = FALSE
  )
}


## Define input files --------------------------------------------------------

pseudotime_metadata_file <- file.path(
  pseudotime_table_dir,
  "pseudotime_analysis_cell_metadata.csv"
)

if (!file.exists(pseudotime_metadata_file)) {
  stop(
    "Pseudotime metadata file was not found: ",
    pseudotime_metadata_file,
    call. = FALSE
  )
}

if (!file.exists(caf_object_file)) {
  stop(
    "CAF subcluster object was not found: ",
    caf_object_file,
    call. = FALSE
  )
}


## Read pseudotime metadata --------------------------------------------------

pseudotime_metadata_table <- readr::read_csv(
  pseudotime_metadata_file,
  show_col_types = FALSE
)

required_pseudotime_columns <- c(
  "cell_id",
  "state",
  "state_number"
)

missing_pseudotime_columns <- setdiff(
  required_pseudotime_columns,
  colnames(pseudotime_metadata_table)
)

if (length(missing_pseudotime_columns) > 0) {
  stop(
    "Required pseudotime metadata columns are missing: ",
    paste(missing_pseudotime_columns, collapse = ", "),
    call. = FALSE
  )
}

if (anyDuplicated(pseudotime_metadata_table$cell_id) > 0) {
  stop(
    "Duplicated cell_id values were found in the pseudotime metadata.",
    call. = FALSE
  )
}

state_levels <- paste0(
  "State ",
  sort(unique(pseudotime_metadata_table$state_number))
)

pseudotime_metadata_table <- pseudotime_metadata_table %>%
  dplyr::mutate(
    state = factor(
      state,
      levels = state_levels
    )
  )

if (any(is.na(pseudotime_metadata_table$state))) {
  stop(
    "Some state values could not be matched to state_number.",
    call. = FALSE
  )
}


## Read CAF subcluster object ------------------------------------------------

caf_subcluster_object <- readRDS(caf_object_file)

missing_cells <- setdiff(
  pseudotime_metadata_table$cell_id,
  colnames(caf_subcluster_object)
)

if (length(missing_cells) > 0) {
  stop(
    length(missing_cells),
    " pseudotime cells were not found in the CAF subcluster object.",
    call. = FALSE
  )
}


## Prepare Seurat object with pseudotime state labels ------------------------

caf_state_object <- subset(
  caf_subcluster_object,
  cells = pseudotime_metadata_table$cell_id
)

caf_state_object <- SeuratObject::JoinLayers(caf_state_object)

state_by_cell <- setNames(
  as.character(pseudotime_metadata_table$state),
  pseudotime_metadata_table$cell_id
)

caf_state_object$pseudotime_state <- factor(
  state_by_cell[colnames(caf_state_object)],
  levels = state_levels
)

if (any(is.na(caf_state_object$pseudotime_state))) {
  stop(
    "Pseudotime state labels could not be assigned to all cells.",
    call. = FALSE
  )
}

Seurat::Idents(caf_state_object) <- "pseudotime_state"


## DEG analysis for each state versus all other states -----------------------

set.seed(pseudotime_random_seed)

state_deg_table <- Seurat::FindAllMarkers(
  caf_state_object,
  only.pos = FALSE,
  assay = "RNA",
  slot = "data",
  min.pct = 0,
  min.cells.feature = 0,
  min.cells.group = 0,
  logfc.threshold = 0,
  return.thresh = Inf,
  random.seed = pseudotime_random_seed,
  test.use = "wilcox"
)

if (nrow(state_deg_table) == 0) {
  stop(
    "No DEG results were returned by FindAllMarkers().",
    call. = FALSE
  )
}

gene_to_entrez <- xenium_gene_identifier_mapping %>%
  dplyr::select(
    gene_symbol,
    entrez_id
  ) %>%
  tibble::deframe()

state_deg_table <- state_deg_table %>%
  dplyr::mutate(
    entrez_id = gene_to_entrez[gene]
  ) %>%
  dplyr::rename(
    state = cluster
  ) %>%
  dplyr::mutate(
    state = factor(state, levels = state_levels)
  ) %>%
  dplyr::select(
    state,
    gene,
    entrez_id,
    avg_log2FC,
    pct.1,
    pct.2,
    p_val,
    p_val_adj
  ) %>%
  dplyr::arrange(state, dplyr::desc(avg_log2FC))


readr::write_csv(
  state_deg_table,
  file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_state_deg.csv"
  )
)


## Prepare gene sets for GSEA ------------------------------------------------

hallmark_msigdb_table <- msigdbr::msigdbr(
  species = "Homo sapiens",
  category = "H"
)

c2_msigdb_table <- msigdbr::msigdbr(
  species = "Homo sapiens",
  category = "C2"
)

# msigdbr has used both ncbi_gene and entrez_gene across package versions.
get_msigdb_entrez_column <- function(msigdb_table) {
  candidate_columns <- c("ncbi_gene", "entrez_gene")
  available_columns <- intersect(candidate_columns, colnames(msigdb_table))

  if (length(available_columns) == 0) {
    stop(
      "No Entrez gene ID column was found in the msigdbr output.",
      call. = FALSE
    )
  }

  available_columns[[1]]
}

hallmark_entrez_column <- get_msigdb_entrez_column(
  hallmark_msigdb_table
)

hallmark_gene_sets <- hallmark_msigdb_table %>%
  dplyr::transmute(
    term = gs_name,
    gene = as.character(.data[[hallmark_entrez_column]])
  ) %>%
  dplyr::filter(!is.na(gene), gene != "")

kegg_cell_cycle_genes <- c2_msigdb_table %>%
  dplyr::filter(gs_name == "KEGG_CELL_CYCLE") %>%
  dplyr::pull(gene_symbol) %>%
  unique()

if (length(kegg_cell_cycle_genes) == 0) {
  stop(
    "KEGG_CELL_CYCLE was not found in the C2 gene-set collection.",
    call. = FALSE
  )
}

additional_gene_sets_symbol <- dplyr::bind_rows(
  tibble::tibble(
    term = "Buffa_Hypoxia",
    symbol = buffa_hypoxia_genes
  ),
  tibble::tibble(
    term = "Winter_Hypoxia",
    symbol = winter_hypoxia_genes
  ),
  tibble::tibble(
    term = "KEGG_Cell_cycle",
    symbol = kegg_cell_cycle_genes
  ),
  tibble::tibble(
    term = "myCAF_signature",
    symbol = myCAF_xenium_panel
  ),
  tibble::tibble(
    term = "iCAF_signature",
    symbol = iCAF_xenium_panel
  )
) %>%
  dplyr::filter(!is.na(symbol), symbol != "") %>%
  dplyr::distinct(term, symbol)

additional_gene_sets <- additional_gene_sets_symbol %>%
  dplyr::inner_join(
    xenium_gene_identifier_mapping %>%
      dplyr::select(
        gene_symbol,
        entrez_id
      ),
    by = c("symbol" = "gene_symbol")
  ) %>%
  dplyr::filter(!is.na(.data$entrez_id)) %>%
  dplyr::transmute(
    term = .data$term,
    gene = .data$entrez_id
  ) %>%
  dplyr::distinct(
    term,
    gene
  )

term2gene <- dplyr::bind_rows(
  hallmark_gene_sets,
  additional_gene_sets
) %>%
  dplyr::distinct(term, gene)

if (nrow(term2gene) == 0) {
  stop(
    "No gene sets were available for GSEA.",
    call. = FALSE
  )
}


## Run GSEA for each pseudotime state ----------------------------------------


state_gsea_table <- purrr::map_dfr(
  state_levels,
  function(target_state) {
    message("Running GSEA for ", target_state)

    ranked_gene_table <- state_deg_table %>%
      dplyr::filter(state == target_state) %>%
      dplyr::filter(!is.na(entrez_id)) %>%
      dplyr::group_by(entrez_id) %>%
      dplyr::slice_max(
        order_by = abs(avg_log2FC),
        n = 1,
        with_ties = FALSE
      ) %>%
      dplyr::ungroup() %>%
      dplyr::arrange(dplyr::desc(avg_log2FC))

    ranked_log2fc <- ranked_gene_table$avg_log2FC
    names(ranked_log2fc) <- ranked_gene_table$entrez_id

    ranked_log2fc <- sort(
      ranked_log2fc,
      decreasing = TRUE
    )

    if (length(ranked_log2fc) == 0) {
      warning(
        "No ranked genes with Entrez IDs were available for ",
        target_state,
        "."
      )
      return(tibble::tibble())
    }

    set.seed(pseudotime_random_seed)
    
    gsea_result <- clusterProfiler::GSEA(
      geneList = ranked_log2fc,
      TERM2GENE = term2gene,
      minGSSize = 10,
      pvalueCutoff = 1,
      verbose = FALSE,
      eps = 0
    )

    if (nrow(gsea_result@result) == 0) {
      warning(
        "No GSEA results were returned for ",
        target_state,
        "."
      )
      return(tibble::tibble())
    }

    gsea_result@result %>%
      tibble::as_tibble() %>%
      dplyr::mutate(
        state = target_state,
        direction = dplyr::if_else(NES > 0, "UP", "DOWN"),
        .before = ID
      )
  }
)

if (nrow(state_gsea_table) == 0) {
  stop(
    "No GSEA results were returned for any pseudotime state.",
    call. = FALSE
  )
}

state_gsea_table <- state_gsea_table %>%
  dplyr::mutate(
    state = factor(state, levels = state_levels),
    description_for_table = format_gene_set_label_for_table(Description)
  ) %>%
  dplyr::select(
    state,
    direction,
    ID,
    Description,
    description_for_table,
    setSize,
    enrichmentScore,
    NES,
    pvalue,
    p.adjust,
    qvalue,
    rank,
    leading_edge,
    core_enrichment
  ) %>%
  dplyr::arrange(state, dplyr::desc(NES))

readr::write_csv(
  state_gsea_table,
  file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_state_gsea.csv"
  )
)


## Save top positive GSEA results for plotting -------------------------------

state_gsea_top_positive_table <- state_gsea_table %>%
  dplyr::filter(NES > 0) %>%
  dplyr::group_by(state) %>%
  dplyr::slice_max(
    order_by = NES,
    n = 5,
    with_ties = FALSE
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    minus_log10_adjusted_p = -log10(p.adjust)
  ) %>%
  dplyr::arrange(state, dplyr::desc(NES))

readr::write_csv(
  state_gsea_top_positive_table,
  file.path(
    pseudotime_table_dir,
    "pseudotime_analysis_state_gsea_top_positive.csv"
  )
)
